In [629]:
import numpy as np
import pandas as pd

In [630]:
# for display all columns,rows and not truncate the data 
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [631]:
# load the data
df=pd.read_csv('99acres_gandhinagar_properties_final.csv')
df.head()

,Page,Name,BHK,Location,Price,Price_per_sqft,Area_sqft,Area_sqm,Area_type,Status,Description,Builder,Posted_Time,Property_URL,Image_URL
0,1,"3 BHK Flatin Sargasan, Gandhinagar",3 BHK Flat,"Sargasan, Gandhinagar",₹1.26 Cr,"₹4,320 /sqft","2,916 sqft",(271 sqm),Super Built-up Area,Ready To Move,"Experience a new style of living with Altezza by The Palm. It offers an exclusive range of 3 BHK apartments in Sargasan, Gandhinagar. Here is a steal deal for you. Book your 3 BHK apartment here at a never before price of Rs. 1.26 Crore. The unit has a super built-up area of 2916.0 sq. ft. This is a ready to move project. It has been designed keeping every small to large needs of residents in c...",NaN,NaN,https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-altezza-by-the-palm-sargasan-gandhinagar-2916-sqft-npspid-V89041074,https://static.99acres.com/universalapp/img/checkLineGray.svg
1,1,"3 BHK Flatin Pethapur, Gandhinagar",3 BHK Flat,"Pethapur, Gandhinagar",₹51.99 Lac,"₹2,962 /sqft","1,755 sqft",(163 sqm),Super Built-up Area,Under Construction,"Experience a new style of living with Satyamev Royal 5. It offers an exclusive range of 3 BHK apartments in Pethapur, Gandhinagar. Here is a steal deal for you. Book your 3 BHK apartment here at a never before price of Rs. 51.99 Lac. The unit has a super built-up area of 1755.0 sq. ft. This is an under construction project. It has been designed keeping every small to large needs of residents in...",NaN,NaN,https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-satyamev-royal-5-pethapur-gandhinagar-1755-sqft-npspid-V87599244,https://static.99acres.com/universalapp/img/checkLineGray.svg
2,1,"3 BHK Flatin Raysan, Gandhinagar",3 BHK Flat,"Raysan, Gandhinagar",₹97 Lac,"₹5,083 /sqft","1,908 sqft",(177 sqm),Super Built-up Area,Ready To Move,"This is your chance to a 3 bhk apartment / flat for sale in radhe imperial sky raysan gandhinagar . Where luxury comes with affordability. Basic details: You will love this bright and spacious 3 bedroom apartment with 3 bathrooms, modular kitchen, spacious hall and 2 balconies.The balcony offers a great view and is a place to enjoy at any time. This house provides ample natural light and has go...",NaN,NaN,https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-radhe-imperial-sky-raysan-gandhinagar-1908-sqft-spid-R89058182,https://static.99acres.com/universalapp/img/checkLineGray.svg
3,1,"3 BHK Flatin Raysan, Gandhinagar",3 BHK Flat,"Raysan, Gandhinagar",₹1.25 Cr,"₹5,669 /sqft","2,205 sqft",(205 sqm),Carpet Area,Ready To Move,"We are the proud owners of this 3 bhk apartment available in saral skyline, raysan, gandhinagar. This it is a and the unit is located on 9th floor and has a carpet area of 245 sq.Yards. It has 2 bathroom(s) and 2 balcony(s). The unit is located in a co-Operative society.",NaN,NaN,https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-raysan-gandhinagar-2205-sqft-spid-R90201698,https://static.99acres.com/universalapp/img/downArrowNew.png
4,1,"3 BHK Flatin Urjanagar 1, Randesan, Gandhinagar",3 BHK Flat,"Urjanagar 1, Randesan, Gandhinagar",₹79 Lac,"₹4,501 /sqft","1,755 sqft",(163 sqm),Carpet Area,Ready To Move,"Situated on the top floor (8th) of a mid-Rise building in divyajivan aura, urjanagar 1, this 5-10 year old 3 bhk flat offers 1755 sqft of well-Laid space with 3 bedrooms and 3 bathrooms. Available immediately, the unfurnished apartment combines comfort with proximity to several religious landmarks in gandhinagar. Ideal for long-Term residence.",NaN,NaN,https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-divyajivan-aura-urjanagar-1-gandhinagar-1755-sqft-spid-F91063942,https://static.99acres.com/universalapp/img/downArrowNew.png

In [632]:
# information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1884 entries, 0 to 1883
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Page            1884 non-null   int64
 1   Name            1884 non-null   object
 2   BHK             1733 non-null   object
 3   Location        1884 non-null   object
 4   Price           1880 non-null   object
 5   Price_per_sqft  1880 non-null   object
 6   Area_sqft       1884 non-null   object
 7   Area_sqm        1884 non-null   object
 8   Area_type       1484 non-null   object
 9   Status          1884 non-null   object
 10  Description     1626 non-null   object
 11  Builder         1 non-null      object
 12  Posted_Time     11 non-null     object
 13  Property_URL    1884 non-null   object
 14  Image_URL       1884 non-null   object
dtypes: int64(1), object(14)
memory usage: 220.9+ KB

In [633]:
# shape 
print(f"Number of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")

Number of rows: 1884
Number of columns: 15

In [634]:
# check for duplicates
print(f"Number of duplicate rows: {df.duplicated().sum()}")

Number of duplicate rows: 0

In [635]:
# check for missing values
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
Page                 0
Name                 0
BHK                151
Location             0
Price                4
Price_per_sqft       4
Area_sqft            0
Area_sqm             0
Area_type          400
Status               0
Description        258
Builder           1883
Posted_Time       1873
Property_URL         0
Image_URL            0
dtype: int64

In [636]:
df['Builder'].value_counts()

Builder
Builder top floor, spacious and sky view    1
Name: count, dtype: int64

In [637]:
df['Posted_Time'].value_counts()

Posted_Time
This is a new building created 2 years ago                                                                                                                                                                                                                                                                                                                                                         1
Available immediately, this 3 bhk flat spans 1602 sq.Ft. On the 11th floor of a 14-Story high-Rise at psy pramukh trinity, uvarsad, gandhinagar. Built 2 years ago, it includes 3 bedrooms, 2 bathrooms, and comes furnished. Residents enjoy amenities like a gym, clubhouse, power backup, lift, and rainwater harvesting, near schools and hospitals.                                           1
Situated in a well-Maintained society in kalol, gandhinagar, this 1 bhk flat offers 55 sq.Ft. Of unfurnished space on the 6th floor of a 7-Story mid-Rise building. Built 1-5 years ago, it features marble flooring, high ceilings, and essential amenities like visitor parking and on-Call maintenance. Immediate availability near key hospitals and a religious site enhances convenience.    1
Located in shri hari gift city, nava naroda, ahmedabad east, this 1 bhk flat offers 436 sq.Ft. Of living space on the 20th floor of a 35-Floor high-Rise building. Built 1-5 years ago, the apartment is immediately available and unfurnished. Close to schools and multiple hospitals, it combines convenience with a comfortable lifestyle.                                                     1
This 3 bhk unfurnished apartment spans 1157.77 sq.Ft. On the 4th floor of a 14-Story high-Rise in surpath sharnam platinum, koba, gandhinagar. With 3 bedrooms and 3 bathrooms, it's a nearly new property available immediately. Benefits include parking, proximity to educational institutions, shree balaji agora mall, and major highways for easy connectivity.                              1
This unfurnished 2 bhk flat on the 6th floor of a mid-Rise building in ved greens dahegam offers 1188 sq.Ft. Of living space. Built less than a year ago, the apartment features 2 bedrooms and 2 bathrooms. Available for immediate sale, its conveniently close to hospitals, a temple, and essential amenities in gandhinagar.                                                                  1
Available immediately, this 2 bhk flat spans 165 sq.Ft. On the 4th floor of a mid-Rise building in mahalakshmi satvam parklane, sargasan, gandhinagar. Built 1-5 years ago, the residential apartment offers 2 bedrooms and 2 bathrooms with a furnished status. Nearby religious sites and a hospital add to its location benefits.                                                               1
Available immediately, this furnished 2 bhk flat spans 999 sq.Ft. On the 5th floor of a low-Rise building in shukan eye, urjanagar 1, randesan, gandhinagar. Built 5-10 years ago, it offers vaastu compliance, full power backup, lift access, gated security, and on-Call maintenance. Nearby are several renowned temples, enhancing the locations spiritual appeal.                            1
Located in shikshapatri shreeji swastik, sargasan, this furnished 2 bhk flat offers 1440 sq.Ft. On the 12th floor of a high-Rise. Built 1-5 years ago, it includes 2 bathrooms, a modular kitchen, power backup, and parking. Available immediately, it enjoys excellent connectivity to gift city and nearby markets.                                                                             1
Spanning 34,848 sq.Ft., this corner residential plot in magodi, gandhinagar offers immediate availability for development. The land is unfurnished and ready for your vision, situated in a growing neighborhood. With a prime location and clear layout, it presents a unique opportunity for residential construction.                                                                           1
This 3 bhk semifurnished flat spans 1,350 sq.Ft. On the 13th floor of a high-Rise at sharnam platinum, koba, gandhinagar. Built less than a year ago, it offers immediate availability within a gated society. Featuring modular kitchen, 3 bathrooms, and visitor parking, its vaastu compliant and close to infocity and health focus clinic.                                                    1
Name: count, dtype: int64

In [638]:
df[(df["Builder"].notna()) | (df["Posted_Time"].notna())]

,Page,Name,BHK,Location,Price,Price_per_sqft,Area_sqft,Area_sqm,Area_type,Status,Description,Builder,Posted_Time,Property_URL,Image_URL
361,9,"3 BHK Flatin Randheja, Gandhinagar",3 BHK Flat,"Randheja, Gandhinagar",₹55 Lac,"₹5,789 /sqft",950 sqft,(88 sqm),Carpet Area,Ready To Move,NaN,NaN,This is a new building created 2 years ago,https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-polaris-elina-randheja-gandhinagar-950-sqft-spid-Z90915948,https://static.99acres.com/universalapp/img/checkLineGray.svg
456,13,"3 BHK Flatin Uvarsad, Gandhinagar",3 BHK Flat,"Uvarsad, Gandhinagar",₹81.5 Lac,"₹8,232 /sqft","1,602 sqft",(149 sqm),Super Built-up Area,Ready To Move,NaN,NaN,"Available immediately, this 3 bhk flat spans 1602 sq.Ft. On the 11th floor of a 14-Story high-Rise at psy pramukh trinity, uvarsad, gandhinagar. Built 2 years ago, it includes 3 bedrooms, 2 bathrooms, and comes furnished. Residents enjoy amenities like a gym, clubhouse, power backup, lift, and rainwater harvesting, near schools and hospitals.",https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-psy-pramukh-trinity-uvarsad-gandhinagar-1602-sqft-spid-K89854502,https://static.99acres.com/universalapp/img/checkLineGray.svg
1235,44,"1 BHK Flatin Kalol, Gandhinagar",1 BHK Flat,"Kalol, Gandhinagar",₹25 Lac,"₹45,454 /sqft",55 sqft,(5 sqm),Carpet Area,Ready To Move,NaN,NaN,"Situated in a well-Maintained society in kalol, gandhinagar, this 1 bhk flat offers 55 sq.Ft. Of unfurnished space on the 6th floor of a 7-Story mid-Rise building. Built 1-5 years ago, it features marble flooring, high ceilings, and essential amenities like visitor parking and on-Call maintenance. Immediate availability near key hospitals and a religious site enhances convenience.",https://www.99acres.com/1-bhk-bedroom-apartment-flat-for-sale-in-kalol-gandhinagar-55-sqft-spid-K90578694,https://static.99acres.com/universalapp/img/downArrowNew.png
1340,49,"1 BHK Flatin Gift City, Gandhinagar",1 BHK Flat,"Gift City, Gandhinagar",₹95 Lac,"₹21,788 /sqft",436 sqft,(41 sqm),Carpet Area,Ready To Move,NaN,NaN,"Located in shri hari gift city, nava naroda, ahmedabad east, this 1 bhk flat offers 436 sq.Ft. Of living space on the 20th floor of a 35-Floor high-Rise building. Built 1-5 years ago, the apartment is immediately available and unfurnished. Close to schools and multiple hospitals, it combines convenience with a comfortable lifestyle.",https://www.99acres.com/1-bhk-bedroom-apartment-flat-for-sale-in-gift-city-gandhinagar-436-sqft-spid-E89814538,https://static.99acres.com/universalapp/img/downArrowNew.png
1416,52,"3 BHK Flatin Koba, Gandhinagar",3 BHK Flat,"Koba, Gandhinagar",₹1.2 Cr,"₹10,364 /sqft","1,157 sqft",(107 sqm),Carpet Area,Ready To Move,NaN,NaN,"This 3 bhk unfurnished apartment spans 1157.77 sq.Ft. On the 4th floor of a 14-Story high-Rise in surpath sharnam platinum, koba, gandhinagar. With 3 bedrooms and 3 bathrooms, it's a nearly new property available immediately. Benefits include parking, proximity to educational institutions, shree balaji agora mall, and major highways for easy connectivity.",https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-surpath-sharnam-platinum-koba-gandhinagar-1158-sqft-spid-V89466724,https://static.99acres.com/universalapp/img/checkLineGray.svg
1429,52,"2 BHK Flatin Dahegam, Gandhinagar",2 BHK Flat,"Dahegam, Gandhinagar",₹37 Lac,"₹3,198 /sqft","1,188 sqft",(110 sqm),Built-up Area,Ready To Move,NaN,NaN,"This unfurnished 2 bhk flat on the 6th floor of a mid-Rise building in ved greens dahegam offers 1188 sq.Ft. Of living space. Built less than a year ago, the apartment features 2 bedrooms and 2 bathrooms. Available for immediate sale, its conveniently close to hospitals, a temple, and essential amenities in gandhinagar.",https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-dhegam-gandhinagar-1188-sqft-spid-W89344809,https://static.99acres.com/universalapp/img/downArrowNew.png
1453,53,"2 BHK Flatin Sargasan, Gandhinagar",2 BHK Flat,"Sargasan, Gandhinagar",₹65 Lac,"₹39,394 /sqft",165 sqft,(15 sqm),Carpet Area,Ready To Move,NaN,NaN,"Available immediately, this 2 bhk flat spans 165 sq.Ft. On the 4th floor of a mid-Rise building in mahalakshmi satvam parklane, sargasan, gandhinagar. Built 1-5 years ago, the residential apartment offers 2 bedrooms and 2 bathrooms with a furnished status. Nearby religious sites and a hospital add to its location benefits.",https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-mahalakshmi-satvam-parklane-sargasan-gandhinagar-165-sqft-spid-N89168659,https://static.99acres.com/universalapp/img/checkLineGray.svg
1502,55,"2 BHK Flatin Urjanagar 1, Randesan, Gandhinagar",2 BHK Flat,"Urjanagar 1, Randesan, Gandhinagar",₹52 Lac,"₹5,205 /sqft",999 sqft,(93 sqm),Carpet Area,Ready To Move,NaN,NaN,"Available immediately, this furnished 2 bhk flat spans 999 sq.Ft. On the 5th floor of a low-Rise building in shukan eye, urjanagar 1, randesan, gandhinagar. Built 5-10 years ago, it offers vaastu compliance, full power backup, lift access, gated security, and on-Call maintenance. Nearby are several renowned temples, enhancing the locations spiritual appeal.",https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-shukan-eye-urjanagar-1-gandhinagar-999-sqft-spid-P88789580,https://static.99acres.com/universalapp/img/downArrowNew.png
1556,57,"2 BHK Flatin Sargasan, Gandhinagar",2 BHK Flat,"Sargasan, Gandhinagar",₹80 Lac,"₹5,556 /sqft","1,440 sqft",(134 sqm),Super Built-up Area,Ready To Move,NaN,NaN,"Located in shikshapatri shreeji swastik, sargasan, this furnished 2 bhk flat offers 1440 sq.Ft. On the 12th floor of a high-Rise. Built 1-5 years ago, it includes 2 bathrooms, a modular kitchen, power backup, and parking. Available immediately, it enjoys excellent connectivity to gift city and nearby markets.",https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-shikshapatri-shreeji-swastik-sargasan-gandhinagar-1440-sqft-spid-A88330738,https://static.99acres.com/universalapp/img/checkLineGray.svg
1574,58,"Residential land / Plotin Magodi, Gandhinagar",NaN,"Magodi, Gandhinagar",₹3 Cr,₹551 /sqft,"54,450 sqft","(5,059 sqm)",NaN,Ready To Move,NaN,NaN,"Spanning 34,848 sq.Ft., this corner residential plot in magodi, gandhinagar offers immediate availability for development. The land is unfurnished and ready for your vision, situated in a growing neighborhood. With a prime location and clear layout, it presents a unique opportunity for residential construction.",https://www.99acres.com/residential-land-plot-for-sale-in-gandhinagar-3872-sqyd-spid-B88302832,https://static.99acres.com/universalapp/img/downArrowNew.png
1655,61,"2 BHK Flatin Sector 26, Gandhinagar",2 BHK Flat,"Sector 26, Gandhinagar",₹49.9 Lac,"₹3,905 /sqft","1,278 sqft",(119 sqm),Carpet Area,Ready To Move,NaN,"Builder top floor, spacious and sky view",NaN,https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-sector-26-gandhinagar-1278-sqft-spid-J87719466,https://static.99acres.com/universalapp/img/downArrowNew.png
1711,64,"3 BHK Flatin Koba, Gandhinagar",3 BHK Flat,"Koba, Gandhinagar",₹1.1 Cr,"₹8,148 /sqft","1,350 sqft",(125 sqm),Carpet Area,Ready To Move,NaN,NaN,"This 3 bhk semifurnished flat spans 1,350 sq.Ft. On the 13th floor of a high-Rise at sharnam platinum, koba, gandhinagar. Built less than a year ago, it offers immediate availability within a gated society. Featuring modular kitchen, 3 bathrooms, and visitor parking, its vaastu compliant and close to infocity and health focus clinic.",https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-koba-gandhinagar-1350-sqft-spid-T87218220,https://static.99acres.com/universalapp/img/downArrowNew.png

Due to scraping inconsistency, some description text was mistakenly stored in the Builder and Posted_Time columns. Merged that text back into the Description column and removed both features.

In [639]:
# Step 1 : Replace NaN with empty string
df["Description"] = df["Description"].fillna("")
df["Builder"] = df["Builder"].fillna("")
df["Posted_Time"] = df["Posted_Time"].fillna("")

# Step 2 : Add Builder and Posted_Time text into Description
df["Description"] = df["Description"] + " " + df["Builder"]
df["Description"] = df["Description"] + " " + df["Posted_Time"]

# Step 3 : Remove extra spaces
df["Description"] = df["Description"].str.replace(r"\s+", " ", regex=True).str.strip()

# Step 4 : Drop Builder and Posted_Time columns
df.drop(columns=["Builder", "Posted_Time"], inplace=True)

In [640]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1884 entries, 0 to 1883
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Page            1884 non-null   int64
 1   Name            1884 non-null   object
 2   BHK             1733 non-null   object
 3   Location        1884 non-null   object
 4   Price           1880 non-null   object
 5   Price_per_sqft  1880 non-null   object
 6   Area_sqft       1884 non-null   object
 7   Area_sqm        1884 non-null   object
 8   Area_type       1484 non-null   object
 9   Status          1884 non-null   object
 10  Description     1884 non-null   object
 11  Property_URL    1884 non-null   object
 12  Image_URL       1884 non-null   object
dtypes: int64(1), object(12)
memory usage: 191.5+ KB

Property_URL are not removed for future use such as dashboard integration, duplicate detection, re-scraping, and advanced image-based real estate analysis.

In [641]:
# Page column is removed because it only represents the scraped pagination number and does not contribute to analysis or modeling.

df.drop(columns=["Page"], inplace=True)

In [642]:
df['Price'].value_counts()

Price
₹65 Lac       63
₹60 Lac       52
₹75 Lac       52
₹55 Lac       43
₹50 Lac       43
₹1.1 Cr       42
₹85 Lac       41
₹95 Lac       37
₹70 Lac       36
₹80 Lac       36
₹1 Cr         33
₹1.2 Cr       32
₹1.5 Cr       30
₹90 Lac       27
₹45 Lac       25
₹72 Lac       25
₹1.25 Cr      23
₹1.05 Cr      20
₹1.3 Cr       20
₹3 Cr         20
₹40 Lac       19
₹35 Lac       19
₹52 Lac       19
₹1.4 Cr       17
₹1.45 Cr      16
₹62 Lac       16
₹1.55 Cr      15
₹2 Cr         15
₹67 Lac       15
₹1.15 Cr      15
₹78 Lac       15
₹2.5 Cr       14
₹54 Lac       13
₹58 Lac       13
₹51 Lac       12
₹1.6 Cr       12
₹42 Lac       12
₹2.25 Cr      11
₹1.11 Cr      11
₹2.2 Cr       11
₹82 Lac       11
₹79 Lac       10
₹1.35 Cr      10
₹53 Lac       10
₹3.25 Cr      10
₹77 Lac        9
₹56 Lac        9
₹3.5 Cr        9
₹49 Lac        9
₹46 Lac        9
₹1.65 Cr       9
₹48 Lac        8
₹1.41 Cr       8
₹57 Lac        8
₹32 Lac        8
₹68 Lac        8
₹97 Lac        8
₹59 Lac        7
₹61 Lac        7
₹2.6 Cr        7
₹25 Lac        7
₹5 Cr          7
₹1.39 Cr       7
₹47 Lac        7
₹1.18 Cr       7
₹36 Lac        7
₹1.8 Cr        7
₹22 Lac        7
₹6.5 Cr        7
₹1.7 Cr        7
₹30 Lac        7
₹2.8 Cr        7
₹1.21 Cr       7
₹69 Lac        6
₹1.29 Cr       6
₹1.75 Cr       6
₹4 Cr          6
₹63 Lac        6
₹99 Lac        6
₹2.7 Cr        6
₹20 Lac        6
₹8 Cr          6
₹2.1 Cr        6
₹2.51 Cr       6
₹37 Lac        6
₹15 Lac        6
₹38 Lac        6
₹1.9 Cr        6
₹86 Lac        6
₹98 Lac        5
₹1.84 Cr       5
₹79.6 Lac      5
₹29 Lac        5
₹85.6 Lac      5
₹3.35 Cr       5
₹41 Lac        5
₹16 Lac        5
₹6.25 Cr       5
₹92 Lac        5
₹83 Lac        5
₹76 Lac        5
₹1.16 Cr       5
₹1.42 Cr       4
₹4.5 Cr        4
₹1.03 Cr       4
₹1.51 Cr       4
₹1.14 Cr       4
₹34 Lac        4
₹71 Lac        4
₹1.28 Cr       4
₹5.5 Cr        4
₹9 Cr          4
₹1.07 Cr       4
₹43 Lac        4
₹3.8 Cr        4
₹4.97 Cr       4
₹3.2 Cr        4
₹2.3 Cr        4
₹27 Lac        4
₹4.25 Cr       4
₹1.01 Cr       3
₹2.31 Cr       3
₹2.4 Cr        3
₹28 Lac        3
₹12 Lac        3
₹21 Lac        3
₹1.85 Cr       3
₹1.46 Cr       3
₹2.11 Cr       3
₹1.36 Cr       3
₹1.12 Cr       3
₹73 Lac        3
₹1.68 Cr       3
₹87 Lac        3
₹2.35 Cr       3
₹13.5 Cr       3
₹24 Lac        3
₹93 Lac        3
₹3.75 Cr       3
₹91 Lac        3
₹2.65 Cr       3
₹84 Lac        3
₹9.5 Cr        3
₹1.26 Cr       3
₹66 Lac        3
₹1.13 Cr       3
₹2.21 Cr       2
₹18 Lac        2
₹12.5 Lac      2
₹33.51 Lac     2
₹1.56 Cr       2
₹25.5 Lac      2
₹1.24 Cr       2
₹33 Lac        2
₹3.3 Cr        2
₹1.27 Cr       2
₹15.5 Lac      2
₹1.61 Cr       2
₹1.66 Cr       2
₹35.5 Lac      2
₹44 Lac        2
₹26 Lac        2
₹1.63 Cr       2
₹15 Cr         2
₹1.57 Cr       2
₹1.19 Cr       2
₹49.5 Lac      2
₹17 Lac        2
₹7.5 Cr        2
₹2.75 Cr       2
₹2.34 Cr       2
₹7 Cr          2
₹3.21 Cr       2
₹18 Cr         2
₹1.48 Cr       2
₹1.38 Cr       2
₹2.55 Cr       2
₹12 Cr         2
₹2.15 Cr       2
₹1.31 Cr       2
₹1.82 Cr       2
₹1.69 Cr       2
₹96 Lac        2
₹2.29 Cr       2
₹2.47 Cr       2
₹1.37 Cr       2
₹48.5 Lac      2
₹2.97 Cr       2
₹5.25 Cr       2
₹2.12 Cr       2
₹1.95 Cr       2
₹1.44 Cr       2
₹2.08 Cr       2
₹75.6 Lac      2
₹4.94 Cr       2
₹4.1 Cr        2
₹2.45 Cr       2
₹1.08 Cr       2
₹89 Lac        2
₹3.26 Cr       2
₹6 Cr          2
₹74 Lac        2
₹10 Lac        2
₹31 Lac        2
₹1.09 Cr       2
₹39 Lac        2
₹1.67 Cr       2
₹51.99 Lac     1
₹53.26 Lac     1
₹55.55 Lac     1
₹71.75 Lac     1
₹85.21 Lac     1
₹11.5 Lac      1
₹79.75 Lac     1
₹2.13 Cr       1
₹37.51 Lac     1
₹14.02 Lac     1
₹2.81 Cr       1
₹2.71 Cr       1
₹49.9 Lac      1
₹13 Cr         1
₹63.5 Lac      1
₹39.75 Lac     1
₹30.5 Lac      1
₹11 Lac        1
₹7 Lac         1
₹19 Lac        1
₹10.25 Lac     1
₹82.56 Lac     1
₹14 Lac        1
₹6.55 Cr       1
₹4.56 Cr       1
₹3.76 Cr       1
₹3.7 Cr        1
₹64 Lac        1
₹1.22 Cr       1
₹1.73 Cr       1
₹4.32 Cr       1
₹10.5 Cr       1
₹8.25 Cr       1
₹60.2 Lac      1
₹55.5 Lac      1
₹92.5 Lac      1
₹3.57 Cr       1
₹9.45 Cr       1
₹7.55 Cr       1
₹1.81 Cr       1
₹82.8 Lac      1
₹5.99 Cr       1
₹62.85 Lac     1
₹92.2 Lac      1
₹3.88 Cr       1
₹67.32 Lac     1
₹99.5 Lac      1
₹77.85 Lac     1
₹62.9 Lac      1
₹65.45 Lac     1
₹3.56 Cr       1
₹97.85 Lac     1
₹62.7 Lac      1
₹3.48 Cr       1
₹1.58 Cr       1
₹2.38 Cr       1
₹2.07 Cr       1
₹74.82 Lac     1
₹3.15 Cr       1
₹3.31 Cr       1
₹6.19 Cr       1
₹3.04 Cr       1
₹86.4 Lac      1
₹1.79 Cr       1
₹59.4 Lac      1
₹97.66 Lac     1
₹4.17 Cr       1
₹64.61 Lac     1
₹62.56 Lac     1
₹1.62 Cr       1
₹1.23 Cr       1
₹58.5 Lac      1
₹63.72 Lac     1
₹37.74 Lac     1
₹1.32 Cr       1
₹71.5 Lac      1
₹78.8 Lac      1
₹68.15 Lac     1
₹91.19 Lac     1
₹91.2 Lac      1
₹5.35 Cr       1
₹4.76 Cr       1
₹63.48 Lac     1
₹68.68 Lac     1
₹2.72 Cr       1
₹2.54 Cr       1
₹2.46 Cr       1
₹2.96 Cr       1
₹3.41 Cr       1
₹2.42 Cr       1
₹81.5 Lac      1
₹34.99 Lac     1
₹3.1 Cr        1
₹3.65 Cr       1
₹2.05 Cr       1
₹62.3 Lac      1
₹3.51 Cr       1
₹3.58 Cr       1
₹22.5 Cr       1
₹59.85 Lac     1
₹88.35 Lac     1
₹2.9 Cr        1
₹6.1 Cr        1
₹17.63 Cr      1
₹3.4 Cr        1
₹8.4 Cr        1
₹2.18 Cr       1
₹10.35 Cr      1
₹91.88 Lac     1
₹30 Cr         1
₹93.07 Lac     1
₹81.81 Lac     1
₹8.51 Cr       1
₹3.62 Cr       1
₹94.85 Lac     1
₹81 Lac        1
₹1.34 Cr       1
₹85.85 Lac     1
₹78.75 Lac     1
₹1.02 Cr       1
₹5.03 Cr       1
₹44.17 Lac     1
₹2.59 Cr       1
₹65.75 Lac     1
₹5.4 Cr        1
₹3.33 Cr       1
₹32.5 Lac      1
₹4.15 Cr       1
₹3.02 Cr       1
₹2.91 Cr       1
₹61.5 Lac      1
₹69.5 Lac      1
₹91.5 Lac      1
₹3.43 Cr       1
₹1.99 Cr       1
₹1.98 Cr       1
₹4.95 Cr       1
₹58.51 Lac     1
₹6.39 Cr       1
₹33.5 Lac      1
₹3.85 Cr       1
₹1.53 Cr       1
₹48.85 Lac     1
₹2.24 Cr       1
₹1.83 Cr       1
₹2.48 Cr       1
₹18.5 Lac      1
₹36.5 Lac      1
₹42.5 Lac      1
₹24.05 Cr      1
₹64.51 Lac     1
₹22.5 Lac      1
₹32 Cr         1
₹2.1 Lac       1
₹1.97 Cr       1
₹1.76 Cr       1
₹5.2 Cr        1
₹35.51 Lac     1
₹16 Cr         1
₹7.25 Cr       1
₹1.71 Cr       1
₹5.34 Cr       1
₹100 Lac       1
₹2.49 Cr       1
₹84.24 Lac     1
₹26.5 Lac      1
₹53.64 Lac     1
₹1.78 Cr       1
₹1.77 Cr       1
₹27.5 Lac      1
₹45.51 Lac     1
₹2.85 Cr       1
₹43.5 Lac      1
₹1.94 Cr       1
₹80.5 Lac      1
₹2.32 Cr       1
₹37.71 Lac     1
₹46.5 Lac      1
₹88 Lac        1
₹86.7 Lac      1
₹3.99 Cr       1
₹53.55 Lac     1
₹39.5 Lac      1
₹72.11 Lac     1
₹86.5 Lac      1
₹8 Lac         1
₹6 Lac         1
₹3.6 Cr        1
₹54.34 Lac     1
₹55.01 Lac     1
₹65.5 Lac      1
₹60.5 Lac      1
Name: count, dtype: int64

In [643]:
df[df["Price"].isna()]

,Name,BHK,Location,Price,Price_per_sqft,Area_sqft,Area_sqm,Area_type,Status,Description,Property_URL,Image_URL
1118,"Residential land / Plotin Gift City, Gandhinagar",NaN,"Gift City, Gandhinagar",NaN,NaN,"27,225 sqft","(2,529 sqm)",NaN,Ready To Move,This is for investment purpose and farm house purpose in gift zone. Call for more details,https://www.99acres.com/residential-land-plot-for-sale-in-gift-city-gandhinagar-1936-sq-yard-r11-spid-M72947711,https://static.99acres.com/universalapp/img/downArrowNew.png
1468,"3 BHK Flatin Sargasan, Gandhinagar",3 BHK Flat,"Sargasan, Gandhinagar",NaN,NaN,275 sqft,(26 sqm),Carpet Area,Ready To Move,"Located in the vibrant polaris casarica, sargasan, this unfurnished 3 bhk flat spans 275 sq.Ft. On the 1st floor of a 13-Story high-Rise. With 3 bathrooms, immediate availability, and access to parking, gym, clubhouse, and lift, it offers convenient living close to swagat holiday mall, nh147, gift city, infocity, and karnavati university.",https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-polaris-casarica-sargasan-gandhinagar-275-sqft-spid-A89075718,https://static.99acres.com/universalapp/img/checkLineGray.svg
1837,"2 BHK Flatin Gift City, Gandhinagar",2 BHK Flat,"Gift City, Gandhinagar",NaN,NaN,81 sqft,(8 sqm),Carpet Area,Under Construction,,https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-vida-by-nila-spaces-gift-city-gandhinagar-81-sqft-spid-R85701188,https://static.99acres.com/universalapp/img/checkLineGray.svg
1849,"3 Bedroom Housein Dahegam, Gandhinagar",3 BHK,"Dahegam, Gandhinagar",NaN,NaN,100 sqft,(9 sqm),NaN,Ready To Move,"We are the proud owners of this 3 bhk apartment available in , dahegam, gandhinagar. This semi-Furnished apartment is a 5-10 year old property. Price on request. it is a resale and a ready to move in apartment. The unit is located on null floor and has . It has 1 bathroom(s) and 3 balcony(s). The ownership is freehold type. The apartment has 1 covered parking and 1 open parking.",https://www.99acres.com/3-bhk-bedroom-independent-house-villa-for-sale-in-dhegam-gandhinagar-100-sqft-spid-Z85624590,https://static.99acres.com/universalapp/img/downArrowNew.png

In [644]:
# Removing rows with missing Price values because Price is a critical variable for analysis and filling them with mean or median could introduce bias, and the number of missing entries is very small compared to the dataset size.

df.dropna(subset=["Price"], inplace=True)

In [645]:
# Function to convert all prices values into Lakhs

def convert_to_lakh(price):

    # Remove ₹ symbol and extra spaces
    price = price.replace("₹", "").strip()

    # Convert Crore to Lakh
    if "Cr" in price:
        value = float(price.replace("Cr", "").strip()) * 100

    # Keep Lakh as it is
    elif "Lac" in price:
        value = float(price.replace("Lac", "").strip())

    else:
        return None

    return value

In [646]:
df['Price']=df["Price"].apply(convert_to_lakh)

In [647]:
df['Price'].value_counts()

Price
65.00      63
75.00      52
60.00      52
50.00      43
55.00      43
110.00     42
85.00      41
95.00      37
80.00      36
70.00      36
100.00     34
120.00     32
150.00     30
90.00      27
45.00      25
72.00      25
125.00     23
130.00     20
105.00     20
300.00     20
40.00      19
35.00      19
52.00      19
140.00     17
62.00      16
145.00     16
155.00     15
200.00     15
67.00      15
78.00      15
115.00     15
250.00     14
58.00      13
54.00      13
51.00      12
160.00     12
42.00      12
111.00     11
225.00     11
220.00     11
82.00      11
79.00      10
135.00     10
53.00      10
325.00     10
165.00      9
77.00       9
46.00       9
350.00      9
56.00       9
49.00       9
141.00      8
32.00       8
68.00       8
57.00       8
48.00       8
97.00       8
280.00      7
59.00       7
180.00      7
22.00       7
30.00       7
170.00      7
61.00       7
118.00      7
25.00       7
47.00       7
121.00      7
500.00      7
139.00      7
650.00      7
260.00      7
36.00       7
99.00       6
800.00      6
400.00      6
251.00      6
129.00      6
210.00      6
270.00      6
86.00       6
20.00       6
190.00      6
37.00       6
15.00       6
175.00      6
38.00       6
69.00       6
63.00       6
76.00       5
116.00      5
29.00       5
41.00       5
83.00       5
98.00       5
16.00       5
92.00       5
79.60       5
625.00      5
184.00      5
85.60       5
335.00      5
43.00       4
27.00       4
34.00       4
497.00      4
114.00      4
550.00      4
320.00      4
103.00      4
142.00      4
128.00      4
71.00       4
107.00      4
230.00      4
425.00      4
450.00      4
380.00      4
900.00      4
151.00      4
87.00       3
112.00      3
231.00      3
126.00      3
66.00       3
113.00      3
136.00      3
168.00      3
1350.00     3
375.00      3
235.00      3
146.00      3
211.00      3
93.00       3
950.00      3
91.00       3
24.00       3
73.00       3
240.00      3
185.00      3
28.00       3
84.00       3
265.00      3
12.00       3
21.00       3
101.00      3
119.00      2
25.50       2
161.00      2
127.00      2
17.00       2
15.50       2
49.50       2
330.00      2
275.00      2
31.00       2
109.00      2
39.00       2
124.00      2
35.50       2
157.00      2
221.00      2
33.51       2
321.00      2
148.00      2
12.50       2
48.50       2
44.00       2
750.00      2
156.00      2
26.00       2
1500.00     2
1800.00     2
700.00      2
163.00      2
215.00      2
166.00      2
229.00      2
137.00      2
18.00       2
234.00      2
494.00      2
74.00       2
96.00       2
169.00      2
525.00      2
212.00      2
297.00      2
1200.00     2
247.00      2
138.00      2
131.00      2
208.00      2
326.00      2
195.00      2
75.60       2
600.00      2
89.00       2
108.00      2
255.00      2
410.00      2
245.00      2
182.00      2
144.00      2
10.00       2
33.00       2
167.00      2
639.00      1
63.50       1
54.34       1
51.99       1
60.50       1
360.00      1
655.00      1
14.00       1
82.56       1
10.25       1
19.00       1
7.00        1
11.00       1
30.50       1
39.75       1
49.90       1
271.00      1
92.20       1
62.85       1
599.00      1
82.80       1
65.45       1
62.90       1
77.85       1
357.00      1
92.50       1
55.50       1
60.20       1
825.00      1
315.00      1
74.82       1
64.00       1
370.00      1
376.00      1
456.00      1
99.50       1
67.32       1
388.00      1
1050.00     1
432.00      1
173.00      1
122.00      1
179.00      1
86.40       1
238.00      1
158.00      1
348.00      1
132.00      1
181.00      1
755.00      1
945.00      1
304.00      1
619.00      1
331.00      1
62.70       1
97.85       1
356.00      1
91.20       1
91.19       1
68.15       1
58.50       1
123.00      1
162.00      1
62.56       1
64.61       1
417.00      1
97.66       1
59.40       1
59.85       1
2250.00     1
358.00      1
341.00      1
296.00      1
246.00      1
254.00      1
272.00      1
68.68       1
365.00      1
310.00      1
34.99       1
207.00      1
78.80       1
71.50       1
63.48       1
476.00      1
535.00      1
91.88       1
1035.00     1
218.00      1
840.00      1
340.00      1
1763.00     1
610.00      1
290.00      1
88.35       1
91.50       1
69.50       1
61.50       1
78.75       1
85.85       1
134.00      1
81.00       1
94.85       1
362.00      1
851.00      1
81.81       1
93.07       1
3000.00     1
248.00      1
183.00      1
37.74       1
63.72       1
351.00      1
62.30       1
205.00      1
81.50       1
242.00      1
65.75       1
259.00      1
44.17       1
503.00      1
224.00      1
58.51       1
495.00      1
198.00      1
199.00      1
343.00      1
520.00      1
102.00      1
32.50       1
333.00      1
540.00      1
291.00      1
302.00      1
176.00      1
197.00      1
2.10        1
3200.00     1
22.50       1
64.51       1
2405.00     1
42.50       1
36.50       1
18.50       1
37.71       1
232.00      1
80.50       1
194.00      1
53.64       1
26.50       1
84.24       1
249.00      1
534.00      1
171.00      1
725.00      1
1600.00     1
35.51       1
285.00      1
45.51       1
27.50       1
415.00      1
48.85       1
153.00      1
385.00      1
33.50       1
43.50       1
177.00      1
178.00      1
37.51       1
213.00      1
79.75       1
11.50       1
85.21       1
71.75       1
55.55       1
53.26       1
65.50       1
55.01       1
281.00      1
14.02       1
6.00        1
8.00        1
86.50       1
72.11       1
39.50       1
53.55       1
399.00      1
86.70       1
88.00       1
46.50       1
1300.00     1
Name: count, dtype: int64

In [648]:
df.rename(columns={"Price": "Price (INR in Lakhs)"}, inplace=True)
df.head()

,Name,BHK,Location,Price (INR in Lakhs),Price_per_sqft,Area_sqft,Area_sqm,Area_type,Status,Description,Property_URL,Image_URL
0,"3 BHK Flatin Sargasan, Gandhinagar",3 BHK Flat,"Sargasan, Gandhinagar",126.00,"₹4,320 /sqft","2,916 sqft",(271 sqm),Super Built-up Area,Ready To Move,"Experience a new style of living with Altezza by The Palm. It offers an exclusive range of 3 BHK apartments in Sargasan, Gandhinagar. Here is a steal deal for you. Book your 3 BHK apartment here at a never before price of Rs. 1.26 Crore. The unit has a super built-up area of 2916.0 sq. ft. This is a ready to move project. It has been designed keeping every small to large needs of residents in c...",https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-altezza-by-the-palm-sargasan-gandhinagar-2916-sqft-npspid-V89041074,https://static.99acres.com/universalapp/img/checkLineGray.svg
1,"3 BHK Flatin Pethapur, Gandhinagar",3 BHK Flat,"Pethapur, Gandhinagar",51.99,"₹2,962 /sqft","1,755 sqft",(163 sqm),Super Built-up Area,Under Construction,"Experience a new style of living with Satyamev Royal 5. It offers an exclusive range of 3 BHK apartments in Pethapur, Gandhinagar. Here is a steal deal for you. Book your 3 BHK apartment here at a never before price of Rs. 51.99 Lac. The unit has a super built-up area of 1755.0 sq. ft. This is an under construction project. It has been designed keeping every small to large needs of residents in...",https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-satyamev-royal-5-pethapur-gandhinagar-1755-sqft-npspid-V87599244,https://static.99acres.com/universalapp/img/checkLineGray.svg
2,"3 BHK Flatin Raysan, Gandhinagar",3 BHK Flat,"Raysan, Gandhinagar",97.00,"₹5,083 /sqft","1,908 sqft",(177 sqm),Super Built-up Area,Ready To Move,"This is your chance to a 3 bhk apartment / flat for sale in radhe imperial sky raysan gandhinagar . Where luxury comes with affordability. Basic details: You will love this bright and spacious 3 bedroom apartment with 3 bathrooms, modular kitchen, spacious hall and 2 balconies.The balcony offers a great view and is a place to enjoy at any time. This house provides ample natural light and has go...",https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-radhe-imperial-sky-raysan-gandhinagar-1908-sqft-spid-R89058182,https://static.99acres.com/universalapp/img/checkLineGray.svg
3,"3 BHK Flatin Raysan, Gandhinagar",3 BHK Flat,"Raysan, Gandhinagar",125.00,"₹5,669 /sqft","2,205 sqft",(205 sqm),Carpet Area,Ready To Move,"We are the proud owners of this 3 bhk apartment available in saral skyline, raysan, gandhinagar. This it is a and the unit is located on 9th floor and has a carpet area of 245 sq.Yards. It has 2 bathroom(s) and 2 balcony(s). The unit is located in a co-Operative society.",https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-raysan-gandhinagar-2205-sqft-spid-R90201698,https://static.99acres.com/universalapp/img/downArrowNew.png
4,"3 BHK Flatin Urjanagar 1, Randesan, Gandhinagar",3 BHK Flat,"Urjanagar 1, Randesan, Gandhinagar",79.00,"₹4,501 /sqft","1,755 sqft",(163 sqm),Carpet Area,Ready To Move,"Situated on the top floor (8th) of a mid-Rise building in divyajivan aura, urjanagar 1, this 5-10 year old 3 bhk flat offers 1755 sqft of well-Laid space with 3 bedrooms and 3 bathrooms. Available immediately, the unfurnished apartment combines comfort with proximity to several religious landmarks in gandhinagar. Ideal for long-Term residence.",https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-divyajivan-aura-urjanagar-1-gandhinagar-1755-sqft-spid-F91063942,https://static.99acres.com/universalapp/img/downArrowNew.png

In [649]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1880 entries, 0 to 1883
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Name                  1880 non-null   object
 1   BHK                   1730 non-null   object
 2   Location              1880 non-null   object
 3   Price (INR in Lakhs)  1880 non-null   float64
 4   Price_per_sqft        1880 non-null   object
 5   Area_sqft             1880 non-null   object
 6   Area_sqm              1880 non-null   object
 7   Area_type             1482 non-null   object
 8   Status                1880 non-null   object
 9   Description           1880 non-null   object
 10  Property_URL          1880 non-null   object
 11  Image_URL             1880 non-null   object
dtypes: float64(1), object(11)
memory usage: 190.9+ KB

In [650]:
df['Price_per_sqft'].value_counts()

Price_per_sqft
₹4,444 /sqft       27
₹5,000 /sqft       20
₹4,000 /sqft       15
₹9,500 /sqft       14
₹5,556 /sqft        9
₹8,333 /sqft        8
₹4,980 /sqft        8
₹5,135 /sqft        8
₹4,501 /sqft        7
₹3,968 /sqft        7
₹3,889 /sqft        7
₹9,000 /sqft        7
₹4,762 /sqft        7
₹4,167 /sqft        7
₹4,535 /sqft        6
₹5,149 /sqft        6
₹4,550 /sqft        6
₹4,284 /sqft        6
₹5,333 /sqft        6
₹4,678 /sqft        6
₹4,794 /sqft        6
₹13,889 /sqft       6
₹3,704 /sqft        6
₹9,444 /sqft        5
₹5,188 /sqft        5
₹6,690 /sqft        5
₹22,569 /sqft       5
₹6,410 /sqft        5
₹4,987 /sqft        5
₹4,453 /sqft        5
₹10,592 /sqft       5
₹3,556 /sqft        5
₹25,702 /sqft       5
₹5,158 /sqft        5
₹36,016 /sqft       5
₹11,607 /sqft       5
₹4,593 /sqft        5
₹5,498 /sqft        5
₹5,291 /sqft        5
₹9,475 /sqft        5
₹9,529 /sqft        5
₹3,876 /sqft        5
₹11,111 /sqft       5
₹4,988 /sqft        5
₹4,040 /sqft        5
₹6,280 /sqft        5
₹4,833 /sqft        5
₹12,401 /sqft       5
₹5,490 /sqft        5
₹6,507 /sqft        5
₹10,000 /sqft       5
₹3,703 /sqft        5
₹6,849 /sqft        5
₹4,630 /sqft        5
₹4,712 /sqft        5
₹7,435 /sqft        4
₹4,775 /sqft        4
₹44,217 /sqft       4
₹9,732 /sqft        4
₹15,556 /sqft       4
₹6,266 /sqft        4
₹9,789 /sqft        4
₹3,939 /sqft        4
₹5,510 /sqft        4
₹10,091 /sqft       4
₹4,197 /sqft        4
₹4,728 /sqft        4
₹4,646 /sqft        4
₹4,301 /sqft        4
₹6,250 /sqft        4
₹7,143 /sqft        4
₹3,846 /sqft        4
₹21,605 /sqft       4
₹4,682 /sqft        4
₹13,488 /sqft       4
₹4,607 /sqft        4
₹6,989 /sqft        4
₹4,720 /sqft        4
₹4,480 /sqft        4
₹4,975 /sqft        4
₹4,830 /sqft        4
₹4,331 /sqft        4
₹4,848 /sqft        4
₹5,168 /sqft        4
₹4,263 /sqft        4
₹11,667 /sqft       3
₹4,471 /sqft        3
₹4,722 /sqft        3
₹4,831 /sqft        3
₹4,822 /sqft        3
₹5,128 /sqft        3
₹4,579 /sqft        3
₹5,555 /sqft        3
₹4,338 /sqft        3
₹9,259 /sqft        3
₹4,889 /sqft        3
₹4,609 /sqft        3
₹4,913 /sqft        3
₹22,222 /sqft       3
₹11,000 /sqft       3
₹4,575 /sqft        3
₹4,394 /sqft        3
₹3,611 /sqft        3
₹5,889 /sqft        3
₹4,286 /sqft        3
₹5,122 /sqft        3
₹3,111 /sqft        3
₹3,925 /sqft        3
₹6,000 /sqft        3
₹4,166 /sqft        3
₹4,701 /sqft        3
₹2,222 /sqft        3
₹4,750 /sqft        3
₹8,500 /sqft        3
₹3,333 /sqft        3
₹4,428 /sqft        3
₹2,500 /sqft        3
₹7,569 /sqft        3
₹40,000 /sqft       3
₹7,000 /sqft        3
₹20,000 /sqft       3
₹4,074 /sqft        3
₹6,667 /sqft        3
₹3,961 /sqft        3
₹5,051 /sqft        3
₹4,549 /sqft        3
₹7,653 /sqft        3
₹567 /sqft          3
₹12,500 /sqft       3
₹5,086 /sqft        3
₹17,822 /sqft       3
₹7,648 /sqft        3
₹4,198 /sqft        2
₹2,962 /sqft        2
₹5,083 /sqft        2
₹6,481 /sqft        2
₹4,228 /sqft        2
₹5,669 /sqft        2
₹3,955 /sqft        2
₹3,943 /sqft        2
₹4,184 /sqft        2
₹2,907 /sqft        2
₹4,789 /sqft        2
₹2,871 /sqft        2
₹3,389 /sqft        2
₹3,541 /sqft        2
₹4,819 /sqft        2
₹4,111 /sqft        2
₹7,778 /sqft        2
₹4,556 /sqft        2
₹8,724 /sqft        2
₹1,36,363 /sqft     2
₹5,430 /sqft        2
₹4,603 /sqft        2
₹1,469 /sqft        2
₹37,037 /sqft       2
₹17,958 /sqft       2
₹4,512 /sqft        2
₹4,460 /sqft        2
₹3,851 /sqft        2
₹4,551 /sqft        2
₹4,618 /sqft        2
₹6,715 /sqft        2
₹4,115 /sqft        2
₹3,535 /sqft        2
₹4,026 /sqft        2
₹4,878 /sqft        2
₹5,658 /sqft        2
₹8,000 /sqft        2
₹3,840 /sqft        2
₹4,393 /sqft        2
₹3,779 /sqft        2
₹5,272 /sqft        2
₹4,644 /sqft        2
₹4,739 /sqft        2
₹16,667 /sqft       2
₹18,000 /sqft       2
₹4,208 /sqft        2
₹6,995 /sqft        2
₹10,866 /sqft       2
₹5,089 /sqft        2
₹4,340 /sqft        2
₹4,173 /sqft        2
₹8,085 /sqft        2
₹7,756 /sqft        2
₹4,365 /sqft        2
₹4,796 /sqft        2
₹4,745 /sqft        2
₹5,050 /sqft        2
₹40,909 /sqft       2
₹9,200 /sqft        2
₹5,095 /sqft        2
₹4,629 /sqft        2
₹3,722 /sqft        2
₹4,948 /sqft        2
₹4,924 /sqft        2
₹23,809 /sqft       2
₹6,424 /sqft        2
₹4,344 /sqft        2
₹4,624 /sqft        2
₹4,516 /sqft        2
₹8,889 /sqft        2
₹4,774 /sqft        2
₹3,759 /sqft        2
₹5,058 /sqft        2
₹3,950 /sqft        2
₹4,209 /sqft        2
₹4,332 /sqft        2
₹4,366 /sqft        2
₹3,590 /sqft        2
₹4,555 /sqft        2
₹4,409 /sqft        2
₹3,888 /sqft        2
₹3,778 /sqft        2
₹4,056 /sqft        2
₹7,444 /sqft        2
₹4,545 /sqft        2
₹5,159 /sqft        2
₹9,154 /sqft        2
₹6,349 /sqft        2
₹15,484 /sqft       2
₹4,979 /sqft        2
₹3,912 /sqft        2
₹6,444 /sqft        2
₹6,455 /sqft        2
₹955 /sqft          2
₹3,200 /sqft        2
₹5,516 /sqft        2
₹3,794 /sqft        2
₹3,533 /sqft        2
₹8,808 /sqft        2
₹889 /sqft          2
₹2,778 /sqft        2
₹4,315 /sqft        2
₹4,612 /sqft        2
₹6,670 /sqft        2
₹11,872 /sqft       2
₹4,837 /sqft        2
₹8,295 /sqft        2
₹3,472 /sqft        2
₹3,810 /sqft        2
₹26,539 /sqft       2
₹3,492 /sqft        2
₹7,273 /sqft        2
₹22,153 /sqft       2
₹5,760 /sqft        2
₹4,233 /sqft        2
₹97,508 /sqft       2
₹50,000 /sqft       2
₹3,818 /sqft        2
₹9,220 /sqft        2
₹4,688 /sqft        2
₹5,041 /sqft        2
₹68,292 /sqft       2
₹4,525 /sqft        2
₹9,803 /sqft        2
₹5,185 /sqft        2
₹29,032 /sqft       2
₹20,082 /sqft       2
₹38,356 /sqft       2
₹4,278 /sqft        2
₹4,149 /sqft        2
₹5,286 /sqft        2
₹19,608 /sqft       2
₹7,500 /sqft        2
₹8,444 /sqft        2
₹9,473 /sqft        1
₹6,326 /sqft        1
₹3,446 /sqft        1
₹1,202 /sqft        1
₹523 /sqft          1
₹6,501 /sqft        1
₹23,569 /sqft       1
₹3,917 /sqft        1
₹18,258 /sqft       1
₹19,596 /sqft       1
₹13,427 /sqft       1
₹5,997 /sqft        1
₹9,596 /sqft        1
₹16,120 /sqft       1
₹6,039 /sqft        1
₹8,470 /sqft        1
₹25,347 /sqft       1
₹3,865 /sqft        1
₹14,253 /sqft       1
₹4,432 /sqft        1
₹10,244 /sqft       1
₹9,249 /sqft        1
₹4,689 /sqft        1
₹4,761 /sqft        1
₹4,327 /sqft        1
₹4,243 /sqft        1
₹3,935 /sqft        1
₹32,500 /sqft       1
₹6,420 /sqft        1
₹9,838 /sqft        1
₹1,839 /sqft        1
₹4,866 /sqft        1
₹7,432 /sqft        1
₹9,546 /sqft        1
₹9,993 /sqft        1
₹2,994 /sqft        1
₹6,209 /sqft        1
₹1,00,000 /sqft     1
₹1,12,500 /sqft     1
₹1,286 /sqft        1
₹13,605 /sqft       1
₹3,655 /sqft        1
₹9,066 /sqft        1
₹4,523 /sqft        1
₹4,736 /sqft        1
₹4,814 /sqft        1
₹7,833 /sqft        1
₹12,439 /sqft       1
₹47,500 /sqft       1
₹5,632 /sqft        1
₹15,707 /sqft       1
₹1,77,777 /sqft     1
₹5,411 /sqft        1
₹17,265 /sqft       1
₹1,798 /sqft        1
₹60 /sqft           1
₹19,886 /sqft       1
₹4,743 /sqft        1
₹8,353 /sqft        1
₹8,232 /sqft        1
₹37 /sqft           1
₹20,500 /sqft       1
₹9,587 /sqft        1
₹4,321 /sqft        1
₹13,387 /sqft       1
₹4,276 /sqft        1
₹8,967 /sqft        1
₹6,536 /sqft        1
₹11,231 /sqft       1
₹5,492 /sqft        1
₹4,285 /sqft        1
₹7,850 /sqft        1
₹21,949 /sqft       1
₹12,505 /sqft       1
₹28,500 /sqft       1
₹5,304 /sqft        1
₹39,160 /sqft       1
₹7,527 /sqft        1
₹3,285 /sqft        1
₹4,847 /sqft        1
₹8,985 /sqft        1
₹5,861 /sqft        1
₹5,454 /sqft        1
₹18,943 /sqft       1
₹4,910 /sqft        1
₹4,930 /sqft        1
₹10,666 /sqft       1
₹2,380 /sqft        1
₹3,855 /sqft        1
₹4,427 /sqft        1
₹4,504 /sqft        1
₹4,651 /sqft        1
₹3,030 /sqft        1
₹5,113 /sqft        1
₹22,710 /sqft       1
₹4,768 /sqft        1
₹11,860 /sqft       1
₹9,298 /sqft        1
₹7,909 /sqft        1
₹3,747 /sqft        1
₹5,657 /sqft        1
₹15,326 /sqft       1
₹8,947 /sqft        1
₹4,185 /sqft        1
₹8,603 /sqft        1
₹10,824 /sqft       1
₹3,221 /sqft        1
₹6,666 /sqft        1
₹3,890 /sqft        1
₹3,185 /sqft        1
₹4,489 /sqft        1
₹3,963 /sqft        1
₹9,398 /sqft        1
₹6,011 /sqft        1
₹4,803 /sqft        1
₹33,112 /sqft       1
₹4,601 /sqft        1
₹4,357 /sqft        1
₹55,362 /sqft       1
₹4,408 /sqft        1
₹6,899 /sqft        1
₹10,483 /sqft       1
₹14,292 /sqft       1
₹4,193 /sqft        1
₹8,818 /sqft        1
₹5,461 /sqft        1
₹4,188 /sqft        1
₹4,118 /sqft        1
₹4,237 /sqft        1
₹20,793 /sqft       1
₹14,577 /sqft       1
₹6,115 /sqft        1
₹2,099 /sqft        1
₹10,180 /sqft       1
₹23,589 /sqft       1
₹37,500 /sqft       1
₹5,923 /sqft        1
₹5,042 /sqft        1
₹6,050 /sqft        1
₹3,829 /sqft        1
₹7,052 /sqft        1
₹7,840 /sqft        1
₹12,545 /sqft       1
₹9,770 /sqft        1
₹19,294 /sqft       1
₹3,110 /sqft        1
₹21,013 /sqft       1
₹11,926 /sqft       1
₹16,147 /sqft       1
₹24,603 /sqft       1
₹1,11,587 /sqft     1
₹2,809 /sqft        1
₹16,731 /sqft       1
₹11,696 /sqft       1
₹4,382 /sqft        1
₹4,583 /sqft        1
₹5,194 /sqft        1
₹2,011 /sqft        1
₹11,450 /sqft       1
₹18,056 /sqft       1
₹5,180 /sqft        1
₹5,245 /sqft        1
₹26,745 /sqft       1
₹4,141 /sqft        1
₹3,076 /sqft        1
₹13,227 /sqft       1
₹9,417 /sqft        1
₹8,969 /sqft        1
₹4,873 /sqft        1
₹4,520 /sqft        1
₹4,747 /sqft        1
₹6,329 /sqft        1
₹4,271 /sqft        1
₹4,318 /sqft        1
₹5,203 /sqft        1
₹4,685 /sqft        1
₹4,369 /sqft        1
₹3,885 /sqft        1
₹8,924 /sqft        1
₹10,556 /sqft       1
₹5,284 /sqft        1
₹3,838 /sqft        1
₹6,310 /sqft        1
₹4,731 /sqft        1
₹5,431 /sqft        1
₹6,996 /sqft        1
₹6,567 /sqft        1
₹6,488 /sqft        1
₹6,220 /sqft        1
₹9,341 /sqft        1
₹5,356 /sqft        1
₹56,122 /sqft       1
₹4,377 /sqft        1
₹4,710 /sqft        1
₹5,754 /sqft        1
₹7,971 /sqft        1
₹12,569 /sqft       1
₹8,915 /sqft        1
₹11,852 /sqft       1
₹4,598 /sqft        1
₹3,761 /sqft        1
₹4,990 /sqft        1
₹4,801 /sqft        1
₹5,153 /sqft        1
₹5,428 /sqft        1
₹5,846 /sqft        1
₹4,667 /sqft        1
₹7,673 /sqft        1
₹5,020 /sqft        1
₹647 /sqft          1
₹490 /sqft          1
₹4,246 /sqft        1
₹5,747 /sqft        1
₹5,925 /sqft        1
₹5,910 /sqft        1
₹4,135 /sqft        1
₹8,067 /sqft        1
₹12,694 /sqft       1
₹6,018 /sqft        1
₹15,823 /sqft       1
₹4,227 /sqft        1
₹4,431 /sqft        1
₹4,528 /sqft        1
₹1,28,755 /sqft     1
₹4,435 /sqft        1
₹11,217 /sqft       1
₹4,853 /sqft        1
₹1,55,555 /sqft     1
₹10,942 /sqft       1
₹6,878 /sqft        1
₹15,217 /sqft       1
₹6,394 /sqft        1
₹5,090 /sqft        1
₹17,544 /sqft       1
₹4,446 /sqft        1
₹4,726 /sqft        1
₹4,018 /sqft        1
₹3,134 /sqft        1
₹4,493 /sqft        1
₹50,980 /sqft       1
₹6,385 /sqft        1
₹8,138 /sqft        1
₹5,061 /sqft        1
₹4,485 /sqft        1
₹8,407 /sqft        1
₹7,175 /sqft        1
₹4,572 /sqft        1
₹6,723 /sqft        1
₹5,054 /sqft        1
₹9,691 /sqft        1
₹4,938 /sqft        1
₹4,383 /sqft        1
₹6,463 /sqft        1
₹4,138 /sqft        1
₹9,207 /sqft        1
₹4,268 /sqft        1
₹20,047 /sqft       1
₹10,068 /sqft       1
₹7,407 /sqft        1
₹8,487 /sqft        1
₹3,623 /sqft        1
₹5,823 /sqft        1
₹8,823 /sqft        1
₹5,289 /sqft        1
₹3,918 /sqft        1
₹3,628 /sqft        1
₹3,922 /sqft        1
₹4,019 /sqft        1
₹4,051 /sqft        1
₹3,908 /sqft        1
₹4,084 /sqft        1
₹8,356 /sqft        1
₹4,420 /sqft        1
₹5,752 /sqft        1
₹23,504 /sqft       1
₹3,793 /sqft        1
₹4,047 /sqft        1
₹3,774 /sqft        1
₹4,777 /sqft        1
₹4,666 /sqft        1
₹9,493 /sqft        1
₹24,086 /sqft       1
₹4,061 /sqft        1
₹5,197 /sqft        1
₹41,000 /sqft       1
₹14,269 /sqft       1
₹13,561 /sqft       1
₹13,182 /sqft       1
₹12,639 /sqft       1
₹3,989 /sqft        1
₹4,511 /sqft        1
₹4,222 /sqft        1
₹7,065 /sqft        1
₹5,093 /sqft        1
₹10,816 /sqft       1
₹9,590 /sqft        1
₹5,701 /sqft        1
₹3,222 /sqft        1
₹13,158 /sqft       1
₹5,029 /sqft        1
₹3,899 /sqft        1
₹4,270 /sqft        1
₹5,362 /sqft        1
₹4,981 /sqft        1
₹1,56,462 /sqft     1
₹3,892 /sqft        1
₹4,746 /sqft        1
₹3,575 /sqft        1
₹4,336 /sqft        1
₹9,645 /sqft        1
₹4,605 /sqft        1
₹6,807 /sqft        1
₹4,479 /sqft        1
₹17,007 /sqft       1
₹8,421 /sqft        1
₹3,516 /sqft        1
₹9,894 /sqft        1
₹4,496 /sqft        1
₹4,665 /sqft        1
₹4,143 /sqft        1
₹4,186 /sqft        1
₹5,085 /sqft        1
₹4,470 /sqft        1
₹9,656 /sqft        1
₹4,716 /sqft        1
₹5,983 /sqft        1
₹5,348 /sqft        1
₹4,943 /sqft        1
₹6,882 /sqft        1
₹7,325 /sqft        1
₹8,044 /sqft        1
₹12,799 /sqft       1
₹7,477 /sqft        1
₹7,017 /sqft        1
₹4,539 /sqft        1
₹19,580 /sqft       1
₹3,384 /sqft        1
₹6,828 /sqft        1
₹11,574 /sqft       1
₹2,881 /sqft        1
₹7,907 /sqft        1
₹5,602 /sqft        1
₹11,828 /sqft       1
₹5,353 /sqft        1
₹13,156 /sqft       1
₹14,256 /sqft       1
₹13,626 /sqft       1
₹13,784 /sqft       1
₹13,151 /sqft       1
₹13,361 /sqft       1
₹11,578 /sqft       1
₹10,500 /sqft       1
₹10,977 /sqft       1
₹10,555 /sqft       1
₹10,645 /sqft       1
₹13,322 /sqft       1
₹4,861 /sqft        1
₹8,778 /sqft        1
₹6,968 /sqft        1
₹3,115 /sqft        1
₹4,782 /sqft        1
₹5,023 /sqft        1
₹19,613 /sqft       1
₹7,369 /sqft        1
₹4,320 /sqft        1
₹4,730 /sqft        1
₹4,148 /sqft        1
₹4,139 /sqft        1
₹23,140 /sqft       1
₹4,989 /sqft        1
₹5,606 /sqft        1
₹3,980 /sqft        1
₹5,028 /sqft        1
₹4,622 /sqft        1
₹4,918 /sqft        1
₹8,892 /sqft        1
₹7,716 /sqft        1
₹4,245 /sqft        1
₹10,033 /sqft       1
₹31,849 /sqft       1
₹11,127 /sqft       1
₹3,666 /sqft        1
₹2,444 /sqft        1
₹8,230 /sqft        1
₹9,107 /sqft        1
₹10,667 /sqft       1
₹3,903 /sqft        1
₹30,968 /sqft       1
₹18,096 /sqft       1
₹4,531 /sqft        1
₹10,720 /sqft       1
₹13,550 /sqft       1
₹6,857 /sqft        1
₹4,125 /sqft        1
₹3,065 /sqft        1
₹21,739 /sqft       1
₹9,462 /sqft        1
₹15,789 /sqft       1
₹63,157 /sqft       1
₹11,645 /sqft       1
₹14,583 /sqft       1
₹3,805 /sqft        1
₹3,086 /sqft        1
₹4,881 /sqft        1
₹8,430 /sqft        1
₹4,597 /sqft        1
₹3,913 /sqft        1
₹3,852 /sqft        1
₹3,240 /sqft        1
₹11,057 /sqft       1
₹7,545 /sqft        1
₹6,331 /sqft        1
₹50,207 /sqft       1
₹5,733 /sqft        1
₹8,250 /sqft        1
₹6,944 /sqft        1
₹13,744 /sqft       1
₹13,409 /sqft       1
₹3,439 /sqft        1
₹10,206 /sqft       1
₹3,767 /sqft        1
₹11,843 /sqft       1
₹3,817 /sqft        1
₹3,675 /sqft        1
₹3,434 /sqft        1
₹55,118 /sqft       1
₹5,620 /sqft        1
₹8,293 /sqft        1
₹4,573 /sqft        1
₹10,101 /sqft       1
₹4,239 /sqft        1
₹4,514 /sqft        1
₹3,985 /sqft        1
₹16,606 /sqft       1
₹14,019 /sqft       1
₹4,205 /sqft        1
₹5,805 /sqft        1
₹4,502 /sqft        1
₹3,974 /sqft        1
₹3,962 /sqft        1
₹9,321 /sqft        1
₹4,457 /sqft        1
₹8,474 /sqft        1
₹2,391 /sqft        1
₹3,312 /sqft        1
₹6,006 /sqft        1
₹17,460 /sqft       1
₹3,165 /sqft        1
₹8,471 /sqft        1
₹19,536 /sqft       1
₹7,424 /sqft        1
₹5,842 /sqft        1
₹11,109 /sqft       1
₹12,267 /sqft       1
₹13,065 /sqft       1
₹8,666 /sqft        1
₹5,666 /sqft        1
₹4,267 /sqft        1
₹19,841 /sqft       1
₹604 /sqft          1
₹5,380 /sqft        1
₹8,888 /sqft        1
₹11,066 /sqft       1
₹4,159 /sqft        1
₹13,333 /sqft       1
₹4,404 /sqft        1
₹4,491 /sqft        1
₹3,831 /sqft        1
₹5,223 /sqft        1
₹3,363 /sqft        1
₹7,386 /sqft        1
₹3,387 /sqft        1
₹5,608 /sqft        1
₹4,337 /sqft        1
₹6,321 /sqft        1
₹3,870 /sqft        1
₹10,776 /sqft       1
₹3,809 /sqft        1
₹3,595 /sqft        1
₹1,667 /sqft        1
₹7,246 /sqft        1
₹9,016 /sqft        1
₹4,474 /sqft        1
₹15,471 /sqft       1
₹4,464 /sqft        1
₹4,069 /sqft        1
₹1,23,456 /sqft     1
₹3,685 /sqft        1
₹8,521 /sqft        1
₹6,061 /sqft        1
₹12,188 /sqft       1
₹3,248 /sqft        1
₹6,093 /sqft        1
₹8,125 /sqft        1
₹11,227 /sqft       1
₹4,846 /sqft        1
₹14,815 /sqft       1
₹3,661 /sqft        1
₹4,215 /sqft        1
₹4,901 /sqft        1
₹4,584 /sqft        1
₹18,074 /sqft       1
₹5,270 /sqft        1
₹3,589 /sqft        1
₹2,113 /sqft        1
₹8,009 /sqft        1
₹20,962 /sqft       1
₹26,086 /sqft       1
₹23,333 /sqft       1
₹5,468 /sqft        1
₹2,22,222 /sqft     1
₹8,173 /sqft        1
₹4,200 /sqft        1
₹3,199 /sqft        1
₹10,944 /sqft       1
₹15,949 /sqft       1
₹5,682 /sqft        1
₹3,618 /sqft        1
₹3,787 /sqft        1
₹64,815 /sqft       1
₹4,623 /sqft        1
₹135 /sqft          1
₹4,207 /sqft        1
₹20,982 /sqft       1
₹6,296 /sqft        1
₹5,368 /sqft        1
₹14,000 /sqft       1
₹2,634 /sqft        1
₹4,079 /sqft        1
₹7,058 /sqft        1
₹8,227 /sqft        1
₹5,847 /sqft        1
₹5,076 /sqft        1
₹4,434 /sqft        1
₹14,337 /sqft       1
₹5,877 /sqft        1
₹6,761 /sqft        1
₹4,902 /sqft        1
₹3,670 /sqft        1
₹3,442 /sqft        1
₹2,666 /sqft        1
₹8,680 /sqft        1
₹10,709 /sqft       1
₹3,896 /sqft        1
₹45,454 /sqft       1
₹1,049 /sqft        1
₹3,833 /sqft        1
₹6 /sqft            1
₹7,373 /sqft        1
₹3,994 /sqft        1
₹3,750 /sqft        1
₹7,975 /sqft        1
₹13,571 /sqft       1
₹3,933 /sqft        1
₹17,896 /sqft       1
₹4,220 /sqft        1
₹4,16,666 /sqft     1
₹41,860 /sqft       1
₹6,053 /sqft        1
₹6,077 /sqft        1
₹11,905 /sqft       1
₹3,871 /sqft        1
₹4,389 /sqft        1
₹1,040 /sqft        1
₹7,222 /sqft        1
₹7,727 /sqft        1
₹3,268 /sqft        1
₹6,419 /sqft        1
₹4,361 /sqft        1
₹5,480 /sqft        1
₹6,956 /sqft        1
₹75,085 /sqft       1
₹18,581 /sqft       1
₹3,716 /sqft        1
₹10,502 /sqft       1
₹44,585 /sqft       1
₹2,936 /sqft        1
₹3,016 /sqft        1
₹4,083 /sqft        1
₹3,166 /sqft        1
₹4,341 /sqft        1
₹2,428 /sqft        1
₹1,07,594 /sqft     1
₹4,201 /sqft        1
₹8,094 /sqft        1
₹12,075 /sqft       1
₹22,774 /sqft       1
₹15,833 /sqft       1
₹8,154 /sqft        1
₹3,289 /sqft        1
₹4,153 /sqft        1
₹7,551 /sqft        1
₹4,518 /sqft        1
₹3,031 /sqft        1
₹7,447 /sqft        1
₹4,793 /sqft        1
₹23,845 /sqft       1
₹3,906 /sqft        1
₹8,450 /sqft        1
₹42,948 /sqft       1
₹2,677 /sqft        1
₹4,020 /sqft        1
₹3,900 /sqft        1
₹3,932 /sqft        1
₹13,580 /sqft       1
₹5,714 /sqft        1
₹8,642 /sqft        1
₹10,885 /sqft       1
₹8,571 /sqft        1
₹178 /sqft          1
₹25 /sqft           1
₹21,788 /sqft       1
₹3,388 /sqft        1
₹9,320 /sqft        1
₹4,323 /sqft        1
₹877 /sqft          1
₹7,967 /sqft        1
₹5,783 /sqft        1
₹49,387 /sqft       1
₹5,933 /sqft        1
₹5,662 /sqft        1
₹7,200 /sqft        1
₹8,676 /sqft        1
₹5,385 /sqft        1
₹16,507 /sqft       1
₹4,672 /sqft        1
₹9,853 /sqft        1
₹83,798 /sqft       1
₹7,308 /sqft        1
₹5,232 /sqft        1
₹3,625 /sqft        1
₹9,285 /sqft        1
₹4,595 /sqft        1
₹4,705 /sqft        1
₹2,064 /sqft        1
₹3,386 /sqft        1
₹7,811 /sqft        1
₹1,388 /sqft        1
₹3,555 /sqft        1
₹34,444 /sqft       1
₹6,076 /sqft        1
₹8,360 /sqft        1

In [651]:
# Remove ₹ symbol, commas, and /sqft text in Price_per_sqft column

df["Price_per_sqft"] = (
    df["Price_per_sqft"]
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.replace("/sqft", "", regex=False)
    .str.strip()
)

# Then convert values into float datatype
df["Price_per_sqft"] = pd.to_numeric(df["Price_per_sqft"], errors="coerce")

In [652]:
df[df["Price_per_sqft"].isna()]

,Name,BHK,Location,Price (INR in Lakhs),Price_per_sqft,Area_sqft,Area_sqm,Area_type,Status,Description,Property_URL,Image_URL
1446,"Residential land / Plotin Vavol, Gandhinagar",NaN,"Vavol, Gandhinagar",60.0,NaN,0.06 sqft,(0 sqm),NaN,Ready To Move,"We have a land available for sale in mahudi, gandhinagar. Available at price of rs 60 lacs. It has plot area of 0.05785124 sq ft. It is a power of attorney property",https://www.99acres.com/residential-land-plot-for-sale-in-kirtidham-society-vavol-gandhinagar-0-sqyd-spid-Q89204781,https://static.99acres.com/universalapp/img/downArrowNew.png
1455,"4 Bedroom Housein Sector 30, Gandhinagar",4 BHK,"Sector 30, Gandhinagar",260.0,NaN,225 sqft,(21 sqm),NaN,Ready To Move,"Available now, this 5-10 year old independent 4 bhk villa in sector 30, gandhinagar offers 225 sq.Ft. Of well-Planned living with 4 bedrooms and 6 bathrooms across multiple floors. The semi-Furnished home benefits from proximity to swaminarayan akshardham temple and key hospitals, blending comfort with convenience.",https://www.99acres.com/4-bhk-bedroom-independent-house-villa-for-sale-in-sector-30-gandhinagar-225-sqft-spid-Z89150001,https://static.99acres.com/universalapp/img/downArrowNew.png
1530,"3 Bedroom Housein PLOT NO-1398/1,SECTOR NO-2/B,GANDHINAGAR",3 BHK,"PLOT NO-1398/1,SECTOR NO-2/B,GANDHINAGAR",250.0,NaN,90 sqft,(8 sqm),NaN,Ready To Move,"This 3 bhk house for sale in plot no-1398/1,sector no-2/b,gandhinagar, a well planned locality in gandhinagar, is ideal for a family that is looking for complete peace of mind. Constructed on a super built up area of 90 sq.Ft., this house comprises 3 bedrooms, 2 bathrooms and 2 balconies. This 10+ years old property is available for immediate possession as the house is ready to move. It is a po...",https://www.99acres.com/3-bhk-bedroom-independent-house-villa-for-sale-in-gandhinagar-90-sqft-r1-spid-Z88535590,https://static.99acres.com/universalapp/img/downArrowNew.png
1696,"2 Bedroom Housein Sector 21, Gandhinagar",2 BHK,"Sector 21, Gandhinagar",400.0,NaN,330 sqft,(31 sqm),NaN,Ready To Move,"Dear, Key will be available, but before that please go in detail in blog Please send your name, mobile no. And address Our representative will be there to show you the house Society is old and construction is old 1990 In milkat card it is in the name of rajeshwari Contact: 79901 27912 Name: Rajesh zala",https://www.99acres.com/2-bhk-bedroom-independent-house-villa-for-sale-in-sector-21-gandhinagar-330-sqft-spid-R87385582,https://static.99acres.com/universalapp/img/downArrowNew.png
1704,"Residential land / Plotin Vayana, Kalol, Gandhinagar",NaN,"Vayana, Kalol, Gandhinagar",500.0,NaN,26.58 sqft,(2 sqm),NaN,Ready To Move,Best for investment purpose. Best for construction site. Best for ploting.,https://www.99acres.com/residential-land-plot-for-sale-in-vayana-gandhinagar-3-sqyd-spid-A87270698,https://static.99acres.com/universalapp/img/downArrowNew.png
1775,5 Bedroom Housein Sector 7 Gandhinagar,5 BHK,Sector 7 Gandhinagar,170.0,NaN,45 sqft,(4 sqm),NaN,Ready To Move,School college market bus station hospital park gym cinema mall sector7c,https://www.99acres.com/5-bhk-bedroom-independent-house-villa-for-sale-in-sector-7-gandhinagar-45-sqft-spid-U86431420,https://static.99acres.com/universalapp/img/downArrowNew.png

In [653]:
df['Area_sqft'].value_counts()

Area_sqft
1,845 sqft                                                                                                                                                                                                                                                                                                                                                                                                          34
1,260 sqft                                                                                                                                                                                                                                                                                                                                                                                                          25
1,800 sqft                                                                                                                                                                                                                                                                                                                                                                                                          21
1,305 sqft                                                                                                                                                                                                                                                                                                                                                                                                          21
2,250 sqft                                                                                                                                                                                                                                                                                                                                                                                                          19
1,215 sqft                                                                                                                                                                                                                                                                                                                                                                                                          15
1,125 sqft                                                                                                                                                                                                                                                                                                                                                                                                          15
2,475 sqft                                                                                                                                                                                                                                                                                                                                                                                                          14
1,485 sqft                                                                                                                                                                                                                                                                                                                                                                                                          14
2,142 sqft                                                                                                                                                                                                                                                                                                                                                                                                          14
1,278 sqft                                                                                                                                                                                                                                                                                                                                                                                                          14
2,025 sqft                                                                                                                                                                                                                                                                                                                                                                                                          14
1,000 sqft                                                                                                                                                                                                                                                                                                                                                                                                          13
1,395 sqft                                                                                                                                                                                                                                                                                                                                                                                                          13
1,170 sqft                                                                                                                                                                                                                                                                                                                                                                                                          13
1,350 sqft                                                                                                                                                                                                                                                                                                                                                                                                          13
2,520 sqft                                                                                                                                                                                                                                                                                                                                                                                                          13
2,880 sqft                                                                                                                                                                                                                                                                                                                                                                                                          12
1,200 sqft                                                                                                                                                                                                                                                                                                                                                                                                          12
1,890 sqft                                                                                                                                                                                                                                                                                                                                                                                                          12
1,710 sqft                                                                                                                                                                                                                                                                                                                                                                                                          12
1,377 sqft                                                                                                                                                                                                                                                                                                                                                                                                          12
1,620 sqft                                                                                                                                                                                                                                                                                                                                                                                                          11
1,323 sqft                                                                                                                                                                                                                                                                                                                                                                                                          11
900 sqft                                                                                                                                                                                                                                                                                                                                                                                                            11
1,755 sqft                                                                                                                                                                                                                                                                                                                                                                                                          11
2,637 sqft                                                                                                                                                                                                                                                                                                                                                                                                          11
2,160 sqft                                                                                                                                                                                                                                                                                                                                                                                                          11
2,070 sqft                                                                                                                                                                                                                                                                                                                                                                                                          10
990 sqft                                                                                                                                                                                                                                                                                                                                                                                                            10
1,935 sqft                                                                                                                                                                                                                                                                                                                                                                                                          10
1,773 sqft                                                                                                                                                                                                                                                                                                                                                                                                          10
1,089 sqft                                                                                                                                                                                                                                                                                                                                                                                                          10
1,980 sqft                                                                                                                                                                                                                                                                                                                                                                                                          10
1,080 sqft                                                                                                                                                                                                                                                                                                                                                                                                          10
1,511 sqft                                                                                                                                                                                                                                                                                                                                                                                                          10
1,791 sqft                                                                                                                                                                                                                                                                                                                                                                                                           8
1,449 sqft                                                                                                                                                                                                                                                                                                                                                                                                           8
1,269 sqft                                                                                                                                                                                                                                                                                                                                                                                                           8
1,179 sqft                                                                                                                                                                                                                                                                                                                                                                                                           8
600 sqft                                                                                                                                                                                                                                                                                                                                                                                                             8
2,313 sqft                                                                                                                                                                                                                                                                                                                                                                                                           8
1,440 sqft                                                                                                                                                                                                                                                                                                                                                                                                           8
1,683 sqft                                                                                                                                                                                                                                                                                                                                                                                                           8
1,242 sqft                                                                                                                                                                                                                                                                                                                                                                                                           8
1,197 sqft                                                                                                                                                                                                                                                                                                                                                                                                           8
1,728 sqft                                                                                                                                                                                                                                                                                                                                                                                                           7
2,205 sqft                                                                                                                                                                                                                                                                                                                                                                                                           7
972 sqft                                                                                                                                                                                                                                                                                                                                                                                                             7

In [654]:
# Find rows where Area_sqft is NOT in proper 'number sqft' format

df[~df["Area_sqft"].str.match(r"^\d[\d,]*\.?\d*\s*sqft$", case=False, na=False)]

,Name,BHK,Location,Price (INR in Lakhs),Price_per_sqft,Area_sqft,Area_sqm,Area_type,Status,Description,Property_URL,Image_URL
15,"4 BHK Flatin Koba, Gandhinagar",4 BHK Flat,"Koba, Gandhinagar",165.00,4263.0,"Property for sell: Luxurious 4 bhk apartment Location: Skyra, 12th floor, opp - Gnlu metro station, koba, gandhinagar Size: 3870 sqft Features: - The appartments are situated at a strategic & convinient location of 2 road corner on 80 metre wide road just opposite gnlu metro station. - 4 spacious bedrooms & modern washrooms - Living rooms with a beautiful courtyard balcony - Fully vastu-Complia...",(360 sqm),Super Built-up Area,Ready To Move,,https://www.99acres.com/4-bhk-bedroom-apartment-flat-for-sale-in-maruti-skyra-koba-gandhinagar-3870-sqft-spid-T88688802,https://static.99acres.com/universalapp/img/checkLineGray.svg
85,"4 BHK Flatin Koba, Gandhinagar",4 BHK Flat,"Koba, Gandhinagar",165.00,4263.0,"Property for sell: Luxurious 4 bhk apartment Location: Skyra, 12th floor, opp - Gnlu metro station, koba, gandhinagar Size: 3870 sqft Features: - The appartments are situated at a strategic & convinient location of 2 road corner on 80 metre wide road just opposite gnlu metro station. - 4 spacious bedrooms & modern washrooms - Living rooms with a beautiful courtyard balcony - Fully vastu-Complia...",(360 sqm),Super Built-up Area,Ready To Move,,https://www.99acres.com/4-bhk-bedroom-apartment-flat-for-sale-in-maruti-skyra-koba-gandhinagar-3870-sqft-spid-T88688802,https://static.99acres.com/universalapp/img/checkLineGray.svg
143,"4 BHK Flatin Koba, Gandhinagar",4 BHK Flat,"Koba, Gandhinagar",165.00,4263.0,"Property for sell: Luxurious 4 bhk apartment Location: Skyra, 12th floor, opp - Gnlu metro station, koba, gandhinagar Size: 3870 sqft Features: - The appartments are situated at a strategic & convinient location of 2 road corner on 80 metre wide road just opposite gnlu metro station. - 4 spacious bedrooms & modern washrooms - Living rooms with a beautiful courtyard balcony - Fully vastu-Complia...",(360 sqm),Super Built-up Area,Ready To Move,,https://www.99acres.com/4-bhk-bedroom-apartment-flat-for-sale-in-maruti-skyra-koba-gandhinagar-3870-sqft-spid-T88688802,https://static.99acres.com/universalapp/img/checkLineGray.svg
314,"3 BHK Flatin Koba, Gandhinagar",3 BHK Flat,"Koba, Gandhinagar",124.00,4332.0,"Sun spacelink is a premium residential project located in koba, gandhinagar, gujarat. The project is spread across 0.88 acres and consists of 90 units housed in 2 towers. Each unit offers configurations ranging from 3 bhk+3t to 3 bhk+3t, with sizes starting from 1255 sqft to 1327 sqft. The project is designed to provide a blend of comfort and style, featuring amenities such as a club house, chi...",(266 sqm),Super Built-up Area,Ready To Move,,https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-sun-spacelink-koba-gandhinagar-2862-sqft-r1-spid-O88630232,https://static.99acres.com/universalapp/img/checkLineGray.svg
322,"3 BHK Builder Floorin Koba, Gandhinagar",3 BHK Builder Floor,"Koba, Gandhinagar",139.00,5516.0,"Situated in koba, gandhinagar, this 3 bhk builder floor spans 2520 sqft on the 5th floor of a 10-Story mid-Rise. The 1-5 year old residential property is unfurnished and ready for immediate possession. With 3 bedrooms, 3 bathrooms, and lift access, it offers convenience close to infocity, health focus clinic, and pandit deendayal petroleum university.",(234 sqm),NaN,Ready To Move,,https://www.99acres.com/3-bhk-bedroom-independent-builder-floor-for-sale-in-koba-gandhinagar-2520-sqft-spid-Y91296850,https://static.99acres.com/universalapp/img/downArrowNew.png
323,"3 Bedroom Housein Mansa, Gandhinagar",3 BHK,"Mansa, Gandhinagar",75.00,6696.0,"Available by 2029, this under-Construction 3 bhk independent villa in keshav aaradhyam, mansa, gandhinagar offers 1120 sqft of well-Planned space with 3 bedrooms and 3 bathrooms. The residential property is unfurnished and ideal for those seeking proximity to multiple hospitals, including yashasvi eye hospital and shivam surgical hospital.",(104 sqm),NaN,Under Construction,,https://www.99acres.com/3-bhk-bedroom-independent-house-villa-for-sale-in-mansa-gandhinagar-1120-sqft-spid-E91290778,https://static.99acres.com/universalapp/img/downArrowNew.png
326,"Residential land / Plotin KAMAREDDY, Gandhinagar",NaN,"KAMAREDDY, Gandhinagar",55.00,18900.0,"Set in gandhinagar, kamareddy, this 291 sqft residential plot offers ready availability within three months. Ideal for building your own home, the land is unbuilt and unfurnished. Positioned in a developing area, it provides a practical opportunity for buyers seeking a compact, accessible site for future construction.",(27 sqm),NaN,Under Construction,,https://www.99acres.com/residential-land-plot-for-sale-in-gandhinagar-32-sqyd-spid-J91270268,https://static.99acres.com/universalapp/img/downArrowNew.png
327,"4 Bedroom Housein Vasana Hadmatia, Sargasan",4 BHK,"Vasana Hadmatia, Sargasan",330.00,26539.0,"Located in vasana hadmatia, sargasan, gandhinagar, this 4 bhk independent house spans 1413 sqft across multiple floors. With 4 bedrooms and 3 bathrooms, the 10+ year old villa is furnished and available immediately. Nearby religious sites include shree mahakali mataji, swaminarayan, and gayatri mandir, adding cultural value to this residential sale.",(131 sqm),NaN,Ready To Move,,https://www.99acres.com/4-bhk-bedroom-independent-house-villa-for-sale-in-vasana-hadmatia-gandhinagar-1413-sqft-r1-spid-N91033046,https://static.99acres.com/universalapp/img/downArrowNew.png
332,"3 BHK Flatin Randesan, Gandhinagar",3 BHK Flat,"Randesan, Gandhinagar",100.00,6105.0,"This 3 bhk flat, spanning 1638 sqft, is available for immediate sale in satyamev riviera, randesan, gandhinagar. Located on the 3rd floor of a low-Rise, 5-10 year old building, it offers 3 bedrooms and 3 bathrooms in a well-Maintained layout. Nearby religious landmarks and metro access add to its appeal.",(152 sqm),Super Built-up Area,Ready To Move,,https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-satyamev-riviera-randesan-gandhinagar-1638-sqft-spid-U91225168,https://static.99acres.com/universalapp/img/checkLineGray.svg
333,"2 BHK Flatin Randheja, Gandhinagar",2 BHK Flat,"Randheja, Gandhinagar",36.00,29032.0,"This 2 bhk flat on the 3rd floor of a low-Rise building in swamev sparsh county, randheja, gandhinagar offers 124 sqft of semi-Furnished living space. Featuring 2 bedrooms, 2 bathrooms, a modular kitchen, and parking, the 5-10 year-Old property is available for immediate sale, close to randheja railway station and sheth n.N saravajanik hospital.",(12 sqm),Built-up Area,Ready To Move,,https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-swamev-sparsh-county-randheja-gandhinagar-124-sqft-spid-S91213322,https://static.99acres.com/universalapp/img/checkLineGray.svg
336,"4 Bedroom Housein Vasana Hadmatia, Sargasan",4 BHK,"Vasana Hadmatia, Sargasan",415.00,18444.0,"Open from 3 side, vaastu complaint north facing entry and south east kitchen.Available for immediate sale, this 4 bhk independent house in vasana hadmatia, sargasan, gandhinagar offers 2250 sqft of well-Maintained living space. Featuring 4 bedrooms and 4 bathrooms across its layout, the 10+ year old villa is unfurnished and benefits from proximity to several religious sites including shree maha...",(209 sqm),NaN,Ready To Move,,https://www.99acres.com/4-bhk-bedroom-independent-house-villa-for-sale-in-vasana-hadmatia-gandhinagar-2475-sqft-spid-P91189868,https://static.99acres.com/universalapp/img/downArrowNew.png
340,"3 BHK Flatin Sargasan, Gandhinagar",3 BHK Flat,"Sargasan, Gandhinagar",125.00,1216.0,"Located in aavkar 96, sargasan, gandhinagar, this 3 bhk flat on the 2nd floor of a 14-Floor high-Rise offers 10279.54 sqft of well-Planned space. Built 1-5 years ago, it includes 3 bathrooms and comes fully furnished with immediate availability. Amenities such as a gym, rainwater harvesting, power backup, and lift enhance living, near key connectivity points and schools.",(955 sqm),Carpet Area,Ready To Move,,https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-aavkar-96-sargasan-gandhinagar-10280-sqft-spid-K91150552,https://static.99acres.com/universalapp/img/checkLineGray.svg
342,"3 BHK Flatin Kudasan, Gandhinagar",3 BHK Flat,"Kudasan, Gandhinagar",75.00,7500.0,"Located in psy pramukh signature, kudasan, gandhinagar, this 10+ year old 3 bhk flat offers 1000 sqft of comfortable living on the 5th floor of a 7-Floor mid-Rise building. Available immediately, it features 3 bedrooms and 3 bathrooms, is vaastu compliant, semi-Furnished, and includes access to a gym, clubhouse, and lift. Nearby are several temples and a multispeciality dental clinic.",(93 sqm),Carpet Area,Ready To Move,,https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-psy-pramukh-signature-kudasan-gandhinagar-1000-sqft-spid-G91128962,https://static.99acres.com/universalapp/img/checkLineGray.svg
347,"1 BHK Flatin Sargasan, Gandhinagar",1 BHK Flat,"Sargasan, Gandhinagar",34.00,4250.0,"This 900 sqft 1 bhk flat, located on the 2nd floor of a low-Rise building in sthapan 2, sargasan, gandhinagar, offers immediate availability. The 5-10 year old apartment is well-Maintained and unfurnished, close to key religious sites and medical facilities, making it ideal for comfortable residential living.",(84 sqm),Super Built-up Area,Ready To Move,,https://www.99acres.com/1-bhk-bedroom-apartment-flat-for-sale-in-sthapan-2-sargasan-gandhinagar-900-sqft-spid-K91006136,https://static.99acres.com/universalapp/img/checkLineGray.svg
349,"2 BHK Flatin Pethapur, Gandhinagar",2 BHK Flat,"Pethapur, Gandhinagar",48.85,3368.0,"Located on the top floor of deep siddheshwari heights in pethapur, this 2 bhk flat offers 1450 sqft of well-Planned space. The 1-5 year old mid-Rise apartment features 2 bedrooms and 2 bathrooms, available immediately and unfurnished. Close to multiple hospitals, it combines convenience with comfortable living in gandhinagar.",(135 sqm),Carpet Area,Ready To Move,,https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-deep-siddheshwari-heights-pethapur-gandhinagar-1450-sqft-spid-C90998084,https://static.99acres.com/universalapp/img/checkLineGray.svg
353,"Residential land / Plotin Dashela, Gandhinagar",NaN,"Dashela, Gandhinagar",400.00,1327.0,"Located in dashela, gandhinagar, this residential land offers 30,138.96 sqft of open space ready for immediate sale. Perfect for building your dream home, the plot boasts a prime location with easy access to local amenities. This opportunity allows for flexible design and development in a serene neighborhood.","(2,800 sqm)",NaN,Ready To Move,,https://www.99acres.com/residential-land-plot-for-sale-in-gandhinagar-3349-sqyd-spid-F90989720,https://static.99acres.com/universalapp/img/downArrowNew.png
356,"4 Bedroom Housein Raysan, Gandhinagar",4 BHK,"Raysan, Gandhinagar",200.00,95238.0,"This 4 bhk independent house in raysan, gandhinagar offers 210 sqft of well-Planned space, featuring 4 bedrooms and 4 bathrooms. Built 5-10 years ago, the villa is available immediately and comes unfurnished. Located near multiple hospitals and infocity, it combines convenience with comfort on a quiet floor.",(20 sqm),NaN,Ready To Move,,https://www.99acres.com/4-bhk-bedroom-independent-house-villa-for-sale-in-raysan-gandhinagar-210-sqft-spid-R90934376,https://static.99acres.com/universalapp/img/downArrowNew.png
357,"1 Bedroom Housein Uvarsad, Gandhinagar",1 BHK,"Uvarsad, Gandhinagar",17.00,3541.0,"Located in vankarvas, uvarsad, gandhinagar, this 1 bhk independent house spans 480 sqft and is available for immediate sale. Over 10 years old, the home features one bedroom and one bathroom, offering a practical layout on a single floor. The property is unfurnished, ideal for customizing your living space in a peaceful neighborhood.",(45 sqm),NaN,Ready To Move,,https://www.99acres.com/1-bhk-bedroom-independent-house-villa-for-sale-in-uvarsad-gandhinagar-480-sqft-spid-B90928750,https://static.99acres.com/universalapp/img/downArrowNew.png
358,"2 BHK Flatin Sargasan, Gandhinagar",2 BHK Flat,"Sargasan, Gandhinagar",70.00,596.0,"Situated in swagat queens land, sargasan, gandhinagar, this 2 bhk flat offers 11745 sqft in a high-Rise building on the 7th floor of 14. Semi-Furnished and 1-5 years old, it includes 2 bathrooms, modular kitchen, lift, power backup, and parking. Immediate availability with gym, clubhouse, and close to metro, malls, schools, and highways.","(1,091 sqm)",Super Built-up Area,Ready To Move,,https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-swagat-queens-land-sargasan-gandhinagar-11745-sqft-spid-P90922140,https://static.99acres.com/universalapp/img/StarNew.png
360,"3 BHK Flatin Randesan, Gandhinagar",3 BHK Flat,"Randesan, Gandhinagar",85.00,4722.0,"Located in the serene sheetal vedika habitat, randesan, gandhinagar, this 3 bhk flat spans 2025 sqft on the 3rd floor of a low-Rise, 5-10 year old building. Offering 3 bedrooms and 3 bathrooms, it comes semi-Furnished and is available for immediate sale. Close to a metro, market, pdpu, swaminarayan kanyashala, cuty pulse cinema, temples and healthcare facilities like svms hospital, ahmd-Gngr hi...",(188 sqm),Super Built-up Area,Ready To Move,,https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-sheetal-vedika-habitat-randesan-gandhinagar-2025-sqft-spid-P90919302,https://static.99acres.com/universalapp/img/downArrowNew.png
459,"3 BHK Builder Floorin Sargasan, Gandhinagar",3 BHK Builder Floor,"Sargasan, Gandhinagar",140.00,68292.0,2400 sqft open terrace garden and road both side facing,(19 sqm),NaN,Ready To Move,,https://www.99acres.com/3-bhk-bedroom-independent-builder-floor-for-sale-in-sargasan-gandhinagar-205-sqft-spid-Y89824530,https://static.99acres.com/universalapp/img/downArrowNew.png
460,"3 BHK Builder Floorin Sargasan, Gandhinagar",3 BHK Builder Floor,"Sargasan, Gandhinagar",140.00,68292.0,2400 sqft open terrace garden and road both side facing,(19 sqm),NaN,Ready To Move,,https://www.99acres.com/3-bhk-bedroom-independent-builder-floor-for-sale-in-sargasan-gandhinagar-205-sqft-spid-Y89824248,https://static.99acres.com/universalapp/img/downArrowNew.png
1167,"2 BHK Flatin Koba, Gandhinagar",2 BHK Flat,"Koba, Gandhinagar",65.00,8125.0,"Situated on the 2nd floor of a low-Rise building in satyamev surya, koba, this 10+ year old 2 bhk flat offers 800 sqft of well-Maintained living space. Ready for immediate possession, it features 2 bedrooms, 1 bathroom, and is partially furnished. Enjoy nearby amenities like a clubhouse, lift access, and proximity to health focus physiotherapy clinic, infocity, and pandit deendayal petroleum un...",(74 sqm),Carpet Area,Ready To Move,,https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-satyamev-surya-koba-gandhinagar-800-sqft-spid-U91322076,https://static.99acres.com/universalapp/img/checkLineGray.svg
1169,"4 BHK Flatin Koba, Gandhinagar",4 BHK Flat,"Koba, Gandhinagar",150.00,11227.0,"This 4 bhk flat in hilltown the overa, koba, gandhinagar, offers 1336 sqft of modern living space on the 6th floor of a 15-Floor high-Rise. Under construction and ready by june 2027, it features 4 bedrooms and 4 bathrooms, comes unfurnished, includes a lift, and is close to a swimming pool. Conveniently near motera stadium metro and key amenities.",(124 sqm),Carpet Area,Under Construction,,https://www.99acres.com/4-bhk-bedroom-apartment-flat-for-sale-in-hilltown-the-overa-koba-gandhinagar-1336-sqft-spid-W91308058,https://static.99acres.com/universalapp/img/checkLineGray.svg
1174,"2 BHK Flatin Kalol, Gandhinagar",2 BHK Flat,"Kalol, Gandhinagar",22.00,40000.0,"Located in tata shubh griha, kalol, this 2 bhk flat on the 2nd floor of a low-Rise building offers 55 sqft of comfortable living. Ready for immediate sale, it features vitrified flooring, a gated society with lift access, and park views. Close to schools, healthcare, and shri hanumanji temple, its a practical choice in gandhinagars growing neighborhood.",(5 sqm),Carpet Area,Ready To Move,,https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-tata-shubh-griha-kalol-gandhinagar-55-sqft-spid-Z91248840,https://static.99acres.com/universalapp/img/downArrowNew.png
1175,"Residential propertyin Mansa, Gandhinagar",NaN,"Mansa, Gandhinagar",520.00,955.0,"Located in mansa, gandhinagar, this 54,450 sqft residential property offers immediate availability. A 1-5 year old building with a versatile layout, it overlooks key healthcare centers like yashasvi eye hospital and shivam surgical hospital, ensuring convenience. This unfurnished, multi-Floor property suits buyers seeking spacious, well-Positioned real estate in gandhinagar.","(5,059 sqm)",NaN,Ready To Move,,https://www.99acres.com/other-residential-property-for-sale-in-mansa-gandhinagar-54450-sqft-spid-K91248438,https://static.99acres.com/universalapp/img/downArrowNew.png
1177,"Residential propertyin Kudasan, Gandhinagar",NaN,"Kudasan, Gandhinagar",169.00,18074.0,"Situated in kudasan, gandhinagar, this newly constructed residential property offers 935 sqft on the ground floor. Built within the last year, it features a practical layout and is available for immediate sale. Residents benefit from proximity to several temples and a multispeciality dental clinic, enhancing convenience and community living.",(87 sqm),NaN,Ready To Move,,https://www.99acres.com/other-residential-property-for-sale-in-kudasan-gandhinagar-935-sqft-spid-Z91229168,https://static.99acres.com/universalapp/img/downArrowNew.png
1178,"2 BHK Flatin Ambika Nagar, Kalol, Gandhinagar",2 BHK Flat,"Ambika Nagar, Kalol, Gandhinagar",32.00,3200.0,"Located in sahjanand apartment, ambika nagar, this 2 bhk flat on the 1st floor of a low-Rise building offers 1000 sqft of comfortable living space. With 2 bedrooms and 2 bathrooms, the apartment is over 10 years old and available immediately. Nearby are key hospitals and the shri hanumanji temple, enhancing convenience.",(93 sqm),Carpet Area,Ready To Move,,https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-ambika-nagar-gandhinagar-1000-sqft-spid-R91225648,https://static.99acres.com/universalapp/img/downArrowNew.png
1179,"2 BHK Flatin Vavol, Gandhinagar",2 BHK Flat,"Vavol, Gandhinagar",42.00,3589.0,"Available immediately, this 2 bhk flat in nilkanth vila, vavol offers 117 sqft of well-Planned space on the 2nd floor of a low-Rise building. With 2 bedrooms and 2 bathrooms, the 5-10 year old apartment comes unfurnished. Located near key medical facilities in gandhinagar, its ideal for convenient living.",(109 sqm),Carpet Area,Ready To Move,,https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-vavol-gandhinagar-1170-sqft-spid-J91199502,https://static.99acres.com/universalapp/img/downArrowNew.png
1181,"Residential land / Plotin Koba, Gandhinagar",NaN,"Koba, Gandhinagar",325.00,8009.0,"Located in koba, gandhinagar, this 4058 sqft residential land plot is available for immediate sale. Featuring a corner position, the plot offers excellent access and visibility. Situated near health focus physiotherapy clinic, infocity, and pandit deendayal petroleum university, it combines convenience with potential, ideal for your next residential project.",(377 sqm),NaN,Ready To Move,,https://www.99acres.com/residential-land-plot-for-sale-in-koba-gandhinagar-451-sqyd-spid-W91171194,https://static.99acres.com/universalapp/img/downArrowNew.png

In [655]:
# Move extra text from Area_sqft to Description only for row 1320

extra_text = df.loc[1320, "Area_sqft"]

# Extract description part
description_part = extra_text.replace("1,875 sqft", "").strip()

# Add it to Description column
df.loc[1320, "Description"] = (
    str(df.loc[1320, "Description"]) + " " + description_part
).strip()

# Keep only correct sqft value
df.loc[1320, "Area_sqft"] = "1,875 sqft"

In [656]:
# Find corrupted Area_sqft rows
mask = ~df["Area_sqft"].str.match(
    r"^\d[\d,]*\.?\d*\s*sqft$",
    case=False,
    na=False
)

# Append corrupted Area_sqft text into Description
df.loc[mask, "Description"] = (
    df.loc[mask, "Description"].fillna("") + " " +
    df.loc[mask, "Area_sqft"].fillna("")
).str.strip()

# Set corrupted Area_sqft values to NaN
df.loc[mask, "Area_sqft"] = np.nan

In [657]:
df.loc[mask, ["Area_sqft", "Description"]]

,Area_sqft,Description
15,NaN,"Property for sell: Luxurious 4 bhk apartment Location: Skyra, 12th floor, opp - Gnlu metro station, koba, gandhinagar Size: 3870 sqft Features: - The appartments are situated at a strategic & convinient location of 2 road corner on 80 metre wide road just opposite gnlu metro station. - 4 spacious bedrooms & modern washrooms - Living rooms with a beautiful courtyard balcony - Fully vastu-Complia..."
85,NaN,"Property for sell: Luxurious 4 bhk apartment Location: Skyra, 12th floor, opp - Gnlu metro station, koba, gandhinagar Size: 3870 sqft Features: - The appartments are situated at a strategic & convinient location of 2 road corner on 80 metre wide road just opposite gnlu metro station. - 4 spacious bedrooms & modern washrooms - Living rooms with a beautiful courtyard balcony - Fully vastu-Complia..."
143,NaN,"Property for sell: Luxurious 4 bhk apartment Location: Skyra, 12th floor, opp - Gnlu metro station, koba, gandhinagar Size: 3870 sqft Features: - The appartments are situated at a strategic & convinient location of 2 road corner on 80 metre wide road just opposite gnlu metro station. - 4 spacious bedrooms & modern washrooms - Living rooms with a beautiful courtyard balcony - Fully vastu-Complia..."
314,NaN,"Sun spacelink is a premium residential project located in koba, gandhinagar, gujarat. The project is spread across 0.88 acres and consists of 90 units housed in 2 towers. Each unit offers configurations ranging from 3 bhk+3t to 3 bhk+3t, with sizes starting from 1255 sqft to 1327 sqft. The project is designed to provide a blend of comfort and style, featuring amenities such as a club house, chi..."
322,NaN,"Situated in koba, gandhinagar, this 3 bhk builder floor spans 2520 sqft on the 5th floor of a 10-Story mid-Rise. The 1-5 year old residential property is unfurnished and ready for immediate possession. With 3 bedrooms, 3 bathrooms, and lift access, it offers convenience close to infocity, health focus clinic, and pandit deendayal petroleum university."
323,NaN,"Available by 2029, this under-Construction 3 bhk independent villa in keshav aaradhyam, mansa, gandhinagar offers 1120 sqft of well-Planned space with 3 bedrooms and 3 bathrooms. The residential property is unfurnished and ideal for those seeking proximity to multiple hospitals, including yashasvi eye hospital and shivam surgical hospital."
326,NaN,"Set in gandhinagar, kamareddy, this 291 sqft residential plot offers ready availability within three months. Ideal for building your own home, the land is unbuilt and unfurnished. Positioned in a developing area, it provides a practical opportunity for buyers seeking a compact, accessible site for future construction."
327,NaN,"Located in vasana hadmatia, sargasan, gandhinagar, this 4 bhk independent house spans 1413 sqft across multiple floors. With 4 bedrooms and 3 bathrooms, the 10+ year old villa is furnished and available immediately. Nearby religious sites include shree mahakali mataji, swaminarayan, and gayatri mandir, adding cultural value to this residential sale."
332,NaN,"This 3 bhk flat, spanning 1638 sqft, is available for immediate sale in satyamev riviera, randesan, gandhinagar. Located on the 3rd floor of a low-Rise, 5-10 year old building, it offers 3 bedrooms and 3 bathrooms in a well-Maintained layout. Nearby religious landmarks and metro access add to its appeal."
333,NaN,"This 2 bhk flat on the 3rd floor of a low-Rise building in swamev sparsh county, randheja, gandhinagar offers 124 sqft of semi-Furnished living space. Featuring 2 bedrooms, 2 bathrooms, a modular kitchen, and parking, the 5-10 year-Old property is available for immediate sale, close to randheja railway station and sheth n.N saravajanik hospital."
336,NaN,"Open from 3 side, vaastu complaint north facing entry and south east kitchen.Available for immediate sale, this 4 bhk independent house in vasana hadmatia, sargasan, gandhinagar offers 2250 sqft of well-Maintained living space. Featuring 4 bedrooms and 4 bathrooms across its layout, the 10+ year old villa is unfurnished and benefits from proximity to several religious sites including shree maha..."
340,NaN,"Located in aavkar 96, sargasan, gandhinagar, this 3 bhk flat on the 2nd floor of a 14-Floor high-Rise offers 10279.54 sqft of well-Planned space. Built 1-5 years ago, it includes 3 bathrooms and comes fully furnished with immediate availability. Amenities such as a gym, rainwater harvesting, power backup, and lift enhance living, near key connectivity points and schools."
342,NaN,"Located in psy pramukh signature, kudasan, gandhinagar, this 10+ year old 3 bhk flat offers 1000 sqft of comfortable living on the 5th floor of a 7-Floor mid-Rise building. Available immediately, it features 3 bedrooms and 3 bathrooms, is vaastu compliant, semi-Furnished, and includes access to a gym, clubhouse, and lift. Nearby are several temples and a multispeciality dental clinic."
347,NaN,"This 900 sqft 1 bhk flat, located on the 2nd floor of a low-Rise building in sthapan 2, sargasan, gandhinagar, offers immediate availability. The 5-10 year old apartment is well-Maintained and unfurnished, close to key religious sites and medical facilities, making it ideal for comfortable residential living."
349,NaN,"Located on the top floor of deep siddheshwari heights in pethapur, this 2 bhk flat offers 1450 sqft of well-Planned space. The 1-5 year old mid-Rise apartment features 2 bedrooms and 2 bathrooms, available immediately and unfurnished. Close to multiple hospitals, it combines convenience with comfortable living in gandhinagar."
353,NaN,"Located in dashela, gandhinagar, this residential land offers 30,138.96 sqft of open space ready for immediate sale. Perfect for building your dream home, the plot boasts a prime location with easy access to local amenities. This opportunity allows for flexible design and development in a serene neighborhood."
356,NaN,"This 4 bhk independent house in raysan, gandhinagar offers 210 sqft of well-Planned space, featuring 4 bedrooms and 4 bathrooms. Built 5-10 years ago, the villa is available immediately and comes unfurnished. Located near multiple hospitals and infocity, it combines convenience with comfort on a quiet floor."
357,NaN,"Located in vankarvas, uvarsad, gandhinagar, this 1 bhk independent house spans 480 sqft and is available for immediate sale. Over 10 years old, the home features one bedroom and one bathroom, offering a practical layout on a single floor. The property is unfurnished, ideal for customizing your living space in a peaceful neighborhood."
358,NaN,"Situated in swagat queens land, sargasan, gandhinagar, this 2 bhk flat offers 11745 sqft in a high-Rise building on the 7th floor of 14. Semi-Furnished and 1-5 years old, it includes 2 bathrooms, modular kitchen, lift, power backup, and parking. Immediate availability with gym, clubhouse, and close to metro, malls, schools, and highways."
360,NaN,"Located in the serene sheetal vedika habitat, randesan, gandhinagar, this 3 bhk flat spans 2025 sqft on the 3rd floor of a low-Rise, 5-10 year old building. Offering 3 bedrooms and 3 bathrooms, it comes semi-Furnished and is available for immediate sale. Close to a metro, market, pdpu, swaminarayan kanyashala, cuty pulse cinema, temples and healthcare facilities like svms hospital, ahmd-Gngr hi..."
459,NaN,2400 sqft open terrace garden and road both side facing
460,NaN,2400 sqft open terrace garden and road both side facing
1167,NaN,"Situated on the 2nd floor of a low-Rise building in satyamev surya, koba, this 10+ year old 2 bhk flat offers 800 sqft of well-Maintained living space. Ready for immediate possession, it features 2 bedrooms, 1 bathroom, and is partially furnished. Enjoy nearby amenities like a clubhouse, lift access, and proximity to health focus physiotherapy clinic, infocity, and pandit deendayal petroleum un..."
1169,NaN,"This 4 bhk flat in hilltown the overa, koba, gandhinagar, offers 1336 sqft of modern living space on the 6th floor of a 15-Floor high-Rise. Under construction and ready by june 2027, it features 4 bedrooms and 4 bathrooms, comes unfurnished, includes a lift, and is close to a swimming pool. Conveniently near motera stadium metro and key amenities."
1174,NaN,"Located in tata shubh griha, kalol, this 2 bhk flat on the 2nd floor of a low-Rise building offers 55 sqft of comfortable living. Ready for immediate sale, it features vitrified flooring, a gated society with lift access, and park views. Close to schools, healthcare, and shri hanumanji temple, its a practical choice in gandhinagars growing neighborhood."
1175,NaN,"Located in mansa, gandhinagar, this 54,450 sqft residential property offers immediate availability. A 1-5 year old building with a versatile layout, it overlooks key healthcare centers like yashasvi eye hospital and shivam surgical hospital, ensuring convenience. This unfurnished, multi-Floor property suits buyers seeking spacious, well-Positioned real estate in gandhinagar."
1177,NaN,"Situated in kudasan, gandhinagar, this newly constructed residential property offers 935 sqft on the ground floor. Built within the last year, it features a practical layout and is available for immediate sale. Residents benefit from proximity to several temples and a multispeciality dental clinic, enhancing convenience and community living."
1178,NaN,"Located in sahjanand apartment, ambika nagar, this 2 bhk flat on the 1st floor of a low-Rise building offers 1000 sqft of comfortable living space. With 2 bedrooms and 2 bathrooms, the apartment is over 10 years old and available immediately. Nearby are key hospitals and the shri hanumanji temple, enhancing convenience."
1179,NaN,"Available immediately, this 2 bhk flat in nilkanth vila, vavol offers 117 sqft of well-Planned space on the 2nd floor of a low-Rise building. With 2 bedrooms and 2 bathrooms, the 5-10 year old apartment comes unfurnished. Located near key medical facilities in gandhinagar, its ideal for convenient living."
1181,NaN,"Located in koba, gandhinagar, this 4058 sqft residential land plot is available for immediate sale. Featuring a corner position, the plot offers excellent access and visibility. Situated near health focus physiotherapy clinic, infocity, and pandit deendayal petroleum university, it combines convenience with potential, ideal for your next residential project."
1184,NaN,"This 1 bhk flat, located on the 2nd floor of a 3-Story building in shubhlabh aavas yojna conop joi soc, chiloda, gandhinagar, offers 46 sqft of space. The 10+ year-Old residential property is available immediately and includes 1 bedroom and 1 bathroom, making it a practical choice for comfortable living."
1189,NaN,"Located in sector 4a gandhinagar, this 3 bhk independent house offers 90 sqft of well-Planned space with 3 bedrooms and 3 bathrooms. Over 10 years old and ready for immediate occupancy, it provides easy access to swaminarayan temple and multiple hospitals, making it a convenient residential choice in a peaceful neighborhood."
1259,NaN,"Urban comfort meets suburban peace at mahavir hills 2 Looking for a spacious home that keeps you close to the action but away from the noise? This 1215 sqft, 2 bhk high-Rise apartment offers the perfect blend of modern living and convenience. Located directly opposite shree kamlam on koba road, you are perfectly positioned between ahmedabad and gandhinagar. Space to breathe: Generous 1215 sqft ..."
1383,NaN,"We are proud owners of farmhouse available for sale in mahudi, gandhinagar. Available at price of rs 50 lacs. It has super area of 3600 sqft. It has 2 bhk, 2 bathroom, 2 balcony.It is a freehold property"

In [658]:
# After moving the extra text from Area_sqft to Description, we can now clean the Area_sqft column by removing commas, "sqft" text, and converting it to float datatype. 

df["Area_sqft"] = (
    df["Area_sqft"]
    .str.replace(",", "", regex=False)
    .str.replace("sqft", "", case=False, regex=False)
    .str.strip()
    .astype(float)
)

In [659]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1880 entries, 0 to 1883
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Name                  1880 non-null   object
 1   BHK                   1730 non-null   object
 2   Location              1880 non-null   object
 3   Price (INR in Lakhs)  1880 non-null   float64
 4   Price_per_sqft        1874 non-null   float64
 5   Area_sqft             1846 non-null   float64
 6   Area_sqm              1880 non-null   object
 7   Area_type             1482 non-null   object
 8   Status                1880 non-null   object
 9   Description           1880 non-null   object
 10  Property_URL          1880 non-null   object
 11  Image_URL             1880 non-null   object
dtypes: float64(3), object(9)
memory usage: 255.5+ KB

In [660]:
df['Area_sqm'].value_counts()

Area_sqm
(121 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           38
(171 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           37
(117 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           28
(105 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           25
(209 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           23
(130 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           22
(111 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           22
(167 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           21
(123 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           21
(101 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           18
(14 sqm)                                                                                                                                                                                                                                                                                                                                                                                                            17
(109 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           17
(93 sqm)                                                                                                                                                                                                                                                                                                                                                                                                            17
(90 sqm)                                                                                                                                                                                                                                                                                                                                                                                                            16
(113 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           16
(138 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           16
(119 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           16
(140 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           16
(188 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           16
(102 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           15
(156 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           15
(110 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           15
(73 sqm)                                                                                                                                                                                                                                                                                                                                                                                                            15
(230 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           15
(166 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           14
(79 sqm)                                                                                                                                                                                                                                                                                                                                                                                                            14
(125 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           14
(135 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           14
(199 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           14
(234 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           14
(100 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           14
(84 sqm)                                                                                                                                                                                                                                                                                                                                                                                                            14
(128 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           13
(151 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           13
(174 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           13
(268 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           12
(115 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           12
(139 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           12
(159 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           12
(176 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           12
(201 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           12
(184 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           12
(165 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           11
(245 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           11
(186 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           11
(192 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           11
(180 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           11
(149 sqm)                                                                                                                                                                                                                                                                                                                                                                                                           11
(92 sqm)                                                                                                                                                                                                                                                                                                                                                                                                            11

In [661]:
# Show the corrupted row first
df[df["Area_sqm"].str.contains("Bungalow", case=False, na=False)]

# Store corrupted text
text = df.loc[1875, "Area_sqm"]

# Move corrupted description into Description column
df.loc[1875, "Description"] = (
    str(df.loc[1875, "Description"]) + " " + text
).strip()

# Set Area_sqm as NaN for that row
df.loc[1875, "Area_sqm"] = np.nan

In [662]:
df['Area_sqm'].value_counts()

Area_sqm
(121 sqm)         38
(171 sqm)         37
(117 sqm)         28
(105 sqm)         25
(209 sqm)         23
(130 sqm)         22
(111 sqm)         22
(123 sqm)         21
(167 sqm)         21
(101 sqm)         18
(109 sqm)         17
(14 sqm)          17
(93 sqm)          17
(90 sqm)          16
(113 sqm)         16
(188 sqm)         16
(119 sqm)         16
(138 sqm)         16
(140 sqm)         16
(102 sqm)         15
(73 sqm)          15
(156 sqm)         15
(230 sqm)         15
(110 sqm)         15
(234 sqm)         14
(79 sqm)          14
(135 sqm)         14
(125 sqm)         14
(199 sqm)         14
(84 sqm)          14
(100 sqm)         14
(166 sqm)         14
(174 sqm)         13
(128 sqm)         13
(151 sqm)         13
(268 sqm)         12
(115 sqm)         12
(176 sqm)         12
(159 sqm)         12
(184 sqm)         12
(139 sqm)         12
(201 sqm)         12
(186 sqm)         11
(92 sqm)          11
(192 sqm)         11
(180 sqm)         11
(163 sqm)         11
(149 sqm)         11
(245 sqm)         11
(165 sqm)         11
(147 sqm)         10
(118 sqm)         10
(56 sqm)          10
(207 sqm)         10
(22 sqm)           9
(116 sqm)          9
(212 sqm)          9
(210 sqm)          9
(134 sqm)          9
(88 sqm)           9
(145 sqm)          9
(131 sqm)          9
(45 sqm)           9
(81 sqm)           8
(19 sqm)           8
(196 sqm)          8
(222 sqm)          8
(96 sqm)           8
(142 sqm)          8
(89 sqm)           8
(213 sqm)          8
(74 sqm)           8
(146 sqm)          8
(59 sqm)           8
(215 sqm)          8
(107 sqm)          8
(65 sqm)           8
(77 sqm)           7
(190 sqm)          7
(161 sqm)          7
(158 sqm)          7
(172 sqm)          7
(334 sqm)          7
(263 sqm)          7
(114 sqm)          7
(410 sqm)          7
(72 sqm)           7
(15 sqm)           7
(13 sqm)           7
(144 sqm)          7
(205 sqm)          7
(177 sqm)          7
(132 sqm)          6
(20 sqm)           6
(187 sqm)          6
(80 sqm)           6
(216 sqm)          6
(155 sqm)          6
(169 sqm)          6
(203 sqm)          6
(251 sqm)          6
(276 sqm)          6
(94 sqm)           6
(11 sqm)           6
(27 sqm)           6
(195 sqm)          6
(86 sqm)           6
(67 sqm)           6
(46 sqm)           6
(219 sqm)          6
(468 sqm)          6
(64 sqm)           6
(82 sqm)           6
(49 sqm)           6
(229 sqm)          6
(360 sqm)          5
(103 sqm)          5
(42 sqm)           5
(70 sqm)           5
(124 sqm)          5
(330 sqm)          5
(69 sqm)           5
(16 sqm)           5
(260 sqm)          5
(78 sqm)           5
(4 sqm)            5
(5,059 sqm)        5
(300 sqm)          5
(148 sqm)          5
(227 sqm)          5
(836 sqm)          5
(120 sqm)          5
(204 sqm)          5
(60 sqm)           5
(91 sqm)           5
(197 sqm)          4
(343 sqm)          4
(12 sqm)           4
(97 sqm)           4
(5 sqm)            4
(28 sqm)           4
(152 sqm)          4
(23 sqm)           4
(502 sqm)          4
(75 sqm)           4
(181 sqm)          4
(175 sqm)          4
(418 sqm)          4
(489 sqm)          4
(2,508 sqm)        4
(194 sqm)          4
(488 sqm)          4
(250 sqm)          4
(2,529 sqm)        4
(231 sqm)          4
(8 sqm)            4
(551 sqm)          4
(232 sqm)          4
(108 sqm)          4
(296 sqm)          4
(154 sqm)          4
(63 sqm)           4
(214 sqm)          4
(248 sqm)          4
(200 sqm)          4
(224 sqm)          4
(126 sqm)          4
(129 sqm)          4
(51 sqm)           4
(10 sqm)           4
(41 sqm)           4
(54 sqm)           3
(182 sqm)          3
(31 sqm)           3
(137 sqm)          3
(66 sqm)           3
(2 sqm)            3
(193 sqm)          3
(71 sqm)           3
(127 sqm)          3
(9 sqm)            3
(402 sqm)          3
(242 sqm)          3
(160 sqm)          3
(279 sqm)          3
(272 sqm)          3
(18 sqm)           3
(259 sqm)          3
(76 sqm)           3
(407 sqm)          3
(301 sqm)          3
(34 sqm)           3
(288 sqm)          3
(6 sqm)            3
(284 sqm)          3
(254 sqm)          3
(241 sqm)          3
(133 sqm)          3
(33 sqm)           3
(5,666 sqm)        3
(372 sqm)          3
(38 sqm)           3
(247 sqm)          3
(240 sqm)          3
(297 sqm)          3
(164 sqm)          3
(253 sqm)          3
(543 sqm)          2
(35 sqm)           2
(153 sqm)          2
(270 sqm)          2
(753 sqm)          2
(136 sqm)          2
(364 sqm)          2
(445 sqm)          2
(189 sqm)          2
(347 sqm)          2
(122 sqm)          2
(395 sqm)          2
(264 sqm)          2
(85 sqm)           2
(7 sqm)            2
(318 sqm)          2
(925 sqm)          2
(217 sqm)          2
(143 sqm)          2
(238 sqm)          2
(303 sqm)          2
(370 sqm)          2
(36 sqm)           2
(52 sqm)           2
(29 sqm)           2
(43 sqm)           2
(32 sqm)           2
(202 sqm)          2
(294 sqm)          2
(68 sqm)           2
(271 sqm)          2
(58 sqm)           2
(150 sqm)          2
(157 sqm)          2
(179 sqm)          2
(198 sqm)          2
(594 sqm)          2
(386 sqm)          2
(24 sqm)           2
(355 sqm)          2
(226 sqm)          2
(322 sqm)          2
(244 sqm)          2
(401 sqm)          2
(1,672 sqm)        2
(55 sqm)           2
(416 sqm)          2
(311 sqm)          2
(266 sqm)          2
(98 sqm)           2
(293 sqm)          2
(3,846 sqm)        2
(21 sqm)           2
(104 sqm)          2
(627 sqm)          2
(408 sqm)          1
(900 sqm)          1
(4,390 sqm)        1
(876 sqm)          1
(183 sqm)          1
(328 sqm)          1
(0 sqm)            1
(5,017 sqm)        1
(106 sqm)          1
(549 sqm)          1
(10,117 sqm)       1
(11,028 sqm)       1
(520 sqm)          1
(711 sqm)          1
(4,375 sqm)        1
(4,756 sqm)        1
(690 sqm)          1
(375 sqm)          1
(223 sqm)          1
(344 sqm)          1
(312 sqm)          1
(339 sqm)          1
(564 sqm)          1
(585 sqm)          1
(354 sqm)          1
(329 sqm)          1
(319 sqm)          1
(1,031 sqm)        1
(280 sqm)          1
(221 sqm)          1
(11,382 sqm)       1
(936 sqm)          1
(1,881 sqm)        1
(321 sqm)          1
(646 sqm)          1
(2,32,378 sqm)     1
(291 sqm)          1
(901 sqm)          1
(57 sqm)           1
(298 sqm)          1
(366 sqm)          1
(261 sqm)          1
(308 sqm)          1
(498 sqm)          1
(15,176 sqm)       1
(424 sqm)          1
(644 sqm)          1
(1,693 sqm)        1
(191 sqm)          1
(95 sqm)           1
(2,150 sqm)        1
(185 sqm)          1
(53 sqm)           1
(50 sqm)           1
(206 sqm)          1
(326 sqm)          1
(420 sqm)          1
(397 sqm)          1
(514 sqm)          1
(61 sqm)           1
(493 sqm)          1
(447 sqm)          1
(886 sqm)          1
(252 sqm)          1
(233 sqm)          1
(269 sqm)          1
(1,171 sqm)        1
(352 sqm)          1
(450 sqm)          1
(422 sqm)          1
(649 sqm)          1
(278 sqm)          1
(256 sqm)          1
(409 sqm)          1
(340 sqm)          1
(719 sqm)          1
(220 sqm)          1
(237 sqm)          1
(11,129 sqm)       1
(616 sqm)          1
(99 sqm)           1
(895 sqm)          1
(208 sqm)          1
(435 sqm)          1
(8,448 sqm)        1
(218 sqm)          1
(246 sqm)          1
(1,923 sqm)        1
(235 sqm)          1
(309 sqm)          1
(332 sqm)          1
(513 sqm)          1
(1,589 sqm)        1
(87 sqm)           1
(377 sqm)          1
(273 sqm)          1
(494 sqm)          1
(368 sqm)          1
(467 sqm)          1
(3,345 sqm)        1
(4,181 sqm)        1
(452 sqm)          1
(292 sqm)          1
(1,965 sqm)        1
(662 sqm)          1
(669 sqm)          1
(243 sqm)          1
(274 sqm)          1
(178 sqm)          1
(506 sqm)          1
(62 sqm)           1
(376 sqm)          1
(647 sqm)          1
(462 sqm)          1
(464 sqm)          1
(4,00,639 sqm)     1
(893 sqm)          1
(13,911 sqm)       1
(3,399 sqm)        1
(22,297 sqm)       1
(17,705 sqm)       1
(2,800 sqm)        1
(168 sqm)          1
(421 sqm)          1
(23,396 sqm)       1
(955 sqm)          1
(6,020 sqm)        1
(1,091 sqm)        1
(7,284 sqm)        1
(25 sqm)           1
(624 sqm)          1
(37 sqm)           1
(2,125 sqm)        1
(1,338 sqm)        1
(112 sqm)          1
(621 sqm)          1
(39 sqm)           1
(26 sqm)           1
(3,516 sqm)        1
(1,212 sqm)        1
(353 sqm)          1
Name: count, dtype: int64

In [663]:
# After moving the extra text from Area_sqm to Description, we can now clean the Area_sqm column by removing brackets, commas, "sqm" text, and converting it to float datatype.

df["Area_sqm"] = (
    df["Area_sqm"]
    .str.replace("(", "", regex=False)
    .str.replace(")", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.replace("sqm", "", case=False, regex=False)
    .str.strip()
    .astype(float)
)

Missing Area_sqft values will be filled using Area_sqm through unit conversion, after which we can remove Area_sqm  to eliminate redundant information.

In [664]:
# Find rows where Area_sqft is missing but Area_sqm is available
mask = df["Area_sqft"].isna() & df["Area_sqm"].notna()

# Fill missing Area_sqft using Area_sqm conversion
df.loc[mask, "Area_sqft"] = df.loc[mask, "Area_sqm"] * 10.764

# Remove Area_sqm column after filling missing values
df.drop(columns=["Area_sqm"], inplace=True)

In [665]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1880 entries, 0 to 1883
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Name                  1880 non-null   object
 1   BHK                   1730 non-null   object
 2   Location              1880 non-null   object
 3   Price (INR in Lakhs)  1880 non-null   float64
 4   Price_per_sqft        1874 non-null   float64
 5   Area_sqft             1880 non-null   float64
 6   Area_type             1482 non-null   object
 7   Status                1880 non-null   object
 8   Description           1880 non-null   object
 9   Property_URL          1880 non-null   object
 10  Image_URL             1880 non-null   object
dtypes: float64(3), object(8)
memory usage: 240.8+ KB

In [666]:
df['Area_type'].value_counts()

Area_type
Super Built-up Area                                                                                                                                                                                                                                                                                                                                                                                                 746
Carpet Area                                                                                                                                                                                                                                                                                                                                                                                                         558
Built-up Area                                                                                                                                                                                                                                                                                                                                                                                                       144
Looking for a 3 bhk property for sale in gandhinagar? Buy this 3 bhk flat in shukan silver that is situated in urjanagar 1, gandhinagar. This residential flat is east-Facing direction. The flat is over 130 sq.Ft. Carpet area and comes with 3 bedroom(s), 3 bathrooms and 2 balconies. The residential building has 8 floors in total and the flat for sale is located on the 2nd floor. An added advanta...      5
The flat is over 1260 sq.Ft. Carpet area and comes with 3 bedroom(s), 3 bathrooms and 1 balcony. The property is located on the 4th floor of a 8 floors tall building. As the project is already ready to move, so you can easily move into this 5-10 years old property. Fix furnished with modular kitchen, sofa set, fix ward robe, bed . Well maintain flat and society, prime location, society has a ga...      5
Society name: Hari aalayam, sargasan (On 2nd floor out of 5 floors) Built up area: 238 sq.Yd. Carpet area: 125 sq.Yd. Features: Fully furnished 3 rooms + 3 bathrooms & 1 modular kitchen Electric geysers in 2 bathrooms 6 fans installed Ac installed in living room Hydrolic storage beds with mattresses 2.16 kw solar panel (Dedicated to flat) Dedicated parking space Garden facing master bedeoom Ope...      1
Affordable luxury 3 bhk top-Floor flat chiloda char rasta Property highlights: - Carpet area: 950 sq ft, total area: 1500 sq ft - 3 bedrooms, 3 bathrooms, semi-Furnished - 4 balconies (Hall, kitchen, 2 bedrooms) - Top floor in 7-Storey building, airy & well-Lit - Dedicated lift for only 3 flats per floor - 10-Ft wide common passageway with stairs & lift access - 2 adjacent underground parking s...      1
The flat is over 2151 sq.Ft. Carpet area and comes with 3 bedroom(s), 3 bathrooms and more than 3 balconies. The property is located on the 4th floor of a 14 floors tall building. This 0-1 year old property is available for immediate possession as the project is ready to move.\nPrice is not negotiable                                                                                                        1
The flat is over 529 sq.Ft. Carpet area and comes with 1 bedroom(s), 1 bathroom and 2 balconies. The flat has a total of 33 floors and this property is situated on 7th floor. As the property is currently under construction , you can expect to get the possession within 6 months. The vitrified flooring of this flat is beautifully designed and helps to give it a pleasing look. The flat will offer ...      1
Located in the popular residential address of kudasan, gandhinagar, shivalay parisar is one of the most preferred destination for apartments in gandhinagar. This 3 bhk flat is your ticket to be a part of this community. The flat is over 2700 sq.Ft. Carpet area and comes with 3 bedroom(s), 3 bathrooms and 1 balcony. This flat lies on the top level of a 7 storey building. Being a ready to move pr...      1
The flat is over 810 sq.Ft. Carpet area and comes with 2 bedroom(s), 2 bathrooms and 1 balcony. The flat has a total of 7 floors and this property is situated on 4th floor. An added advantage of this 1-5 years old flat is that it is available for immediate possession as the project is already ready to move. Well maintain flat with pop lights and interior design, all fix furnished, amenities lik...      1
This residential flat is east-Facing direction. The flat is over 1278 sq.Ft. Carpet area and comes with 3 bedroom(s), 3 bathrooms and 2 balconies. This flat lies on the 1st level of a 8 storey building. An added advantage of this 5-10 years old flat is that it is available for immediate possession as the project is already ready to move. The beautifully designed vitrified flooring enhances the ...      1
Situated in sargasan, gandhinagar, atmos by solaire is a well planned society that offers a pleasant living experience to its residents. This 4 bhk flat in gandhinagar is your opportunity to be a part of this community. The flat is facing the east direction. The flat is over 190 sq.M. Carpet area and comes with 4 bedroom(s), 4 bathrooms and 2 balconies. The residential building has 13 floors in...      1
This lovely 3 bhk apartment/flat in sargasan is available for sale in one of gandhinagar's most popular projects, ashwamegh elite. The flat is east-Facing. The flat is over 77 sq.M. Carpet area and comes with 3 bedroom(s), 3 bathrooms and 1 balcony. This flat is situated on the 1st floor of this 11 floors tall residential building. This 0-1 year old property is available for immediate possessio...      1
This is a east-Facing property. The flat is over 1278 sq.Ft. Carpet area and comes with 3 bedroom(s), 3 bathrooms and 2 balconies. The property is located on the 1st floor of a 8 floors tall building. Being a ready to move project, you can expect immediate possession of this 5-10 years old property. The flat comes well built with vitrified flooring options. The flat will offer a modern lifestyl...      1
The flat is over 1410 sq.Ft. Carpet area and comes with 3 bedroom(s), 3 bathrooms and 1 balcony. This flat is situated on the 9th floor of this 13 floors tall residential building. Being a ready to move project, you can expect immediate possession of this 0-1 year old property. This project is prime location, best residential project, best quality construction , all amenities here like a gym, i...      1
The flat is west-Facing. The flat is over 630 sq.Ft. Carpet area and comes with 2 bedroom(s), 2 bathrooms and 2 balconies. The flat has a total of 33 floors and this property is situated on 22nd floor. Being a ready to move project, you can expect immediate possession of this 1-5 years old property. The beautifully designed vitrified flooring enhances the beauty of the flat. This residential pr...      1
Located in the popular residential address of gift city, gandhinagar, sangath ipl smart life is one of the most preferred destination for apartments in gandhinagar. This 2 bhk flat is your ticket to be a part of this community. The flat is north-Facing. The flat is over 777 sq.Ft. Carpet area and comes with 2 bedroom(s), 2 bathrooms and 1 balcony. The residential building has 24 floors in total...      1
This beautiful 3 bhk flat in kudasan, gandhinagar is situated in vision ventilla, one of the popular residential society in gandhinagar. The flat is over 1186 sq.Ft. Carpet area and comes with 3 bedroom(s), 3 bathrooms and 1 balcony. This flat lies on the 7th level of a 13 storey building. This residential property is still under construction and will be available for possession by december 202...      1
The flat is over 1550 sq.Ft. Carpet area and comes with 2 bedroom(s), 2 bathrooms and 3 balconies. This flat is situated on the 10th floor of this 14 floors tall residential building. This residential property is still under construction and will be available for possession by december 2027. The vitrified flooring of this flat is beautifully designed and helps to give it a pleasing look. All th...      1
This property faces the west direction. The flat is over 384 sq.Ft. Carpet area and comes with 1 bedroom(s), 1 bathroom . This flat is situated on the 1st floor of this 4 floors tall residential building. This is a ready to move project and the property is 1-5 years old.                                                                                                                                       1
The flat is facing the north-East direction. The flat is over 680 sq.Ft. Carpet area and comes with 2 bedroom(s), 2 bathrooms and 1 balcony. The flat has a total of 8 floors and this property is situated on 2nd floor. As the project is already ready to move, so you can easily move into this 1-5 years old property. The floor of this flat is beautifully designed using vitrified flooring, giving t...      1
The flat is over 1255 sq.Ft. Carpet area and comes with 3 bedroom(s), 3 bathrooms and 1 balcony. This flat is situated on the 7th floor of this 14 floors tall residential building. This 0-1 year old property is available for immediate possession as the project is ready to move. Hrudhya is designed very well to provide modern facilities such as swimming pool, fitness centre / gym, grocery shop, ...      1
The flat is east-Facing. The flat is over 1328 sq.Ft. Carpet area and comes with 3 bedroom(s), 2 bathrooms and 3 balconies. The flat has a total of 5 floors and this property is situated on 3rd floor. This is a ready to move project and the property is 1-5 years old. The flat comes well built with marble flooring options. The flat will offer a modern lifestyle as it is presented with many of th...      1
The flat is over 74 sq.M. Carpet area and comes with 1 bedroom(s), 2 bathrooms . The flat has a total of 5 floors and this property is situated on 3rd floor. As the project is already ready to move, so you can easily move into this 1-5 years old property.                                                                                                                                                       1
This beautiful 2 bhk flat in koba, gandhinagar is situated in sant vihar 1, one of the popular residential society in gandhinagar. The flat is east-Facing. The flat is over 880 sq.Ft. Carpet area and comes with 2 bedroom(s), 2 bathrooms and 3 balconies. The property is located on the 2nd floor of a 9 floors tall building. This is a ready to move project and the property is 1-5 years old. The vi...      1
This lovely 1 bhk apartment/flat in kalol is available for sale in one of gandhinagar's most popular projects, yash pushpak heights. The flat is over 530 sq.Ft. Carpet area and comes with 1 bedroom(s), 2 bathrooms and 1 balcony. This flat is situated on the 2nd floor of this 7 floors tall residential building. Being a ready to move project, you can expect immediate possession of this 1-5 years ...      1
This 1 bhk apartment is available for sale in maruti apartment, one of the most prominent projects for flats in randheja, gandhinagar. The flat is over 270 sq.Ft. Carpet area and comes with 1 bedroom(s), 1 bathroom and 1 balcony. The residential building has 4 floors in total and the flat for sale is located on the 3rd floor. Being a ready to move project, you can expect immediate possession of...      1
Looking for magnificent 2 bhk builder floors in babul gandhinagar? This property is the best deal for you. Equipped with 2 bedrooms, 2 bathrooms. This property is semi-Furnished. Carpet area of the property is 450 sq.Ft. This builder floor apartment is located at ground floor in a building of total 4 floors. You can plan to move in immediately in this amazing ready to move in builder floor. Thi...      1
Name: count, dtype: int64

Invalid Area_type entries caused by scraping inconsistencies were moved to the Description column and replaced with NaN to maintain data consistency.

In [667]:
# Valid Area_type values
valid_area_types = [
    "Super Built-up Area",
    "Carpet Area",
    "Built-up Area"
]

# Find corrupted Area_type rows
mask = (
    df["Area_type"].notna() &
    ~df["Area_type"].isin(valid_area_types)
)

# Move corrupted Area_type text into Description
df.loc[mask, "Description"] = (
    df.loc[mask, "Description"].fillna("") + " " +
    df.loc[mask, "Area_type"]
).str.strip()

# Replace corrupted Area_type values with NaN
df.loc[mask, "Area_type"] = np.nan

In [668]:
df.loc[mask, ["Area_type", "Description"]]

,Area_type,Description
55,NaN,"Looking for a 3 bhk property for sale in gandhinagar? Buy this 3 bhk flat in shukan silver that is situated in urjanagar 1, gandhinagar. This residential flat is east-Facing direction. The flat is over 130 sq.Ft. Carpet area and comes with 3 bedroom(s), 3 bathrooms and 2 balconies. The residential building has 8 floors in total and the flat for sale is located on the 2nd floor. An added advanta..."
70,NaN,"The flat is over 1260 sq.Ft. Carpet area and comes with 3 bedroom(s), 3 bathrooms and 1 balcony. The property is located on the 4th floor of a 8 floors tall building. As the project is already ready to move, so you can easily move into this 5-10 years old property. Fix furnished with modular kitchen, sofa set, fix ward robe, bed . Well maintain flat and society, prime location, society has a ga..."
125,NaN,"Looking for a 3 bhk property for sale in gandhinagar? Buy this 3 bhk flat in shukan silver that is situated in urjanagar 1, gandhinagar. This residential flat is east-Facing direction. The flat is over 130 sq.Ft. Carpet area and comes with 3 bedroom(s), 3 bathrooms and 2 balconies. The residential building has 8 floors in total and the flat for sale is located on the 2nd floor. An added advanta..."
140,NaN,"The flat is over 1260 sq.Ft. Carpet area and comes with 3 bedroom(s), 3 bathrooms and 1 balcony. The property is located on the 4th floor of a 8 floors tall building. As the project is already ready to move, so you can easily move into this 5-10 years old property. Fix furnished with modular kitchen, sofa set, fix ward robe, bed . Well maintain flat and society, prime location, society has a ga..."
183,NaN,"Looking for a 3 bhk property for sale in gandhinagar? Buy this 3 bhk flat in shukan silver that is situated in urjanagar 1, gandhinagar. This residential flat is east-Facing direction. The flat is over 130 sq.Ft. Carpet area and comes with 3 bedroom(s), 3 bathrooms and 2 balconies. The residential building has 8 floors in total and the flat for sale is located on the 2nd floor. An added advanta..."
198,NaN,"The flat is over 1260 sq.Ft. Carpet area and comes with 3 bedroom(s), 3 bathrooms and 1 balcony. The property is located on the 4th floor of a 8 floors tall building. As the project is already ready to move, so you can easily move into this 5-10 years old property. Fix furnished with modular kitchen, sofa set, fix ward robe, bed . Well maintain flat and society, prime location, society has a ga..."
232,NaN,"Looking for a 3 bhk property for sale in gandhinagar? Buy this 3 bhk flat in shukan silver that is situated in urjanagar 1, gandhinagar. This residential flat is east-Facing direction. The flat is over 130 sq.Ft. Carpet area and comes with 3 bedroom(s), 3 bathrooms and 2 balconies. The residential building has 8 floors in total and the flat for sale is located on the 2nd floor. An added advanta..."
247,NaN,"The flat is over 1260 sq.Ft. Carpet area and comes with 3 bedroom(s), 3 bathrooms and 1 balcony. The property is located on the 4th floor of a 8 floors tall building. As the project is already ready to move, so you can easily move into this 5-10 years old property. Fix furnished with modular kitchen, sofa set, fix ward robe, bed . Well maintain flat and society, prime location, society has a ga..."
257,NaN,"Looking for a 3 bhk property for sale in gandhinagar? Buy this 3 bhk flat in shukan silver that is situated in urjanagar 1, gandhinagar. This residential flat is east-Facing direction. The flat is over 130 sq.Ft. Carpet area and comes with 3 bedroom(s), 3 bathrooms and 2 balconies. The residential building has 8 floors in total and the flat for sale is located on the 2nd floor. An added advanta..."
272,NaN,"The flat is over 1260 sq.Ft. Carpet area and comes with 3 bedroom(s), 3 bathrooms and 1 balcony. The property is located on the 4th floor of a 8 floors tall building. As the project is already ready to move, so you can easily move into this 5-10 years old property. Fix furnished with modular kitchen, sofa set, fix ward robe, bed . Well maintain flat and society, prime location, society has a ga..."
397,NaN,"Society name: Hari aalayam, sargasan (On 2nd floor out of 5 floors) Built up area: 238 sq.Yd. Carpet area: 125 sq.Yd. Features: Fully furnished 3 rooms + 3 bathrooms & 1 modular kitchen Electric geysers in 2 bathrooms 6 fans installed Ac installed in living room Hydrolic storage beds with mattresses 2.16 kw solar panel (Dedicated to flat) Dedicated parking space Garden facing master bedeoom Ope..."
436,NaN,"Affordable luxury 3 bhk top-Floor flat chiloda char rasta Property highlights: - Carpet area: 950 sq ft, total area: 1500 sq ft - 3 bedrooms, 3 bathrooms, semi-Furnished - 4 balconies (Hall, kitchen, 2 bedrooms) - Top floor in 7-Storey building, airy & well-Lit - Dedicated lift for only 3 flats per floor - 10-Ft wide common passageway with stairs & lift access - 2 adjacent underground parking s..."
502,NaN,"The flat is over 2151 sq.Ft. Carpet area and comes with 3 bedroom(s), 3 bathrooms and more than 3 balconies. The property is located on the 4th floor of a 14 floors tall building. This 0-1 year old property is available for immediate possession as the project is ready to move.\nPrice is not negotiable"
527,NaN,"The flat is over 529 sq.Ft. Carpet area and comes with 1 bedroom(s), 1 bathroom and 2 balconies. The flat has a total of 33 floors and this property is situated on 7th floor. As the property is currently under construction , you can expect to get the possession within 6 months. The vitrified flooring of this flat is beautifully designed and helps to give it a pleasing look. The flat will offer ..."
689,NaN,"Located in the popular residential address of kudasan, gandhinagar, shivalay parisar is one of the most preferred destination for apartments in gandhinagar. This 3 bhk flat is your ticket to be a part of this community. The flat is over 2700 sq.Ft. Carpet area and comes with 3 bedroom(s), 3 bathrooms and 1 balcony. This flat lies on the top level of a 7 storey building. Being a ready to move pr..."
769,NaN,"The flat is over 810 sq.Ft. Carpet area and comes with 2 bedroom(s), 2 bathrooms and 1 balcony. The flat has a total of 7 floors and this property is situated on 4th floor. An added advantage of this 1-5 years old flat is that it is available for immediate possession as the project is already ready to move. Well maintain flat with pop lights and interior design, all fix furnished, amenities lik..."
842,NaN,"This residential flat is east-Facing direction. The flat is over 1278 sq.Ft. Carpet area and comes with 3 bedroom(s), 3 bathrooms and 2 balconies. This flat lies on the 1st level of a 8 storey building. An added advantage of this 5-10 years old flat is that it is available for immediate possession as the project is already ready to move. The beautifully designed vitrified flooring enhances the ..."
882,NaN,"Situated in sargasan, gandhinagar, atmos by solaire is a well planned society that offers a pleasant living experience to its residents. This 4 bhk flat in gandhinagar is your opportunity to be a part of this community. The flat is facing the east direction. The flat is over 190 sq.M. Carpet area and comes with 4 bedroom(s), 4 bathrooms and 2 balconies. The residential building has 13 floors in..."
887,NaN,"This lovely 3 bhk apartment/flat in sargasan is available for sale in one of gandhinagar's most popular projects, ashwamegh elite. The flat is east-Facing. The flat is over 77 sq.M. Carpet area and comes with 3 bedroom(s), 3 bathrooms and 1 balcony. This flat is situated on the 1st floor of this 11 floors tall residential building. This 0-1 year old property is available for immediate possessio..."
923,NaN,"This is a east-Facing property. The flat is over 1278 sq.Ft. Carpet area and comes with 3 bedroom(s), 3 bathrooms and 2 balconies. The property is located on the 1st floor of a 8 floors tall building. Being a ready to move project, you can expect immediate possession of this 5-10 years old property. The flat comes well built with vitrified flooring options. The flat will offer a modern lifestyl..."
937,NaN,"The flat is over 1410 sq.Ft. Carpet area and comes with 3 bedroom(s), 3 bathrooms and 1 balcony. This flat is situated on the 9th floor of this 13 floors tall residential building. Being a ready to move project, you can expect immediate possession of this 0-1 year old property. This project is prime location, best residential project, best quality construction , all amenities here like a gym, i..."
987,NaN,"The flat is west-Facing. The flat is over 630 sq.Ft. Carpet area and comes with 2 bedroom(s), 2 bathrooms and 2 balconies. The flat has a total of 33 floors and this property is situated on 22nd floor. Being a ready to move project, you can expect immediate possession of this 1-5 years old property. The beautifully designed vitrified flooring enhances the beauty of the flat. This residential pr..."
1022,NaN,"Located in the popular residential address of gift city, gandhinagar, sangath ipl smart life is one of the most preferred destination for apartments in gandhinagar. This 2 bhk flat is your ticket to be a part of this community. The flat is north-Facing. The flat is over 777 sq.Ft. Carpet area and comes with 2 bedroom(s), 2 bathrooms and 1 balcony. The residential building has 24 floors in total..."
1056,NaN,"This beautiful 3 bhk flat in kudasan, gandhinagar is situated in vision ventilla, one of the popular residential society in gandhinagar. The flat is over 1186 sq.Ft. Carpet area and comes with 3 bedroom(s), 3 bathrooms and 1 balcony. This flat lies on the 7th level of a 13 storey building. This residential property is still under construction and will be available for possession by december 202..."
1142,NaN,"The flat is over 1550 sq.Ft. Carpet area and comes with 2 bedroom(s), 2 bathrooms and 3 balconies. This flat is situated on the 10th floor of this 14 floors tall residential building. This residential property is still under construction and will be available for possession by december 2027. The vitrified flooring of this flat is beautifully designed and helps to give it a pleasing look. All th..."
1188,NaN,"This property faces the west direction. The flat is over 384 sq.Ft. Carpet area and comes with 1 bedroom(s), 1 bathroom . This flat is situated on the 1st floor of this 4 floors tall residential building. This is a ready to move project and the property is 1-5 years old."
1215,NaN,"The flat is facing the north-East direction. The flat is over 680 sq.Ft. Carpet area and comes with 2 bedroom(s), 2 bathrooms and 1 balcony. The flat has a total of 8 floors and this property is situated on 2nd floor. As the project is already ready to move, so you can easily move into this 1-5 years old property. The floor of this flat is beautifully designed using vitrified flooring, giving t..."
1225,NaN,"The flat is over 1255 sq.Ft. Carpet area and comes with 3 bedroom(s), 3 bathrooms and 1 balcony. This flat is situated on the 7th floor of this 14 floors tall residential building. This 0-1 year old property is available for immediate possession as the project is ready to move. Hrudhya is designed very well to provide modern facilities such as swimming pool, fitness centre / gym, grocery shop, ..."
1312,NaN,"The flat is east-Facing. The flat is over 1328 sq.Ft. Carpet area and comes with 3 bedroom(s), 2 bathrooms and 3 balconies. The flat has a total of 5 floors and this property is situated on 3rd floor. This is a ready to move project and the property is 1-5 years old. The flat comes well built with marble flooring options. The flat will offer a modern lifestyle as it is presented with many of th..."
1466,NaN,"The flat is over 74 sq.M. Carpet area and comes with 1 bedroom(s), 2 bathrooms . The flat has a total of 5 floors and this property is situated on 3rd floor. As the project is already ready to move, so you can easily move into this 1-5 years old property."
1513,NaN,"This beautiful 2 bhk flat in koba, gandhinagar is situated in sant vihar 1, one of the popular residential society in gandhinagar. The flat is east-Facing. The flat is over 880 sq.Ft. Carpet area and comes with 2 bedroom(s), 2 bathrooms and 3 balconies. The property is located on the 2nd floor of a 9 floors tall building. This is a ready to move project and the property is 1-5 years old. The vi..."
1690,NaN,"This lovely 1 bhk apartment/flat in kalol is available for sale in one of gandhinagar's most popular projects, yash pushpak heights. The flat is over 530 sq.Ft. Carpet area and comes with 1 bedroom(s), 2 bathrooms and 1 balcony. This flat is situated on the 2nd floor of this 7 floors tall residential building. Being a ready to move project, you can expect immediate possession of this 1-5 years ..."
1777,NaN,"This 1 bhk apartment is available for sale in maruti apartment, one of the most prominent projects for flats in randheja, gandhinagar. The flat is over 270 sq.Ft. Carpet area and comes with 1 bedroom(s), 1 bathroom and 1 balcony. The residential building has 4 floors in total and the flat for sale is located on the 3rd floor. Being a ready to move project, you can expect immediate possession of..."
1873,NaN,"Looking for magnificent 2 bhk builder floors in babul gandhinagar? This property is the best deal for you. Equipped with 2 bedrooms, 2 bathrooms. This property is semi-Furnished. Carpet area of the property is 450 sq.Ft. This builder floor apartment is located at ground floor in a building of total 4 floors. You can plan to move in immediately in this amazing ready to move in builder floor. Thi..."

In [669]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1880 entries, 0 to 1883
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Name                  1880 non-null   object
 1   BHK                   1730 non-null   object
 2   Location              1880 non-null   object
 3   Price (INR in Lakhs)  1880 non-null   float64
 4   Price_per_sqft        1874 non-null   float64
 5   Area_sqft             1880 non-null   float64
 6   Area_type             1448 non-null   object
 7   Status                1880 non-null   object
 8   Description           1880 non-null   object
 9   Property_URL          1880 non-null   object
 10  Image_URL             1880 non-null   object
dtypes: float64(3), object(8)
memory usage: 240.8+ KB

In [670]:
df['Status'].value_counts()

Status
Ready To Move                                                                                                                                                                                                                                                                                                                                                                                                       1602
Under Construction                                                                                                                                                                                                                                                                                                                                                                                                   260
Construction g+2 (3 flor )\n4 badroom \n2 kitchen \nProperty highlights \nEast facing, 3 side open property, vetrified flooring, \nOnly 2 years,\n24 hour water and electricity \nB.U permission approved \n12 meter road\nFully furnished \n4 a.C\nSolar system                                                                                                                                                       3
Situated on the 17th floor of a 34-Story high-Rise, this 2 bhk flat in shivalik skyview, gift city offers 1599.51 sq.Ft. Of under-Construction space. With 2 bedrooms and 2 bathrooms, it comes unfurnished and includes access to a gym, clubhouse, pool, and lift. Conveniently close to schools, airport, and shopping, available january 2027.                                                                     1
Independent/builder floor is available for sell.Construction ages only 5-10 years old propertysituated in kalol.Area of the construction is 145.00 sq. Yards(Builtup area) it has been unfurnished.It has good design of 2 bedrooms. Non-Stop water supply in 2 bathrooms .It has been priced at rs 2400000.Located on 2nd floor out of 5.                                                                             1
New under-Construction project in randheja                                                                                                                                                                                                                                                                                                                                                                             1
Available from may 2028, this under-Construction 2 bhk flat at the rhythm elevate in karai, gandhinagar offers 155 sq.Ft. Of modern living space on the 5th floor of a 12-Story high-Rise. Featuring 2 bedrooms, 2 bathrooms, lift access, and a swimming pool, its close to koba circle metro, schools, nh 48, and esic hospital. Fully unfurnished for customization.                                                1
Planning to purchase a plot in gandhinagar? This plot in palodia is situated in one of the excellent locations of the city. This 710 sq.Yards super built up area plot is your opportunity to build a exceptional residence. Construction on this property can be easily done upto 3 floors. Boundary wall is already constructed to separate the plot from nearby properties. Immediately, possession of pro...       1
Constructed on a super built-Up area of 1503 sq. Ft., the flat comprises 2 bedrooms, 2 bathrooms, and 1 balcony. It is available on the 10th to 13th floors of a 13-Storey residential building. This under-Construction property will be ready for possession in approximately 2 months. The flat is designed to offer a modern lifestyle with amenities such as a fitness centre / gym, clubhouse, cctv sur...       1
Located in vida by nila spaces, gift city, this under-Construction 1 bhk apartment spans 529 sq.Ft. On the 7th floor of a 33-Story high-Rise. Featuring 2 bathrooms, lift access, and amenities like a gym and pool, it offers modern living with excellent connectivity near pdpu metro and national highway 48. Available from june 2028, ideal for residential sale.                                                1
Available from march 2027, this under-Construction 4 bhk flat offers 4050 sq.Ft. On the 5th floor of an 18-Storey high-Rise at kumbh avyanna, koba, gandhinagar. Featuring 4 bedrooms and 4 bathrooms, the well-Planned layout suits residential needs. Close to healthcare facilities and pandit deendayal petroleum university, it combines comfort with convenience.                                                1
Available by 2027, this under-Construction 2 bhk flat in shilp north sky, gift city offers 1430 sq.Ft. Of living space on the 8th floor of a 25-Story high-Rise. The residence includes 2 bedrooms and 2 bathrooms, is semi-Furnished, and features amenities like a clubhouse, swimming pool, lift, and power backup. Close to schools, malls, and nh 48 connectivity.                                                1
Plot for sale in vavol is available in gandhinagar. This locality resonates with your modern lifestyle. It's a 1048 sq.Yards super built up area property. Construction on this property can be easily done upto 6 floors. Immediately, possession of property can be transferred. The owner of the property has freehold entitlement over the land. The asking price is only 5.34 crore. The plot location i...       1
Spacious, ready to build plot in vavol, gandhinagar. It spans over spectacular 165 sq.Yards super built up area. Construction on this property can be easily done upto 4 floors. Immediately, possession of property can be transferred. The property is owned under freehold contract. The plot is available at a price of 1.16 crore.                                                                                1
Available from march 2027, this under-Construction 3 bhk flat on the 5th floor of a 13-Story high-Rise at shreeji sarvopari, sargasan, gandhinagar offers 1845 sq.Ft. Of well-Designed space. Featuring 3 bedrooms and 2 bathrooms, this residential apartment is close to key religious sites and sanjivani heart and medical hospital, blending convenience with comfort.                                            1
This 2 bhk flat, located on the 8th floor of a 34-Story high-Rise at shivalik skyview, gift city, gandhinagar, offers 1505.86 sq.Ft. Of under-Construction living space. Ready by dec 2027, it features 2 bedrooms, 2 bathrooms, and comes with key amenities like a clubhouse, gym, lift, and pool. Nearby are shree rang mall, nh48, and top schools.                                                                1
Located on the 19th floor of a high-Rise at vida by nila spaces, this under-Construction 2 bhk apartment in gift city offers 871 sq.Ft. Of well-Planned living space. Available within six months, it comes unfurnished with 2 bathrooms, lift access, power backup, and amenities like a gym and swimming pool. Conveniently close to pdpu metro and major schools.                                                   1
Available within 6 months, this 2 bhk flat in vida by nila spaces, gift city, gandhinagar spans 871 sq.Ft. Located on the 24th floor of a 33-Story high-Rise, the under-Construction apartment features 2 bedrooms and 2 bathrooms. Residents enjoy amenities like a gym, swimming pool, lift, and power backup, with excellent connectivity near pdpu metro and national highway 48.                                  1
Name: count, dtype: int64

Invalid Status entries caused by scraping inconsistencies were transferred to the Description column and replaced with NaN to preserve dataset consistency.

In [671]:
# Valid Status values
valid_status = [
    "Ready To Move",
    "Under Construction"
]

# Find corrupted Status rows
mask = (
    df["Status"].notna() &
    ~df["Status"].isin(valid_status)
)

# Move corrupted Status text into Description
df.loc[mask, "Description"] = (
    df.loc[mask, "Description"].fillna("") + " " +
    df.loc[mask, "Status"]
).str.strip()

# Replace corrupted Status values with NaN
df.loc[mask, "Status"] = np.nan

df.loc[mask, ["Status", "Description"]]

,Status,Description
20,NaN,"Construction g+2 (3 flor )\n4 badroom \n2 kitchen \nProperty highlights \nEast facing, 3 side open property, vetrified flooring, \nOnly 2 years,\n24 hour water and electricity \nB.U permission approved \n12 meter road\nFully furnished \n4 a.C\nSolar system"
90,NaN,"Construction g+2 (3 flor )\n4 badroom \n2 kitchen \nProperty highlights \nEast facing, 3 side open property, vetrified flooring, \nOnly 2 years,\n24 hour water and electricity \nB.U permission approved \n12 meter road\nFully furnished \n4 a.C\nSolar system"
148,NaN,"Construction g+2 (3 flor )\n4 badroom \n2 kitchen \nProperty highlights \nEast facing, 3 side open property, vetrified flooring, \nOnly 2 years,\n24 hour water and electricity \nB.U permission approved \n12 meter road\nFully furnished \n4 a.C\nSolar system"
388,NaN,"Situated on the 17th floor of a 34-Story high-Rise, this 2 bhk flat in shivalik skyview, gift city offers 1599.51 sq.Ft. Of under-Construction space. With 2 bedrooms and 2 bathrooms, it comes unfurnished and includes access to a gym, clubhouse, pool, and lift. Conveniently close to schools, airport, and shopping, available january 2027."
414,NaN,Independent/builder floor is available for sell.Construction ages only 5-10 years old propertysituated in kalol.Area of the construction is 145.00 sq. Yards(Builtup area) it has been unfurnished.It has good design of 2 bedrooms. Non-Stop water supply in 2 bathrooms .It has been priced at rs 2400000.Located on 2nd floor out of 5.
474,NaN,New under-Construction project in randheja
476,NaN,"Available from may 2028, this under-Construction 2 bhk flat at the rhythm elevate in karai, gandhinagar offers 155 sq.Ft. Of modern living space on the 5th floor of a 12-Story high-Rise. Featuring 2 bedrooms, 2 bathrooms, lift access, and a swimming pool, its close to koba circle metro, schools, nh 48, and esic hospital. Fully unfurnished for customization."
735,NaN,"Planning to purchase a plot in gandhinagar? This plot in palodia is situated in one of the excellent locations of the city. This 710 sq.Yards super built up area plot is your opportunity to build a exceptional residence. Construction on this property can be easily done upto 3 floors. Boundary wall is already constructed to separate the plot from nearby properties. Immediately, possession of pro..."
1017,NaN,"Constructed on a super built-Up area of 1503 sq. Ft., the flat comprises 2 bedrooms, 2 bathrooms, and 1 balcony. It is available on the 10th to 13th floors of a 13-Storey residential building. This under-Construction property will be ready for possession in approximately 2 months. The flat is designed to offer a modern lifestyle with amenities such as a fitness centre / gym, clubhouse, cctv sur..."
1205,NaN,"Located in vida by nila spaces, gift city, this under-Construction 1 bhk apartment spans 529 sq.Ft. On the 7th floor of a 33-Story high-Rise. Featuring 2 bathrooms, lift access, and amenities like a gym and pool, it offers modern living with excellent connectivity near pdpu metro and national highway 48. Available from june 2028, ideal for residential sale."
1292,NaN,"Available from march 2027, this under-Construction 4 bhk flat offers 4050 sq.Ft. On the 5th floor of an 18-Storey high-Rise at kumbh avyanna, koba, gandhinagar. Featuring 4 bedrooms and 4 bathrooms, the well-Planned layout suits residential needs. Close to healthcare facilities and pandit deendayal petroleum university, it combines comfort with convenience."
1314,NaN,"Available by 2027, this under-Construction 2 bhk flat in shilp north sky, gift city offers 1430 sq.Ft. Of living space on the 8th floor of a 25-Story high-Rise. The residence includes 2 bedrooms and 2 bathrooms, is semi-Furnished, and features amenities like a clubhouse, swimming pool, lift, and power backup. Close to schools, malls, and nh 48 connectivity."
1353,NaN,"Plot for sale in vavol is available in gandhinagar. This locality resonates with your modern lifestyle. It's a 1048 sq.Yards super built up area property. Construction on this property can be easily done upto 6 floors. Immediately, possession of property can be transferred. The owner of the property has freehold entitlement over the land. The asking price is only 5.34 crore. The plot location i..."
1380,NaN,"Spacious, ready to build plot in vavol, gandhinagar. It spans over spectacular 165 sq.Yards super built up area. Construction on this property can be easily done upto 4 floors. Immediately, possession of property can be transferred. The property is owned under freehold contract. The plot is available at a price of 1.16 crore."
1519,NaN,"Available from march 2027, this under-Construction 3 bhk flat on the 5th floor of a 13-Story high-Rise at shreeji sarvopari, sargasan, gandhinagar offers 1845 sq.Ft. Of well-Designed space. Featuring 3 bedrooms and 2 bathrooms, this residential apartment is close to key religious sites and sanjivani heart and medical hospital, blending convenience with comfort."
1521,NaN,"This 2 bhk flat, located on the 8th floor of a 34-Story high-Rise at shivalik skyview, gift city, gandhinagar, offers 1505.86 sq.Ft. Of under-Construction living space. Ready by dec 2027, it features 2 bedrooms, 2 bathrooms, and comes with key amenities like a clubhouse, gym, lift, and pool. Nearby are shree rang mall, nh48, and top schools."
1523,NaN,"Located on the 19th floor of a high-Rise at vida by nila spaces, this under-Construction 2 bhk apartment in gift city offers 871 sq.Ft. Of well-Planned living space. Available within six months, it comes unfurnished with 2 bathrooms, lift access, power backup, and amenities like a gym and swimming pool. Conveniently close to pdpu metro and major schools."
1536,NaN,"Available within 6 months, this 2 bhk flat in vida by nila spaces, gift city, gandhinagar spans 871 sq.Ft. Located on the 24th floor of a 33-Story high-Rise, the under-Construction apartment features 2 bedrooms and 2 bathrooms. Residents enjoy amenities like a gym, swimming pool, lift, and power backup, with excellent connectivity near pdpu metro and national highway 48."

In [672]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1880 entries, 0 to 1883
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Name                  1880 non-null   object
 1   BHK                   1730 non-null   object
 2   Location              1880 non-null   object
 3   Price (INR in Lakhs)  1880 non-null   float64
 4   Price_per_sqft        1874 non-null   float64
 5   Area_sqft             1880 non-null   float64
 6   Area_type             1448 non-null   object
 7   Status                1862 non-null   object
 8   Description           1880 non-null   object
 9   Property_URL          1880 non-null   object
 10  Image_URL             1880 non-null   object
dtypes: float64(3), object(8)
memory usage: 240.8+ KB

In [673]:
df['Property_URL'].value_counts()

Property_URL
https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-sargasan-gandhinagar-1584-sqft-spid-N90936662                                                        5
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-madhav-shivanjali-imperia-sargasan-gandhinagar-2358-sqft-spid-T91092592                              5
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-vinayak-courtyard-raysan-gandhinagar-2520-sqft-spid-R90624454                                        5
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-shreenath-homes-kudasan-gandhinagar-1845-sqft-spid-D90690758                                         5
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-kudasan-gandhinagar-1260-sqft-spid-T88713296                                                         5
https://www.99acres.com/3-bhk-bedroom-independent-house-villa-for-sale-in-sector-29-gandhinagar-5040-sqft-spid-P89741616                                              5
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-shukan-silver-urjanagar-1-gandhinagar-1665-sqft-r1-spid-Y86656544                                    5
https://www.99acres.com/5-bhk-bedroom-independent-house-villa-for-sale-in-koba-gandhinagar-2880-sqft-spid-S90507082                                                   5
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-the-skylark-randesan-gandhinagar-1998-sqft-spid-Q90281740                                            5
https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-shukan-silver-urjanagar-1-gandhinagar-852-sqft-spid-U90757956                                        5
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-ayunam-greens-kudasan-gandhinagar-1791-sqft-spid-S88739522                                           5
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-vinayak-sapphire-sargasan-gandhinagar-2313-sqft-spid-J89832344                                       5
https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-shree-ugati-heights-kudasan-gandhinagar-1305-sqft-spid-I90153374                                     5
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-the-grasslands-kudasan-gandhinagar-2880-sqft-spid-O90302400                                          5
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-kudasan-gandhinagar-1773-sqft-r1-spid-D88681112                                                      5
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-shivalay-parisar-kudasan-gandhinagar-2637-sqft-spid-P90540222                                        5
https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-kudasan-gandhinagar-828-sqft-r1-spid-C88635650                                                       5
https://www.99acres.com/5-bhk-bedroom-independent-house-villa-for-sale-in-kudasan-gandhinagar-1773-sq-ft-spid-S88763940                                               5
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-shubhaarambh-shilp-serenity-sargasan-gandhinagar-236-sqft-spid-C89715960                             5
https://www.99acres.com/4-bhk-bedroom-apartment-flat-for-sale-in-siddhraj-z-plus-sargasan-gandhinagar-2800-sqft-spid-D89554432                                        5
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-shreeji-sahajanand-shayona-sargasan-gandhinagar-792-sqft-spid-G88471194                              5
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-saamarth-h7-raysan-gandhinagar-1574-sqft-spid-T90805510                                              5
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-hari-aalayam-sargasan-gandhinagar-2142-sqft-spid-H90662904                                           5
https://www.99acres.com/4-bhk-bedroom-apartment-flat-for-sale-in-as-asteria-koba-gandhinagar-4410-sqft-r3-spid-A82608346                                              5
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-as-asteria-koba-gandhinagar-2263-sqft-spid-B90624586                                                 5
https://www.99acres.com/6-bhk-bedroom-independent-house-villa-for-sale-in-palodia-ahmedabad-west-5931-sqft-spid-V88747806                                             4
https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-shree-ugati-heights-kudasan-gandhinagar-930-sqft-spid-D89937030                                      4
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-kudasan-gandhinagar-2070-sqft-spid-G90293054                                                         4
https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-shree-rang-pearl-by-kaavyaratna-group-gift-city-gandhinagar-1449-sqft-spid-U90885608                 4
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-randesan-gandhinagar-1935-sqft-spid-B89741302                                                        4
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-shivalay-parisar-kudasan-gandhinagar-3230-sqft-spid-T88403926                                        4
https://www.99acres.com/residential-land-plot-for-sale-in-palodia-ahmedabad-west-584-sqyd-r4-spid-M82947958                                                           4
https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-sahjanand-city-kudasan-gandhinagar-147-sqft-spid-F90968710                                           4
https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-kudasan-gandhinagar-2232-sqft-spid-F90210510                                                         4
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-shivalay-sharnam-kudasan-gandhinagar-2835-sqft-spid-N90783482                                        4
https://www.99acres.com/3-bhk-bedroom-independent-house-villa-for-sale-in-raysan-gandhinagar-1800-sqft-spid-O90920016                                                 4
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-mahalaxmi-royal-palace-kudasan-gandhinagar-2250-sqft-spid-G90879552                                  4
https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-uma-mahalaxmi-4-kudasan-gandhinagar-1350-sqft-r1-spid-X88640570                                      4
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-shivalay-parisar-kudasan-gandhinagar-2637-sqft-spid-T90543098                                        4
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-saamarth-heaven-5-koba-gandhinagar-2250-sqft-spid-J90922894                                          4
https://www.99acres.com/5-bhk-bedroom-independent-house-villa-for-sale-in-pethapur-gandhinagar-2043-sqft-spid-A90784234                                               4
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-sargasan-gandhinagar-2466-sqft-r1-spid-Y88733324                                                     4
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-kudasan-gandhinagar-1980-sqft-r1-spid-W88630582                                                      4
https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-vavol-gandhinagar-1089-sqft-spid-M90644556                                                           4
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-satvan-bellevue-raysan-gandhinagar-2277-sqft-spid-I90702252                                          4
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-shreedhar-bhakti-kudasan-gandhinagar-1090-sqft-spid-J90664988                                        4
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-md-maruti-magnum-randesan-gandhinagar-1710-sqft-spid-T90306894                                       4
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-sthapan-apartments-sargasan-gandhinagar-1845-sqft-spid-M90541100                                     4
https://www.99acres.com/residential-land-plot-for-sale-in-palodia-ahmedabad-west-585-sqyd-r8-spid-R76241875                                                           4
https://www.99acres.com/4-bhk-bedroom-apartment-flat-for-sale-in-maruti-skyra-koba-gandhinagar-3870-sqft-spid-T88688802                                               3
https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-shivalik-skyview-gift-city-gandhinagar-1582-sqft-spid-K90727598                                      3
https://www.99acres.com/2-bhk-bedroom-independent-builder-floor-for-sale-in-psy-pramukh-lotus-sargasan-gandhinagar-1242-sqft-spid-R80413281                           3
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-bansal-shiva-blessing-1-sargasan-gandhinagar-1529-sqft-spid-J91125540                                3
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-akshat-heaven-kudasan-gandhinagar-2016-sq-ft-spid-Y90483186                                          3
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-shree-rang-pearl-by-kaavyaratna-group-gift-city-gandhinagar-2088-sqft-spid-J89986800                 3
https://www.99acres.com/residential-land-plot-for-sale-in-sanavad-ahmedabad-east-3000-sqyd-spid-Z90127116                                                             3
https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-radhe-vrundavan-residency-vavol-gandhinagar-1107-sqft-r2-spid-L76565921                              3
https://www.99acres.com/4-bhk-bedroom-independent-house-villa-for-sale-in-sector-3c-gandhinagar-972-sqft-spid-K90465736                                               3
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-radhe-imperial-sky-raysan-gandhinagar-1908-sqft-spid-R89058182                                       2
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-raysan-gandhinagar-2205-sqft-spid-R90201698                                                          2
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-divyajivan-aura-urjanagar-1-gandhinagar-1755-sqft-spid-F91063942                                     2
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-bliss-bansari-opulence-koba-gandhinagar-2475-sqft-spid-W88788888                                     2
https://www.99acres.com/residential-land-plot-for-sale-in-dhegam-gandhinagar-4600-sqyd-r1-spid-Z88808336                                                              2
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-shubhaarambh-shilp-serenity-sargasan-gandhinagar-2124-sqft-r1-spid-J86783686                         2
https://www.99acres.com/4-bhk-bedroom-apartment-flat-for-sale-in-shlokam-sharnam-sargasan-gandhinagar-3690-sqft-spid-V91094614                                        2
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-psy-pramukh-signature-kudasan-gandhinagar-980-sqft-spid-G91130676                                    2
https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-sre-luvkush-4-raysan-gandhinagar-1422-sqft-spid-V88148666                                            2
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-silicone-hills-koba-gandhinagar-2016-sqft-spid-B90874768                                             2
https://www.99acres.com/4-bhk-bedroom-apartment-flat-for-sale-in-koba-gandhinagar-438-sq-ft-spid-I89042256                                                            2
https://www.99acres.com/studio-apartment-flat-for-sale-in-vida-by-nila-spaces-gift-city-gandhinagar-483-sqft-spid-C89513918                                           2
https://www.99acres.com/3-bhk-bedroom-independent-builder-floor-for-sale-in-gift-city-gandhinagar-2300-sqft-spid-N83780390                                            1
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-bansari-greencity-gandhinagar-2025-sqft-spid-L83616222                                               1
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-labh-vardhan-kudasan-gandhinagar-1845-sqft-spid-F89005038                                            1
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-keshav-aaradhyam-kudasan-gandhinagar-2448-sqft-spid-Y90293180                                        1
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-shree-krishna-sunshine-heights-2-kudasan-gandhinagar-1782-sqft-spid-H90362248                        1
https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-sargasan-gandhinagar-1323-sqft-spid-V90790072                                                        1
https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-sobha-dream-heights-gift-city-gandhinagar-1095-sqft-spid-X89338527                                   1
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-randesan-gandhinagar-2250-sqft-r1-spid-W87877566                                                     1
https://www.99acres.com/4-bhk-bedroom-independent-house-villa-for-sale-in-vavol-gandhinagar-2322-sq-ft-spid-S90749582                                                 1
https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-randheja-gandhinagar-1485-sqft-spid-D90532266                                                        1
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-raysan-gandhinagar-1447-sqft-spid-W88740598                                                          1
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-shukan-heights-kudasan-gandhinagar-1800-sqft-spid-F89488294                                          1
https://www.99acres.com/residential-land-plot-for-sale-in-santej-ahmedabad-north-1000-sqyd-spid-W89399779                                                             1
https://www.99acres.com/4-bhk-bedroom-independent-house-villa-for-sale-in-waterstone-devshrut-villa-koba-gandhinagar-2970-sqft-spid-M90894056                         1
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-shubh-saral-heights-kudasan-gandhinagar-1215-sqft-spid-D88738332                                     1
https://www.99acres.com/5-bhk-bedroom-independent-house-villa-for-sale-in-dhegam-gandhinagar-1818-sqft-spid-E89637544                                                 1
https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-sargasan-gandhinagar-1440-sqft-spid-N90274910                                                        1
https://www.99acres.com/5-bhk-bedroom-independent-house-villa-for-sale-in-raysan-gandhinagar-3312-sqft-spid-R91268984                                                 1
https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-sargasan-gandhinagar-708-sqft-spid-I90723234                                                         1
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-polaris-elina-randheja-gandhinagar-1485-sqft-spid-N90789842                                          1
https://www.99acres.com/5-bhk-bedroom-independent-house-villa-for-sale-in-vrundavan-homes-raysan-gandhinagar-1890-sqft-spid-G90814508                                 1
https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-sargasan-gandhinagar-1323-sqft-spid-T90900470                                                        1
https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-akshat-heaven-kudasan-gandhinagar-1323-sqft-spid-N90262770                                           1
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-sargasan-gandhinagar-2079-sqft-spid-I90849536                                                        1
https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-swagat-flamingo-sargasan-gandhinagar-1323-sqft-spid-X90161122                                        1
https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-sargasan-gandhinagar-765-sqft-spid-W88757798                                                         1
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-sargasan-gandhinagar-1512-sqft-spid-P90658918                                                        1
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-royal-riviera-randesan-gandhinagar-2160-sqft-spid-L90080230                                          1
https://www.99acres.com/4-bhk-bedroom-apartment-flat-for-sale-in-megh-malhar-uvarsad-gandhinagar-3450-sqft-spid-C90013134                                             1
https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-sahjanand-city-kudasan-gandhinagar-1008-sqft-spid-N89861700                                          1
https://www.99acres.com/4-bhk-bedroom-independent-house-villa-for-sale-in-parijat-homes-sargasan-gandhinagar-243-sqft-spid-Q90439888                                  1
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-randesan-gandhinagar-1800-sq-ft-spid-Y88771834                                                       1
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-sargasan-gandhinagar-3879-sqft-spid-K90327396                                                        1
https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-shivansh-108-koba-gandhinagar-1453-sqft-spid-C89637388                                               1
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-sargasan-gandhinagar-1890-sqft-spid-L88817066                                                        1
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-hrudhya-sargasan-gandhinagar-2610-sqft-spid-U89269473                                                1
https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-swagat-kingsland-sargasan-gandhinagar-1530-sqft-spid-I90027828                                       1
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-hari-aalayam-sargasan-gandhinagar-2277-sqft-spid-M88578602                                           1
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-arpan-antilia-vavol-gandhinagar-1935-sqft-spid-U88946830                                             1
https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-garuda-tulsi-heights-kudasan-gandhinagar-1449-sqft-spid-X90021994                                    1
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-raysan-gandhinagar-2142-sqft-r1-spid-B88208506                                                       1
https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-s-sopan-2-kalol-gandhinagar-1050-sqft-spid-C89734588                                                 1
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-sun-spacelink-koba-gandhinagar-2862-sqft-r1-spid-O88630232                                           1
https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-sai-residency-chiloda-gandhinagar-1368-sqft-spid-A90534066                                           1
https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-sargasan-gandhinagar-2196-sqft-spid-I88591590                                                        1
https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-kudasan-gandhinagar-1134-sqft-r1-spid-A88683310                                                      1
https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-kudasan-gandhinagar-1305-sqft-spid-J90156618                                                         1
https://www.99acres.com/2-bhk-bedroom-apartment-flat-for-sale-in-snkj-siddharth-residency-vavol-gandhinagar-1125-sqft-spid-X90518264                                  1

In [674]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1880 entries, 0 to 1883
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Name                  1880 non-null   object
 1   BHK                   1730 non-null   object
 2   Location              1880 non-null   object
 3   Price (INR in Lakhs)  1880 non-null   float64
 4   Price_per_sqft        1874 non-null   float64
 5   Area_sqft             1880 non-null   float64
 6   Area_type             1448 non-null   object
 7   Status                1862 non-null   object
 8   Description           1880 non-null   object
 9   Property_URL          1880 non-null   object
 10  Image_URL             1880 non-null   object
dtypes: float64(3), object(8)
memory usage: 240.8+ KB

In [675]:
df['Image_URL'].value_counts()

Image_URL
https://static.99acres.com/universalapp/img/downArrowNew.png     1111
https://static.99acres.com/universalapp/img/checkLineGray.svg     731
https://static.99acres.com/universalapp/img/StarNew.png            38
Name: count, dtype: int64

Image_URL column is removed because it mainly contains website UI icons and non-property images, which are not useful for analysis or modeling.

In [676]:
df.drop(columns=["Image_URL"], inplace=True)

In [677]:
# df.sample(5)
# df.head()

# Feature Engineering

 We can see that Description column contains a lot of unique values because it is a combination of multiple text fields. AS there are not common pattern so Regex or any other method cannot be applied to extract specific information from Description column. 

 So i decided to use baseclass schema and LLM to extract specific information from Description column and create new columns for that information. This will help in better analysis and modeling.

In [678]:
!pip install groq

Requirement already satisfied: groq in C:\Users\MEGH BAVARVA\AppData\Local\Programs\Python\Python313\Lib\site-packages (0.37.1)
Requirement already satisfied: anyio<5,>=3.5.0 in C:\Users\MEGH BAVARVA\AppData\Local\Programs\Python\Python313\Lib\site-packages (from groq) (4.8.0)
Requirement already satisfied: distro<2,>=1.7.0 in C:\Users\MEGH BAVARVA\AppData\Local\Programs\Python\Python313\Lib\site-packages (from groq) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in C:\Users\MEGH BAVARVA\AppData\Local\Programs\Python\Python313\Lib\site-packages (from groq) (0.28.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in C:\Users\MEGH BAVARVA\AppData\Local\Programs\Python\Python313\Lib\site-packages (from groq) (2.11.7)
Requirement already satisfied: sniffio in C:\Users\MEGH BAVARVA\AppData\Local\Programs\Python\Python313\Lib\site-packages (from groq) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.10 in C:\Users\MEGH BAVARVA\AppData\Local\Programs\Python\Python313\Lib\site-packages (from groq) (4.15.0)
Requirement already satisfied: idna>=2.8 in C:\Users\MEGH BAVARVA\AppData\Local\Programs\Python\Python313\Lib\site-packages (from anyio<5,>=3.5.0->groq) (3.10)
Requirement already satisfied: certifi in C:\Users\MEGH BAVARVA\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpx<1,>=0.23.0->groq) (2025.8.3)
Requirement already satisfied: httpcore==1.* in C:\Users\MEGH BAVARVA\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpx<1,>=0.23.0->groq) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in C:\Users\MEGH BAVARVA\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq) (0.14.0)
Requirement already satisfied: annotated-types>=0.6.0 in C:\Users\MEGH BAVARVA\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pydantic<3,>=1.9.0->groq) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in C:\Users\MEGH BAVARVA\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pydantic<3,>=1.9.0->groq) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in C:\Users\MEGH BAVARVA\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pydantic<3,>=1.9.0->groq) (0.4.1)

WARNING: Ignoring invalid distribution ~andas (C:\Users\MEGH BAVARVA\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~andas (C:\Users\MEGH BAVARVA\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~andas (C:\Users\MEGH BAVARVA\AppData\Local\Programs\Python\Python313\Lib\site-packages)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [679]:
from groq import Groq
from pydantic import BaseModel, Field, field_validator
from typing import List, Optional
import json
from dotenv import load_dotenv
import os

# Load .env file
load_dotenv()

# Read API key from .env
groq_api_key = os.getenv("GROQ_API_KEY")

# Create Groq client
client = Groq(api_key=groq_api_key)


# Pydantic Schema
class PropertyDetails(BaseModel):

    # Basic Property Info
    bedrooms: Optional[int] = None
    bathrooms: Optional[int] = None
    balconies: Optional[int] = None

    # Area / Floor
    current_floor: Optional[str] = None
    total_floors: Optional[int] = None
    total_floors_house: Optional[int] = None

    # Property Characteristics
    facing: Optional[str] = None
    furnishing_status: Optional[str] = None
    property_type: Optional[str] = None

    # Combined Lists - allow optional strings and filter None values
    age_possession: List[Optional[str]] = Field(default_factory=list)
    amenities: List[Optional[str]] = Field(default_factory=list)
    additional_rooms: List[Optional[str]] = Field(default_factory=list)
    nearby: List[Optional[str]] = Field(default_factory=list)
    additional_insights: List[Optional[str]] = Field(default_factory=list)

    @field_validator('age_possession', 'amenities', 'additional_rooms', 'nearby', 'additional_insights', mode='before')
    @classmethod
    def filter_none_values(cls, v):
        """Remove None values from lists"""
        if isinstance(v, list):
            return [item for item in v if item is not None]
        return v


# LLM Extraction Function
def extract_with_llm(description):

    prompt = f"""
    You are an expert real estate information extraction system.

    Extract structured property details from the property description.

    Rules:
    - Return ONLY valid JSON.
    - Missing values should be null.
    - Lists must always return arrays [] even if empty.
    - Normalize values wherever possible.

    Fields to extract:

    1. bedrooms -> integer
    2. bathrooms -> integer
    3. balconies -> integer

    4. current_floor -> string
    5. total_floors -> integer
    6. total_floors_house -> integer

    7. facing -> string
    8. furnishing_status -> furnished / semi-furnished / unfurnished
    9. property_type -> apartment / villa / bungalow / penthouse / etc.

    10. age_possession -> list containing:
        - property age
        - possession details
        Example:
        ["0-1 year old", "ready to move"]

    11. amenities -> list containing amenities like:
        - lift
        - garden
        - parking
        - clubhouse
        - swimming pool
        - gym
        - security
        - power backup
        etc.

    12. additional_rooms -> list containing:
        - pooja room
        - servant room
        - study room
        - store room
        - terrace
        - utility room
        etc.

    13. nearby -> list containing nearby landmarks:
        - school
        - hospital
        - metro
        - mall
        - highway
        etc.

    14. additional_insights -> list containing:
        - vastu compliant
        - corner property
        - luxury property
        - road facing
        - garden facing
        - park facing
        etc.

    Property Description:
    \"\"\"{description}\"\"\"
    """

    response = client.chat.completions.create(

        # model of LLM to use for extraction
        model="llama-3.1-8b-instant",

        messages=[
            {
                "role": "system",
                "content": "You are a highly accurate real estate data extraction engine."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],

        response_format={"type": "json_object"},
        temperature=0

    )

    extracted_json = json.loads(
        response.choices[0].message.content
    )

    # Validate output
    validated_output = PropertyDetails(**extracted_json)

    return validated_output

In [680]:
# test the function with a sample description

description = """
Luxury 3 BHK semi-furnished apartment with 2 bathrooms and 3 balconies.
Includes lift, clubhouse, swimming pool, gym, and security.
East facing and vastu compliant.
Ready to move property near metro station and hospital.
"""

result = extract_with_llm(description)

print(result.model_dump())

{'bedrooms': 3, 'bathrooms': 2, 'balconies': 3, 'current_floor': None, 'total_floors': None, 'total_floors_house': None, 'facing': 'East', 'furnishing_status': 'semi-furnished', 'property_type': 'apartment', 'age_possession': ['0-1 year old', 'ready to move'], 'amenities': ['lift', 'clubhouse', 'swimming pool', 'gym', 'security'], 'additional_rooms': [], 'nearby': ['metro station', 'hospital'], 'additional_insights': ['vastu compliant']}

In [ ]:
# Apply LLM Extraction to All Descriptions

# Initialize new columns for extracted features (if not already done)
if 'bedrooms' not in df.columns:
    df['bedrooms'] = None
    df['bathrooms'] = None
    df['balconies'] = None
    df['current_floor'] = None
    df['total_floors'] = None
    df['total_floors_house'] = None
    df['facing'] = None
    df['furnishing_status'] = None
    df['property_type'] = None
    df['age_possession'] = None
    df['amenities'] = None
    df['additional_rooms'] = None
    df['nearby'] = None
    df['additional_insights'] = None


success_count = 0
error_count = 0
skip_count = 0
start_row = 0

print(f"Starting extraction from row {start_row}")
print(f"Total rows: {len(df) - start_row}")

for idx in range(start_row, len(df)):

    description = df.at[idx, 'Description']

    # Skip empty descriptions
    if pd.isna(description) or str(description).strip() == "":

        skip_count += 1

        print(f"Row {idx} → SKIPPED")

        continue

    try:

        result = extract_with_llm(description)

        # Store extracted features
        df.at[idx, 'bedrooms'] = result.bedrooms
        df.at[idx, 'bathrooms'] = result.bathrooms
        df.at[idx, 'balconies'] = result.balconies
        df.at[idx, 'current_floor'] = result.current_floor
        df.at[idx, 'total_floors'] = result.total_floors
        df.at[idx, 'total_floors_house'] = result.total_floors_house
        df.at[idx, 'facing'] = result.facing
        df.at[idx, 'furnishing_status'] = result.furnishing_status
        df.at[idx, 'property_type'] = result.property_type
        df.at[idx, 'age_possession'] = result.age_possession
        df.at[idx, 'amenities'] = result.amenities
        df.at[idx, 'additional_rooms'] = result.additional_rooms
        df.at[idx, 'nearby'] = result.nearby
        df.at[idx, 'additional_insights'] = result.additional_insights

        success_count += 1

        print(f"Row {idx} → SUCCESS")

    except Exception as e:

        error_count += 1

        print(f"Row {idx} → ERROR : {str(e)}")

        continue


# FINAL SUMMARY
print("\n================ FINAL REPORT ================")

print(f"Total Rows       : {len(df) - start_row}")
print(f"Successful Rows  : {success_count}")
print(f"Error Rows       : {error_count}")
print(f"Skipped Rows     : {skip_count}")

print("=============================================")

In [ ]:
# Fill missing bedrooms using BHK column

mask = df["bedrooms"].isna() & df["BHK"].notna()

df.loc[mask, "bedrooms"] = (
    df.loc[mask, "BHK"]
    .str.extract(r"(\d+)")[0]
    .astype(float)
)

In [ ]:
df.info()

In [ ]:
# Create mapping dictionary
location_mapping = {
    "Sargasan, Gandhinagar": "Sargasan",
    "Kudasan, Gandhinagar": "Kudasan",
    "Gift City, Gandhinagar": "Gift City",
    "Raysan, Gandhinagar": "Raysan",
    "Vavol, Gandhinagar": "Vavol",
    "Koba, Gandhinagar": "Koba",
    "Randesan, Gandhinagar": "Randesan",
    "Kalol, Gandhinagar": "Kalol",
    "Pethapur, Gandhinagar": "Pethapur",
    "Randheja, Gandhinagar": "Randheja",
    "Palodia, Gandhinagar": "Palodia",
    "Urjanagar 1, Randesan, Gandhinagar": "Randesan",
    "Dahegam, Gandhinagar": "Dahegam",
    "Uvarsad, Gandhinagar": "Uvarsad",
    "Khoraj, Gandhinagar": "Khoraj",
    "Chiloda, Gandhinagar": "Chiloda",
    "Sector 29, Gandhinagar": "Sector 29",
    "Alampur, Gandhinagar": "Alampur",
    "Sardar Patel Ring Road, Gandhinagar": "SP Ring Road",
    "Sector 26, Gandhinagar": "Sector 26",
    "Panchvati, Kalol, Gandhinagar": "Kalol",
    "Sector 22, Gandhinagar": "Sector 22",
    "Kolavada, Gandhinagar": "Kolavada",
    "Mansa, Gandhinagar": "Mansa",
    "OrigHeights": "Sargasan",
    "Ambapur, Gandhinagar": "Ambapur",
    "Rakanpur, Gandhinagar": "Kalol",
    "Palaj, Gandhinagar": "Gandhinagar Taluka",
    "Mahudi, Gandhinagar": "Mansa",
    "Khatraj, Gandhinagar": "Kalol",
    "Vasana Hadmatia, Sargasan": "Sargasan",
    "Karai, Gandhinagar": "Karai",
    "Sector 25, Gandhinagar": "Sector 25",
    "Sector 3C Gandhinagar, SG Highway": "Sector 3",
    "Swagat RaForest 2": "Kudasan",
    "Adalaj, Gandhinagar": "Adalaj",
    "Grambharti, Gandhinagar": "Mansa",
    "Sector 8B Gandhinagar, Sector 8 Gandhinagar": "Sector 8",
    "Ambika Nagar, Kalol, Gandhinagar": "Kalol",
    "Nabhoi, Gandhinagar": "Nabhoi",
    "Sanavad, Gandhinagar": "Kalol",
    "Lodra, Gandhinagar": "Mansa",
    "Kalyanpura, Kalol, Gandhinagar": "Kalol",
    "Valad, Gandhinagar": "Valad",
    "Sector 4A Gandhinagar, Sector 4 Gandhinagar": "Sector 4",
    "Por, Gandhinagar": "Gandhinagar Taluka",
    "Unali, Gandhinagar": "Kalol",
    "Nandoli, Gandhinagar": "Kalol",
    "Vardhaman Nagar, Kalol, Gandhinagar": "Kalol",
    "Urjanagar, Randesan, Gandhinagar": "Randesan",
    "Vayana, Kalol, Gandhinagar": "Kalol",
    "Akshar Villa Bunglows, Gandhinagar": "Vavol",
    "Pratap Pura, Kalol, Gandhinagar": "Kalol",
    "Sector 6, Gandhinagar": "Sector 6",
    "Green City, Sector 26 Gandhinagar": "Sector 26",
    "GIDC Chhatral, Gandhinagar": "Kalol",
    "Sector 28, Gandhinagar": "Sector 28",
    "adalaj, Gandhinagar": "Adalaj",
    "Shal4 Apartment": "Vavol",
    "Sector 8, Gandhinagar": "Sector 8",
    "Santej, Gandhinagar": "Kalol",
    "Dabhoda, Gandhinagar": "Dabhoda",
    "Sector 7 Gandhinagar": "Sector 7",
    "SG Highway, Gandhinagar": "SG Highway",
    "Chhatral, Gandhinagar": "Kalol",
    "Natraj TwBunglows": "Dahegam",
    "Lavarpur, Gandhinagar": "Gandhinagar Taluka",
    "Sector 21, Gandhinagar": "Sector 21",
    "Zundal, Gandhinagar": "SP Ring Road",
    "Dhamasana, Gandhinagar": "Kalol",
    "Bhaijipura, Gandhinagar": "Gandhinagar Taluka",
    "VAISHNODEVI TEMPLE, GANDHINAGAR": "SG Highway",
    "Sector 23 Gandhinagar, Sector 16 Gandhinagar": "Sector 16",
    "Jethalaj, Gandhinagar": "Kalol",
    "Borishana, Gandhinagar": "Kalol",
    "Juna chora, Gandhinagar": "Kalol",
    "Sector 2B Gandhinagar, SG Highway": "Sector 2",
    "Sector 5A Gandhinagar, Sector 5 Gandhinagar": "Sector 5",
    "KAMAREDDY, Gandhinagar": "Other",
    "Dashela, Gandhinagar": "Gandhinagar Taluka",
    "Adraj Moti, Gandhinagar": "Gandhinagar Taluka",
    "Sector 11, Gandhinagar": "Sector 11",
    "Sughad, Gandhinagar": "Sughad",
    "GIDC, Dahegam, Gandhinagar": "Dahegam",
    "Shree Residency, Gandhinagar": "Sargasan",
    "Kaavyaratna BougaVille": "Gift City",
    "ADALAJ, Gandhinagar": "Adalaj",
    "Sanoda, Gandhinagar": "Dahegam",
    "at Gandhinagar": "Gandhinagar Taluka",
    "Shreeji Bungalows, Gandhinagar": "Sargasan",
    "sargasan Tp 9, Gandhinagar": "Sargasan",
    "Swagat RaForest 4": "Sargasan",
    "Moti Bhoyan, Gandhinagar": "Kalol",
    "Dholera, Gandhinagar": "Outside Gandhinagar",
    "Adhana, Gandhinagar": "Kalol",
    "Vansajda, Gandhinagar": "Kalol",
    "Rancharda, Gandhinagar": "Kalol",
    "Sonarda, Gandhinagar": "Gandhinagar Taluka",
    "On Request, Gandhinagar": "Other",
    "Shal6": "Vavol",
    "Bardoli, Gandhinagar": "Dahegam",
    "Sector 5, Gandhinagar": "Sector 5",
    "Aluva, Gandhinagar": "Kalol",
    "Sector 4B Gandhinagar, Sector 4 Gandhinagar": "Sector 4",
    "Indroda, Gandhinagar": "Gandhinagar Taluka",
    "OrigParrk": "Sargasan",
    "urjanagar 2,plot number 18, Gandhinagar": "Randesan",
    "Sector 3 Gandhinagar , SG Highway": "Sector 3",
    "Sector 19, Gandhinagar": "Sector 19",
    "PLOT NO-1398/1,SECTOR NO-2/B,GANDHINAGAR": "Sector 2",
    "Sector 1 Gandhinagar, SG Highway": "Sector 1",
    "Amarapur, Gandhinagar": "Mansa",
    "Sector 30, Gandhinagar": "Sector 30",
    "Sector 4, Gandhinagar": "Sector 4",
    "Sector 4D Gandhinagar, Sector 4 Gandhinagar": "Sector 4",
    "Plot No 672,, Gandhinagar": "Sector 22",
    "Street No. 1, VV Giri Nagar, Gandhi Nagar, Kavadiguda, Gandhinagar": "Other",
    "Magodi, Gandhinagar": "Gandhinagar Taluka",
    "Ratanpur, Gandhinagar": "Gandhinagar Taluka",
    "Infocity, SG Highway": "SG Highway",
    "Sector 24, Gandhinagar": "Sector 24",
    "Sector 27, Gandhinagar": "Sector 27",
    "Subhgriha Tata Housing, Gandhinagar": "Kalol",
    "Jamla village, Gandhinagar": "Kalol",
    "Villupuram, Gandhinagar": "Other",
    "Pundra, Gandhinagar": "Mansa",
    "hooda, Gandhinagar": "Mansa",
    "Dholakuva, Gandhinagar": "Mansa",
    "Lekawada, Gandhinagar": "Gandhinagar Taluka",
    "babul, Gandhinagar": "Sector 22",
    "Gandhinagar Randheja Highway": "Randheja"
}

# Create new mapped column
df["Mapped_Area"] = df["Location"].map(location_mapping)

# Check result
print(df[["Location", "Mapped_Area"]].head())

In [ ]:
# Step 1 : Fill bathrooms using regex from Description

import re

mask = df["bathrooms"].isna()

df.loc[mask, "bathrooms"] = (
    df.loc[mask, "Description"]
    .str.extract(
        r"(\d+)\s*(bathroom|bathrooms|washroom|washrooms)",
        flags=re.IGNORECASE
    )[0]
)

In [ ]:
# Bathroom per bedroom ratio by location based mapped area

ratio_df = (
    df.dropna(subset=["bedrooms", "bathrooms"])
      .groupby("Mapped_Area")[["bedrooms", "bathrooms"]]
      .median()
)

# Create ratio
ratio_df["ratio"] = (
    ratio_df["bathrooms"] / ratio_df["bedrooms"]
)

print(ratio_df.head())

In [ ]:
# Fill missing bathrooms using mapped area ratio

mask = (
    df["bathrooms"].isna() &
    df["bedrooms"].notna()
)

for idx in df[mask].index:

    mapped_area = df.loc[idx, "Mapped_Area"]
    bedrooms = df.loc[idx, "bedrooms"]

    # Convert to numeric safely
    bedrooms = float(bedrooms)

    if mapped_area in ratio_df.index:

        ratio = ratio_df.loc[mapped_area, "ratio"]

        estimated_bathrooms = round(bedrooms * ratio)

        # Minimum 1 bathroom
        estimated_bathrooms = max(1, estimated_bathrooms)

    else:
        # fallback heuristic
        estimated_bathrooms = max(1, round(bedrooms))

    df.loc[idx, "bathrooms"] = estimated_bathrooms

    print(
        f"Row {idx} | Area: {mapped_area} | "
        f"Bedrooms: {bedrooms} -> Estimated Bathrooms: {estimated_bathrooms}"
    )

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1880 entries, 0 to 1883
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Name                  1880 non-null   object
 1   BHK                   1730 non-null   object
 2   Location              1880 non-null   object
 3   Price (INR in Lakhs)  1880 non-null   float64
 4   Price_per_sqft        1874 non-null   float64
 5   Area_sqft             1880 non-null   float64
 6   Area_type             1448 non-null   object
 7   Status                1862 non-null   object
 8   Description           1880 non-null   object
 9   Property_URL          1880 non-null   object
 10  bedrooms              1737 non-null   object
 11  bathrooms             1737 non-null   object
 12  balconies             830 non-null    object
 13  current_floor         988 non-null    object
 14  total_floors          843 non-null    object
 15  total_floors_house    66 non-null     object
 16  facing                549 non-null    object
 17  furnishing_status     812 non-null    object
 18  property_type         1327 non-null   object
 19  age_possession        1695 non-null   object
 20  amenities             1695 non-null   object
 21  additional_rooms      1695 non-null   object
 22  nearby                1695 non-null   object
 23  additional_insights   1695 non-null   object
 24  Mapped_Area           1880 non-null   object
dtypes: float64(3), object(22)
memory usage: 446.4+ KB

In [ ]:
# balcony per bedroom ratio by location based mapped area

balcony_ratio_df = (
    df.dropna(subset=["bedrooms", "balconies"])
      .groupby("Mapped_Area")[["bedrooms", "balconies"]]
      .median()
)

balcony_ratio_df["ratio"] = (
    balcony_ratio_df["balconies"] /
    balcony_ratio_df["bedrooms"]
)

print(balcony_ratio_df.head())

                   bedrooms balconies     ratio
Mapped_Area
Adalaj                  3.0       3.0       1.0
Alampur                 3.0       2.5  0.833333
Chiloda                 2.0       2.0       1.0
Dahegam                 3.0       1.5       0.5
Gandhinagar Taluka      3.0       2.5  0.833333

In [ ]:
mask = (
    df["balconies"].isna() &
    df["bedrooms"].notna()
)

for idx in df[mask].index:

    mapped_area = df.loc[idx, "Mapped_Area"]
    bedrooms = float(df.loc[idx, "bedrooms"])

    if mapped_area in balcony_ratio_df.index:

        ratio = balcony_ratio_df.loc[mapped_area, "ratio"]

        estimated_balconies = math.ceil(
            bedrooms * ratio
        )

    else:
        # fallback heuristic
        estimated_balconies = max(1, bedrooms - 1)

    # Optional upper cap
    estimated_balconies = min(estimated_balconies, 5)

    df.loc[idx, "balconies"] = estimated_balconies

    print(
        f"Row {idx} | "
        f"Area: {mapped_area} | "
        f"Bedrooms: {bedrooms} -> "
        f"Estimated Balconies: {estimated_balconies}"
    )

Row 0 | Area: Sargasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 1 | Area: Pethapur | Bedrooms: 3.0 -> Estimated Balconies: 2
Row 4 | Area: Randesan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 5 | Area: Koba | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 12 | Area: Koba | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 15 | Area: Koba | Bedrooms: 4.0 -> Estimated Balconies: 2
Row 16 | Area: Gift City | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 17 | Area: Sargasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 19 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 20 | Area: Sector 3 | Bedrooms: 4.0 -> Estimated Balconies: 2
Row 21 | Area: Gift City | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 25 | Area: Kudasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 27 | Area: Gift City | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 30 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 35 | Area: Raysan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 37 | Area: Kudasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 42 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 47 | Area: Kudasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 48 | Area: Kudasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 49 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 52 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 56 | Area: Sargasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 60 | Area: Kudasan | Bedrooms: 5.0 -> Estimated Balconies: 2
Row 66 | Area: Koba | Bedrooms: 4.0 -> Estimated Balconies: 2
Row 67 | Area: Koba | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 68 | Area: Raysan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 71 | Area: Sector 29 | Bedrooms: 3.0 -> Estimated Balconies: 2.0
Row 74 | Area: Randesan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 75 | Area: Koba | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 82 | Area: Koba | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 85 | Area: Koba | Bedrooms: 4.0 -> Estimated Balconies: 2
Row 86 | Area: Gift City | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 87 | Area: Sargasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 89 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 90 | Area: Sector 3 | Bedrooms: 4.0 -> Estimated Balconies: 2
Row 91 | Area: Gift City | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 95 | Area: Kudasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 97 | Area: Gift City | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 100 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 105 | Area: Raysan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 107 | Area: Kudasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 112 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 117 | Area: Kudasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 118 | Area: Kudasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 119 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 122 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 126 | Area: Sargasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 130 | Area: Kudasan | Bedrooms: 5.0 -> Estimated Balconies: 2
Row 136 | Area: Koba | Bedrooms: 4.0 -> Estimated Balconies: 2
Row 137 | Area: Koba | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 138 | Area: Raysan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 141 | Area: Sector 29 | Bedrooms: 3.0 -> Estimated Balconies: 2.0
Row 143 | Area: Koba | Bedrooms: 4.0 -> Estimated Balconies: 2
Row 144 | Area: Gift City | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 145 | Area: Sargasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 147 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 148 | Area: Sector 3 | Bedrooms: 4.0 -> Estimated Balconies: 2
Row 149 | Area: Gift City | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 153 | Area: Kudasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 155 | Area: Gift City | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 158 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 163 | Area: Raysan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 165 | Area: Kudasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 170 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 175 | Area: Kudasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 176 | Area: Kudasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 177 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 180 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 184 | Area: Sargasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 188 | Area: Kudasan | Bedrooms: 5.0 -> Estimated Balconies: 2
Row 194 | Area: Koba | Bedrooms: 4.0 -> Estimated Balconies: 2
Row 195 | Area: Koba | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 196 | Area: Raysan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 199 | Area: Sector 29 | Bedrooms: 3.0 -> Estimated Balconies: 2.0
Row 202 | Area: Kudasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 204 | Area: Gift City | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 207 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 212 | Area: Raysan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 214 | Area: Kudasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 219 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 224 | Area: Kudasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 225 | Area: Kudasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 226 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 229 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 233 | Area: Sargasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 237 | Area: Kudasan | Bedrooms: 5.0 -> Estimated Balconies: 2
Row 243 | Area: Koba | Bedrooms: 4.0 -> Estimated Balconies: 2
Row 244 | Area: Koba | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 245 | Area: Raysan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 248 | Area: Sector 29 | Bedrooms: 3.0 -> Estimated Balconies: 2.0
Row 249 | Area: Kudasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 250 | Area: Kudasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 251 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 254 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 258 | Area: Sargasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 262 | Area: Kudasan | Bedrooms: 5.0 -> Estimated Balconies: 2
Row 268 | Area: Koba | Bedrooms: 4.0 -> Estimated Balconies: 2
Row 269 | Area: Koba | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 270 | Area: Raysan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 273 | Area: Sector 29 | Bedrooms: 3.0 -> Estimated Balconies: 2.0
Row 274 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 278 | Area: Gift City | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 280 | Area: Vavol | Bedrooms: 4.0 -> Estimated Balconies: 2
Row 283 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 285 | Area: Koba | Bedrooms: 4.0 -> Estimated Balconies: 2
Row 289 | Area: Raysan | Bedrooms: 5.0 -> Estimated Balconies: 2
Row 292 | Area: Raysan | Bedrooms: 0.0 -> Estimated Balconies: 0
Row 297 | Area: Sargasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 303 | Area: Randesan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 305 | Area: Koba | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 313 | Area: Kalol | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 314 | Area: Koba | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 320 | Area: Dahegam | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 321 | Area: Dahegam | Bedrooms: 0.0 -> Estimated Balconies: 0
Row 322 | Area: Koba | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 323 | Area: Mansa | Bedrooms: 3.0 -> Estimated Balconies: 2
Row 324 | Area: Sargasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 325 | Area: Randesan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 327 | Area: Sargasan | Bedrooms: 4.0 -> Estimated Balconies: 2
Row 328 | Area: Raysan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 330 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 332 | Area: Randesan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 333 | Area: Randheja | Bedrooms: 2.0 -> Estimated Balconies: 2
Row 334 | Area: Randheja | Bedrooms: 2.0 -> Estimated Balconies: 2
Row 335 | Area: Uvarsad | Bedrooms: 2.0 -> Estimated Balconies: 2
Row 336 | Area: Sargasan | Bedrooms: 4.0 -> Estimated Balconies: 2
Row 337 | Area: Kudasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 338 | Area: Sargasan | Bedrooms: 5.0 -> Estimated Balconies: 2
Row 339 | Area: Pethapur | Bedrooms: 3.0 -> Estimated Balconies: 2
Row 340 | Area: Sargasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 342 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 343 | Area: SP Ring Road | Bedrooms: 2.0 -> Estimated Balconies: 2
Row 344 | Area: Gift City | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 346 | Area: Gift City | Bedrooms: 1.0 -> Estimated Balconies: 1
Row 347 | Area: Sargasan | Bedrooms: 1.0 -> Estimated Balconies: 1
Row 348 | Area: Sargasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 349 | Area: Pethapur | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 351 | Area: Vavol | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 352 | Area: Sargasan | Bedrooms: 1.0 -> Estimated Balconies: 1
Row 355 | Area: Sargasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 356 | Area: Raysan | Bedrooms: 4.0 -> Estimated Balconies: 2
Row 357 | Area: Uvarsad | Bedrooms: 1.0 -> Estimated Balconies: 1
Row 358 | Area: Sargasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 359 | Area: Dahegam | Bedrooms: 4.0 -> Estimated Balconies: 2
Row 360 | Area: Randesan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 361 | Area: Randheja | Bedrooms: 3.0 -> Estimated Balconies: 3
Row 363 | Area: Kalol | Bedrooms: 6.0 -> Estimated Balconies: 3
Row 366 | Area: Sector 11 | Bedrooms: 3.0 -> Estimated Balconies: 2.0
Row 367 | Area: Vavol | Bedrooms: 1.0 -> Estimated Balconies: 1
Row 368 | Area: Koba | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 369 | Area: Sargasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 370 | Area: Pethapur | Bedrooms: 3.0 -> Estimated Balconies: 2
Row 371 | Area: Sughad | Bedrooms: 3.0 -> Estimated Balconies: 2.0
Row 372 | Area: Sargasan | Bedrooms: 6.0 -> Estimated Balconies: 2
Row 375 | Area: Gift City | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 376 | Area: Vavol | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 378 | Area: Sargasan | Bedrooms: 0.0 -> Estimated Balconies: 0
Row 379 | Area: Sargasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 380 | Area: Sector 8 | Bedrooms: 4.0 -> Estimated Balconies: 3.0
Row 382 | Area: Kudasan | Bedrooms: 4.0 -> Estimated Balconies: 2
Row 383 | Area: Koba | Bedrooms: 4.0 -> Estimated Balconies: 2
Row 384 | Area: Raysan | Bedrooms: 4.0 -> Estimated Balconies: 2
Row 388 | Area: Gift City | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 389 | Area: Kalol | Bedrooms: 5.0 -> Estimated Balconies: 3
Row 390 | Area: Karai | Bedrooms: 3.0 -> Estimated Balconies: 2.0
Row 393 | Area: Randesan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 394 | Area: Raysan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 395 | Area: Sargasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 396 | Area: Sargasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 397 | Area: Sargasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 398 | Area: Gift City | Bedrooms: 3.0 -> Estimated Balconies: 2
Row 399 | Area: Randesan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 401 | Area: Sargasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 402 | Area: Randesan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 403 | Area: Sargasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 404 | Area: Randesan | Bedrooms: 4.0 -> Estimated Balconies: 2
Row 406 | Area: Karai | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 407 | Area: Sargasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 408 | Area: Sargasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 409 | Area: Sargasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 410 | Area: Randesan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 411 | Area: Adalaj | Bedrooms: 1.0 -> Estimated Balconies: 1
Row 412 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 413 | Area: Randesan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 414 | Area: Kalol | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 416 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 417 | Area: Sargasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 418 | Area: Gift City | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 419 | Area: Pethapur | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 420 | Area: Vavol | Bedrooms: 3.0 -> Estimated Balconies: 2
Row 421 | Area: Sargasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 422 | Area: Vavol | Bedrooms: 1.0 -> Estimated Balconies: 1
Row 423 | Area: Dahegam | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 424 | Area: Dahegam | Bedrooms: 4.0 -> Estimated Balconies: 2
Row 425 | Area: Ambapur | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 428 | Area: Vavol | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 429 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 430 | Area: Gift City | Bedrooms: 1.0 -> Estimated Balconies: 1
Row 431 | Area: Koba | Bedrooms: 5.0 -> Estimated Balconies: 2
Row 434 | Area: Pethapur | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 437 | Area: Alampur | Bedrooms: 4.0 -> Estimated Balconies: 4
Row 440 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 441 | Area: Sargasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 442 | Area: Randesan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 444 | Area: Sector 5 | Bedrooms: 1.0 -> Estimated Balconies: 1
Row 445 | Area: Sargasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 446 | Area: Gift City | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 447 | Area: Sargasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 450 | Area: Vavol | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 451 | Area: Gift City | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 452 | Area: Chiloda | Bedrooms: 2.0 -> Estimated Balconies: 2
Row 453 | Area: Sargasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 455 | Area: Sargasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 456 | Area: Uvarsad | Bedrooms: 3.0 -> Estimated Balconies: 3
Row 457 | Area: Kalol | Bedrooms: 1.0 -> Estimated Balconies: 1
Row 458 | Area: Gift City | Bedrooms: 3.0 -> Estimated Balconies: 2
Row 459 | Area: Sargasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 460 | Area: Sargasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 461 | Area: Sargasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 463 | Area: Kudasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 466 | Area: Raysan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 467 | Area: Kudasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 468 | Area: Gift City | Bedrooms: 3.0 -> Estimated Balconies: 2
Row 469 | Area: Raysan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 470 | Area: Sargasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 471 | Area: Kalol | Bedrooms: 1.0 -> Estimated Balconies: 1
Row 472 | Area: Raysan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 473 | Area: Gift City | Bedrooms: 3.0 -> Estimated Balconies: 2
Row 474 | Area: Randheja | Bedrooms: 2.0 -> Estimated Balconies: 2
Row 475 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 476 | Area: Karai | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 477 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 478 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 480 | Area: Sector 22 | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 482 | Area: SP Ring Road | Bedrooms: 2.0 -> Estimated Balconies: 2
Row 483 | Area: Randesan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 484 | Area: Sargasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 486 | Area: Sargasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 488 | Area: Gift City | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 489 | Area: Sargasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 490 | Area: Koba | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 491 | Area: Sargasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 493 | Area: Gift City | Bedrooms: 3.0 -> Estimated Balconies: 2
Row 495 | Area: Vavol | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 498 | Area: Sargasan | Bedrooms: 0.0 -> Estimated Balconies: 0
Row 499 | Area: Kalol | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 500 | Area: Sargasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 503 | Area: Gift City | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 504 | Area: Sargasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 507 | Area: Randesan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 508 | Area: Kudasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 509 | Area: Gift City | Bedrooms: 3.0 -> Estimated Balconies: 2
Row 510 | Area: Randesan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 511 | Area: Sargasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 515 | Area: Pethapur | Bedrooms: 3.0 -> Estimated Balconies: 2
Row 516 | Area: Sargasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 518 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 519 | Area: Vavol | Bedrooms: 4.0 -> Estimated Balconies: 2
Row 520 | Area: Raysan | Bedrooms: 4.0 -> Estimated Balconies: 2
Row 521 | Area: Sargasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 522 | Area: Raysan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 523 | Area: Kalol | Bedrooms: 0.0 -> Estimated Balconies: 0
Row 524 | Area: Gift City | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 525 | Area: Sargasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 528 | Area: Pethapur | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 529 | Area: Koba | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 530 | Area: Kolavada | Bedrooms: 3.0 -> Estimated Balconies: 2.0
Row 532 | Area: Kudasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 533 | Area: Kalol | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 535 | Area: Randesan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 536 | Area: Sargasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 537 | Area: Kalol | Bedrooms: 1.0 -> Estimated Balconies: 1
Row 538 | Area: Kalol | Bedrooms: 3.0 -> Estimated Balconies: 2
Row 539 | Area: Kalol | Bedrooms: 1.0 -> Estimated Balconies: 1
Row 541 | Area: Kolavada | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 542 | Area: Vavol | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 544 | Area: Pethapur | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 545 | Area: Sargasan | Bedrooms: 0.0 -> Estimated Balconies: 0
Row 547 | Area: Gift City | Bedrooms: 4.0 -> Estimated Balconies: 2
Row 548 | Area: Kudasan | Bedrooms: 4.0 -> Estimated Balconies: 2
Row 549 | Area: Randesan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 550 | Area: Randesan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 551 | Area: Sargasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 552 | Area: Adalaj | Bedrooms: 3.0 -> Estimated Balconies: 3
Row 553 | Area: Randesan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 554 | Area: Pethapur | Bedrooms: 3.0 -> Estimated Balconies: 2
Row 555 | Area: Vavol | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 556 | Area: Sargasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 557 | Area: SG Highway | Bedrooms: 1.0 -> Estimated Balconies: 1
Row 560 | Area: Kudasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 561 | Area: Randesan | Bedrooms: 5.0 -> Estimated Balconies: 2
Row 562 | Area: Gift City | Bedrooms: 1.0 -> Estimated Balconies: 1
Row 563 | Area: Sargasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 564 | Area: Dahegam | Bedrooms: 1.0 -> Estimated Balconies: 1
Row 568 | Area: Pethapur | Bedrooms: 3.0 -> Estimated Balconies: 2
Row 570 | Area: Sargasan | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 572 | Area: Kudasan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 575 | Area: Vavol | Bedrooms: 3.0 -> Estimated Balconies: 2
Row 576 | Area: Pethapur | Bedrooms: 2.0 -> Estimated Balconies: 1
Row 577 | Area: Sargasan | Bedrooms: 4.0 -> Estimated Balconies: 2
Row 578 | Area: Randesan | Bedrooms: 3.0 -> Estimated Balconies: 1
Row 580 | Area: Gift City | Bedrooms: 2.0 -> Estimated Balconies: 1

In [ ]:
# Create missing indicators for current_floor and total_floors before filling missing values

df["current_floor_missing"] = (
    df["current_floor"].isna().astype(int)
)

df["current_floor"] = (
    df["current_floor"]
    .fillna("Unknown")
)

df["total_floors_missing"] = (
    df["total_floors"].isna().astype(int)
)

df["total_floors"] = (
    df["total_floors"]
    .fillna("Unknown")
)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1880 entries, 0 to 1883
Data columns (total 27 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Name                   1880 non-null   object
 1   BHK                    1730 non-null   object
 2   Location               1880 non-null   object
 3   Price (INR in Lakhs)   1880 non-null   float64
 4   Price_per_sqft         1874 non-null   float64
 5   Area_sqft              1880 non-null   float64
 6   Area_type              1448 non-null   object
 7   Status                 1862 non-null   object
 8   Description            1880 non-null   object
 9   Property_URL           1880 non-null   object
 10  bedrooms               1737 non-null   object
 11  bathrooms              1737 non-null   object
 12  balconies              1737 non-null   object
 13  current_floor          1880 non-null   object
 14  total_floors           1880 non-null   object
 15  total_floors_house     66 non-null     object
 16  facing                 549 non-null    object
 17  furnishing_status      812 non-null    object
 18  property_type          1327 non-null   object
 19  age_possession         1695 non-null   object
 20  amenities              1695 non-null   object
 21  additional_rooms       1695 non-null   object
 22  nearby                 1695 non-null   object
 23  additional_insights    1695 non-null   object
 24  Mapped_Area            1880 non-null   object
 25  current_floor_missing  1880 non-null   int64
 26  total_floors_missing   1880 non-null   int64
dtypes: float64(3), int64(2), object(22)
memory usage: 475.8+ KB

In [ ]:
df['furnishing_status'].value_counts()

furnishing_status
unfurnished            544
semi-furnished         138
furnished               65
fully furnished         52
semi-Furnished           3
partly furnished         2
partially furnished      2
well furnished           1
well built               1
partial-furnished        1
well-Furnished           1
full-Furnished           1
fully-furnished          1
Name: count, dtype: int64

In [ ]:
def normalize_furnishing(x):
    if pd.isna(x):
        return np.nan
    
    x = x.lower().replace("-", " ").strip()

    if "unfurnished" in x:
        return "unfurnished"
    
    if any(k in x for k in ["semi", "partly", "partially", "partial"]):
        return "semi-furnished"
    
    if any(k in x for k in ["furnished", "full", "well"]):
        return "furnished"
    
    return np.nan

In [ ]:
df["furnishing_status"]=df["furnishing_status"].apply(normalize_furnishing)

In [ ]:
df['furnishing_status'].value_counts()

furnishing_status
unfurnished       544
semi-furnished    146
furnished         122
Name: count, dtype: int64

In [ ]:
df.info()

In [ ]:
df['facing'].value_counts()

In [ ]:
def clean_facing(x):

    if pd.isna(x):
        return np.nan

    x = str(x).lower().strip()

    mapping = {

        # EAST
        "east": "East",
        "east-facing": "East",
        "east-facing ": "East",
        "east facing": "East",
        "east direction": "East",
        "east-facing": "East",
        "east-facing ": "East",
        "east-facing": "East",
        "east-facing": "East",

        # WEST
        "west": "West",
        "west-facing": "West",
        "west-facing ": "West",
        "west-facing": "West",

        # NORTH
        "north": "North",
        "north-facing": "North",

        # SOUTH
        "south": "South",

        # NORTH EAST
        "north-east": "North-East",
        "north east": "North-East",
        "north-east-facing": "North-East",
        "north-east-facing ": "North-East",

        # NORTH WEST
        "north-west": "North-West",

        # SOUTH EAST
        "south-east": "South-East",

        # SOUTH WEST
        "south-west": "South-West",

        # NON-FACING / VIEW VALUES
        "garden": "Other",
        "garden-facing": "Other",
        "garden facing": "Other",
        "garden face": "Other",
        "park": "Other",
        "park facing": "Other",
        "road": "Other",
        "road facing": "Other",
        "road side": "Other",
        "road side view": "Other",
        "roadside view": "Other",
        "main road": "Other",
        "main road, park": "Other",
        "park and main road": "Other",
        "pool": "Other",
        "swimming pool": "Other",
        "balcony view": "Other",
        "courtyard": "Other",
        "open space side": "Other",
        "side open": "Other",
        "sky view": "Other",
        "corner": "Other",
        "three sides open spaceous": "Other",
        "frot side": "Other",
        "swami narayan dham": "Other"
    }

    return mapping.get(x, "Other")


# Apply cleaning
df["facing_cleaned"] = df["facing"].apply(clean_facing)

# Check cleaned values
print(df["facing_cleaned"].value_counts())

facing_cleaned
East          345
North-East     79
Other          58
West           26
North          15
North-West      8
South           8
South-East      6
South-West      4
Name: count, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1880 entries, 0 to 1883
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Name                   1880 non-null   object
 1   BHK                    1730 non-null   object
 2   Location               1880 non-null   object
 3   Price (INR in Lakhs)   1880 non-null   float64
 4   Price_per_sqft         1874 non-null   float64
 5   Area_sqft              1880 non-null   float64
 6   Area_type              1448 non-null   object
 7   Status                 1862 non-null   object
 8   Description            1880 non-null   object
 9   Property_URL           1880 non-null   object
 10  bedrooms               1737 non-null   object
 11  bathrooms              1737 non-null   object
 12  balconies              1737 non-null   object
 13  current_floor          1880 non-null   object
 14  total_floors           1880 non-null   object
 15  total_floors_house     66 non-null     object
 16  facing                 549 non-null    object
 17  furnishing_status      812 non-null    object
 18  property_type          1327 non-null   object
 19  age_possession         1695 non-null   object
 20  amenities              1695 non-null   object
 21  additional_rooms       1695 non-null   object
 22  nearby                 1695 non-null   object
 23  additional_insights    1695 non-null   object
 24  Mapped_Area            1880 non-null   object
 25  current_floor_missing  1880 non-null   int64
 26  total_floors_missing   1880 non-null   int64
 27  facing_cleaned         549 non-null    object
dtypes: float64(3), int64(2), object(23)
memory usage: 490.5+ KB

In [ ]:
df['age_possession'].value_counts()

In [ ]:
def extract_age(text):
    if pd.isna(text):
        return "Unknown"
    
    text = str(text).lower()

    if any(x in text for x in ["0-1", "0–1", "1 year", "1-year", "nearly new"]):
        return "New"
    
    if any(x in text for x in ["1-5", "2-5", "1–5"]):
        return "1-5 years"
    
    if any(x in text for x in ["5-10", "5–10"]):
        return "5-10 years"
    
    if any(x in text for x in ["10-20", "10–15", "11-20", "10 year", "10+"]):
        return "10-20 years"
    
    if any(x in text for x in ["20"]):
        return "20+ years"
    
    return "Unknown"

In [ ]:
def extract_possession(text):
    if pd.isna(text):
        return "Unknown"
    
    text = str(text).lower()

    if "ready" in text or "immediate" in text:
        return "Ready to move"
    
    if "under" in text:
        return "Under construction"
    
    if "vacant" in text:
        return "Vacant"
    
    if "available" in text:
        return "Future possession"
    
    return "Unknown"

In [ ]:
def clean_age_possession(x):

    # handle missing values
    if x is None:
        return pd.Series(["Unknown", "Unknown"])

    # convert list → string
    x = str(x).lower()

    # handle empty cases
    if x in ["[]", "[null, null]"]:
        return pd.Series(["Unknown", "Unknown"])

    x = x.strip("[]")

    parts = [p.strip() for p in x.split(",")]

    age = parts[0] if len(parts) > 0 else ""
    possession = parts[1] if len(parts) > 1 else ""

    return pd.Series([
        extract_age(age),
        extract_possession(possession)
    ])

In [ ]:
df[["property_age_bucket", "possession_status"]] = (
    df["age_possession"].apply(clean_age_possession)
)

In [683]:
# df['age_possession'].value_counts()

In [293]:
df['additional_rooms'].value_counts()

additional_rooms
[]                               1687
[pooja room]                        3
[puja room]                         1
[servant room]                      1
[store room, gallery/balcony]       1
[loft]                              1
[store room]                        1
Name: count, dtype: int64

In [304]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1880 entries, 0 to 1883
Data columns (total 30 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Name                   1880 non-null   object
 1   BHK                    1730 non-null   object
 2   Location               1880 non-null   object
 3   Price (INR in Lakhs)   1880 non-null   float64
 4   Price_per_sqft         1874 non-null   float64
 5   Area_sqft              1880 non-null   float64
 6   Area_type              1448 non-null   object
 7   Status                 1862 non-null   object
 8   Description            1880 non-null   object
 9   Property_URL           1880 non-null   object
 10  bedrooms               1737 non-null   object
 11  bathrooms              1737 non-null   object
 12  balconies              1737 non-null   object
 13  current_floor          1880 non-null   object
 14  total_floors           1880 non-null   object
 15  total_floors_house     66 non-null     object
 16  facing                 549 non-null    object
 17  furnishing_status      812 non-null    object
 18  property_type          1327 non-null   object
 19  age_possession         1695 non-null   object
 20  amenities              1695 non-null   object
 21  additional_rooms       1695 non-null   object
 22  nearby                 1695 non-null   object
 23  additional_insights    1695 non-null   object
 24  Mapped_Area            1880 non-null   object
 25  current_floor_missing  1880 non-null   int64
 26  total_floors_missing   1880 non-null   int64
 27  facing_cleaned         549 non-null    object
 28  property_age_bucket    1880 non-null   object
 29  possession_status      1880 non-null   object
dtypes: float64(3), int64(2), object(25)
memory usage: 519.9+ KB

In [305]:
df["is_new_property"] = (
    df["property_age_bucket"].isin(["New", "1-5 years"])
).astype(int)

In [307]:
df["possession_status"] = df["possession_status"].replace(
    "Future possession",
    "Under construction"
)

In [308]:
df["possession_status"].value_counts()

possession_status
Ready to move         1361
Unknown                503
Under construction      16
Name: count, dtype: int64

In [309]:
df["is_ready_to_move"] = (
    df["possession_status"] == "Ready to move"
).astype(int)

In [311]:
df['amenities'].value_counts()

amenities
[]                                                                                                                                    1484
[lift, garden, parking, clubhouse, swimming pool, gym, security, power backup]                                                          10
[lift, gym, security, power backup]                                                                                                      7
[lift]                                                                                                                                   7
[lift, garden, parking, clubhouse, power backup]                                                                                         6
[parking]                                                                                                                                6
[lift, parking]                                                                                                                          5
[lift, garden, parking, security, power backup]                                                                                          5
[swimming pool, fitness centre / gym]                                                                                                    4
[landscaped gardens, childrens play areas, clubhouse, security]                                                                          4
[24 hour water, 24 hour electricity, solar system]                                                                                       3
[fitness center, clubhouse]                                                                                                              3
[visitor parking]                                                                                                                        3
[fitness center]                                                                                                                         3
[lift, power backup, rainwater harvesting]                                                                                               2
[lift, gym, swimming pool]                                                                                                               2
[party plot/garden, common parking area, 24 hr. Water, 24 hr. electricity, pipeline gas connection]                                      2
[gym, indoor games, community hall, home theatre, water body, conference room, working office]                                           2
[fitness center, clubhouse, swimming pool]                                                                                               2
[gym, clubhouse, swimming pool, lift]                                                                                                    2
[gym, clubhouse, pool, power backup]                                                                                                     2
[lift, parking, clubhouse, swimming pool, power backup]                                                                                  2
[lift, fitness center]                                                                                                                   2
[gym, clubhouse, power backup, lift]                                                                                                     2
[lift, swimming pool]                                                                                                                    2
[fitness centre / gym, club house, park, shopping centre, lift(s)]                                                                       2
[swimming pool, fitness centre / gym, club house]                                                                                        2
[visitor parking, on-Call maintenance]                                                                                                   2
[gym, clubhouse, lift]                                                                                                                   2
[swimming pool]                                                                                                                          2
[clubhouse, swimming pool, garden]                                                                                                       2
[swimming pool, lift]                                                                                                                    2
[lift, garden, parking, clubhouse, security, power backup]                                                                               1
[clubhouse, garden, children play area, parking, power backup, security, cctv, pic and drop facility]                                    1
[club house, chi]                                                                                                                        1
[fitness centre / gym, club house, cctv surveillance, lift(s)]                                                                           1
[lift, gym, parking]                                                                                                                     1
[clubhouse, gym, cafe, badminton court, box cricket]                                                                                     1
[garden, gym, indoor play hall, common hall]                                                                                             1
[modular kitchen, wardrobes, parking]                                                                                                    1
[lift, garden, parking, electric geysers, fans, ac, solar panel, power backup]                                                           1
[gym, park, kids play area, tt area, community hall]                                                                                     1
[lift, gym, clubhouse, swimming pool]                                                                                                    1
[lift, parking, clubhouse, garden]                                                                                                       1
[rainwater harvesting, power backup, lift]                                                                                               1
[lift, power backup, rainwater harvesting, clubhouse]                                                                                    1
[lift, clubhouse, fitness center]                                                                                                        1
[gym, yoga room, children play area, community hall]                                                                                     1
[gym, garden, lift]                                                                                                                      1
[community hall, yoga room, garden, children play area]                                                                                  1
[3 car parking, lift, garden]                                                                                                            1
[garden, security, clubhouse]                                                                                                            1
[garden, gym, yoga room, theatre, club house, kids zone]                                                                                 1
[24/7 water, gated society security, visitor parking, on-Call maintenance]                                                               1
[club, power back-Up]                                                                                                                    1
[lift, garden, parking, clubhouse, swimming pool, gym, security, power backup, mini golf course, squash court, cafe]                     1
[swimming pool, gym, yoga room, table tennis room, badminton, children play area, cricket, walking track]                                1
[lift, gym, security]                                                                                                                    1
[swimming pool, fitness centre / gym, park, lift(s)]                                                                                     1
[swimming pool, fitness]                                                                                                                 1
[central ac, parking]                                                                                                                    1
[swimming pool, gym, garden, tennis court, clubhouse, 24x7 security, fire safety]                                                        1
[lift, power backup, childrens play area]                                                                                                1
[lift, fire safety system, 24 hours water supply, security]                                                                              1
[swimming pool, fitness centre / gym, park, club house, cctv surveillance]                                                               1
[gym, clubhouse]                                                                                                                         1
[landscaped gardens, childrens play area, yoga zone, cctv surveillance, gated security, ample parking]                                   1
[sky lounge, clubhouse, landscaped leisure zones]                                                                                        1
[cricket pitch, badminton court, cycling & jogging track, power backup]                                                                  1
[fitness]                                                                                                                                1
[gym, clubhouse, power backup, lift, rainwater harvesting]                                                                               1
[clubhouse, gym, lift, swimming pool]                                                                                                    1
[lift, on-Call maintenance]                                                                                                              1
[gym, rainwater harvesting, power backup, lift]                                                                                          1
[lift, power backup, parking, gym, clubhouse]                                                                                            1
[swimming pool, club house, cctv surveillance, lift(s)]                                                                                  1
[garden]                                                                                                                                 1
[lift, gym, clubhouse, cctv]                                                                                                             1
[lift, power backup, fire safety systems, 247 water supply]                                                                              1
[swimming pool, gym, clubhouse, lift]                                                                                                    1
[gymnasium, children's play area, swimming pool, sports avenues, library, business center, temple]                                       1
[lift, garden, parking, clubhouse]                                                                                                       1
[gym]                                                                                                                                    1
[indoor games, kids play area, 24 hours water supply, security]                                                                          1
[lift, garden, parking]                                                                                                                  1
[lift, gym, rooftop]                                                                                                                     1
[fitness centre / gym, parking, clubhouse, swimming pool]                                                                                1
[lift, gated society]                                                                                                                    1
[clubhouse, lift]                                                                                                                        1
[lift, gym, clubhouse]                                                                                                                   1
[park, lift]                                                                                                                             1
[lift, park]                                                                                                                             1
[lift, garden, park, fitness centre / gym]                                                                                               1
[parking, gated society]                                                                                                                 1
[gym, clubhouse, pool, parking, lift]                                                                                                    1
[gym, pool]                                                                                                                              1
[swimming pool, fitness centre / gym, grocery shop]                                                                                      1
[lift, visitor parking, on-Call maintenance]                                                                                             1
[fitness centre / gym, club house, lift(s)]                                                                                              1
[fitness centre / gym, club house, parking]                                                                                              1
[lift, power backup, parking]                                                                                                            1
[clubhouse, gym, parking]                                                                                                                1
[power backup, visitor parking]                                                                                                          1
[lift, gym, clubhouse, swimming pool, parking]                                                                                           1
[clubhouse, swimming pool, lift, power backup]                                                                                           1
[clubhouse, gym]                                                                                                                         1
[air-conditioned, parking]                                                                                                               1
[lift, gym, clubhouse, swimming pool, power backup]                                                                                      1
[lift, parking, garden]                                                                                                                  1
[lift, clubhouse, gym, swimming pool]                                                                                                    1
[fitness centre / gym]                                                                                                                   1
[clubhouse, gym, lift]                                                                                                                   1
[lift, power backup, central ac]                                                                                                         1
[lift, power backup, visitor parking, on-Call maintenance]                                                                               1
[clubhouse, gym, swimming pool, lift, parking, power backup]                                                                             1
[power backup, clubhouse]                                                                                                                1
[lift, parking, gated society access, on-Call maintenance]                                                                               1
[lift, clubhouse, gym, 24/7 water]                                                                                                       1
[lift, garden, outdoor play area, banquet hall, badminton court, cricket pitch, indoor cinema, indoor play area, library, parking]       1
[lift, gated security, power backup]                                                                                                     1
[clubhouse, gym, lift, pool]                                                                                                             1
[lift, gym, swimming pool, power backup]                                                                                                 1
[gym, swimming pool, lift, power backup]                                                                                                 1
[gym, clubhouse, lift, power backup]                                                                                                     1
[lift, parking, solar system]                                                                                                            1
[power backup, parking]                                                                                                                  1
[lift, cctv surveillance]                                                                                                                1
[lift, gym, clubhouse, parking, swimming pool]                                                                                           1
[parking, gym, clubhouse, lift]                                                                                                          1
[garden, club house, gym]                                                                                                                1
[lift, parking, cctv camera, power backup]                                                                                               1
[full power backup, 24x7 water, on-Call maintenance]                                                                                     1
[swimming pool, gym, tennis, table tennis, carom, ches, library]                                                                         1
[lift, gym, parking, power backup]                                                                                                       1
[parking, power backup]                                                                                                                  1
[gym, swimming pool]                                                                                                                     1
[fitness center, power backup]                                                                                                           1
[car parking facility, 24 hours water]                                                                                                   1
[lift, security, 24x7 water supply]                                                                                                      1
[visitor parking, modular kitchen]                                                                                                       1
[gated security, modular kitchen, 24/7 water]                                                                                            1
Name: count, dtype: int64

In [316]:
df['nearby'].value_counts()

nearby
[]                                                                                                                      1247
[school, hospital, metro, mall, highway]                                                                                  35
[school]                                                                                                                  19
[metro]                                                                                                                   12
[school, hospital, metro]                                                                                                 11
[school, hospital]                                                                                                        10
[hospital]                                                                                                                 9
[highway]                                                                                                                  9
[hospitals, ambe mata mandir]                                                                                              8
[school, hospital, mall, highway]                                                                                          7
[temple, hospital]                                                                                                         7
[gift city]                                                                                                                6
[metro station, gift city]                                                                                                 6
[hospitals]                                                                                                                5
[gift city, metro station]                                                                                                 5
[temples, hospitals]                                                                                                       4
[temple]                                                                                                                   4
[school, hospital, market]                                                                                                 4
[school, markets]                                                                                                          4
[podar international]                                                                                                      4
[sheth n.N saravajanik hospital, randheja railway station]                                                                 4
[schools, hospitals]                                                                                                       3
[sg highway]                                                                                                               3
[hospital, temple]                                                                                                         3
[hospitals, shree satay narayan mandir]                                                                                    3
[12 meter road]                                                                                                            3
[relience circle]                                                                                                          2
[s p ring road]                                                                                                            2
[hospitals, infocity]                                                                                                      2
[schools, hospital, shopping]                                                                                              2
[mall, school]                                                                                                             2
[gandhinagar, kalol]                                                                                                       2
[pdpu metro, national highway 48]                                                                                          2
[temples, healthcare facilities]                                                                                           2
[religious landmarks, several]                                                                                             2
[school, market]                                                                                                           2
[shri hanumanji temple, multiple hospitals]                                                                                2
[hospitals, schools, markets]                                                                                              2
[hospital, school]                                                                                                         2
[hospitals, temple]                                                                                                        2
[religious sites]                                                                                                          2
[metro, malls, schools]                                                                                                    2
[school, hospital, mall]                                                                                                   2
[highway, mall]                                                                                                            2
[health focus physiotherapy clinic, infocity, pandit deendayal petroleum university]                                       2
[metro station, hospital]                                                                                                  2
[metro, school]                                                                                                            2
[hospital, railway station]                                                                                                2
[metro, road, highway]                                                                                                     1
[key connectivity points, schools]                                                                                         1
[hospitals, schools, markets, khodiyar temple, bank of baroda atm]                                                         1
[key religious sites, medical facilities]                                                                                  1
[metro, malls, schools, highways]                                                                                          1
[metro, market, pdpu, swaminarayan kanyashala, cuty pulse cinema, temples, svms hospital]                                  1
[hospitals, clubhouse]                                                                                                     1
[metro, religious sites]                                                                                                   1
[top schools, hospitals, sarkhej gandhinagar highway]                                                                      1
[health focus physiotherapy clinic, infocity]                                                                              1
[school, airport, shopping]                                                                                                1
[school, hospital, university]                                                                                             1
[schools, market, main road]                                                                                               1
[school, hotel, mall]                                                                                                      1
[schools, markets, hospitals]                                                                                              1
[sanjari park, pethapur]                                                                                                   1
[markets, metro, schools, railways]                                                                                        1
[hospitals, supreme smile dental clinic, gayatri hospital]                                                                 1
[prominent temples, multispeciality clinic]                                                                                1
[hospital, mall, railway station]                                                                                          1
[religious sites, multispecialty clinic]                                                                                   1
[multiple temples, dental clinic]                                                                                          1
[swaminarayan temple, gayatri hospital]                                                                                    1
[schools, hospital, mall, highway]                                                                                         1
[temples, medical facilities]                                                                                              1
[khodiyar temple, medical facilities, atms]                                                                                1
[hospitals, shr hanumanji temple]                                                                                          1
[bus depots, school]                                                                                                       1
[key healthcare facilities, infocity office complex]                                                                       1
[metro, highway]                                                                                                           1
[hospitals, infocity office complex]                                                                                       1
[pdpu road, gift city, metro station]                                                                                      1
[koba circle metro, schools, nh 48, esic hospital]                                                                         1
[nh147, sahjanand school, shoppers plaza]                                                                                  1
[multiple religious sites, shree mahakali mataji temple, swaminarayan temple]                                              1
[school, shopping malls, hospitals, garden]                                                                                1
[metro, hospitals, office complexes]                                                                                       1
[tcs, software company offices]                                                                                            1
[schools, hospital, shopping at swagat holiday mall]                                                                       1
[temples, clinics]                                                                                                         1
[multiple hospitals, health focus physiotherapy clinic]                                                                    1
[sg highway, adalaj petrol pump]                                                                                           1
[several temples]                                                                                                          1
[metro, schools]                                                                                                           1
[ramdevpir temple, Pethapur, gandhinagar]                                                                                  1
[tech parks, infocity, gift city, s.G. Highway, swagat holiday mall, dmart]                                                1
[sg highway, daiict, aashka hospital]                                                                                      1
[sbi bank, temple, market, school, rickshaw stand]                                                                         1
[railway station, medical college hospital, city bus stand]                                                                1
[school, hospital, highway, mall]                                                                                          1
[school, hospital, bus stop, highway]                                                                                      1
[relience smart bazar]                                                                                                     1
[science city circle]                                                                                                      1
[hospital, school, malls]                                                                                                  1
[poddar international school]                                                                                              1
[vavol pundrasan road]                                                                                                     1
[city pulse cinema, urjanagar 1 area]                                                                                      1
[S.G highway]                                                                                                              1
[pdpu road]                                                                                                                1
[sargasan cross road]                                                                                                      1
[d' mart]                                                                                                                  1
[mall, school, hospital]                                                                                                   1
[infocity area, national institute of design road]                                                                         1
[kh road]                                                                                                                  1
[club house]                                                                                                               1
[markets, hospital, school, malls]                                                                                         1
[schools, markets]                                                                                                         1
[metro station, school, hospital, highway]                                                                                 1
[school, mall, temple, garden]                                                                                             1
[school, hospital, shopping mall]                                                                                          1
[school, shopping malls]                                                                                                   1
[school, hospital, metro, mall, highway, airport, park]                                                                    1
[metro, rever]                                                                                                             1
[school, hospital, bazaar]                                                                                                 1
[schools, healthcare, shri hanumanji temple]                                                                               1
[temple, dental clinic]                                                                                                    1
[key medical facilities, gandhinagar]                                                                                      1
[railway station, metro station, mall, market]                                                                             1
[swaminarayan temple, hospitals]                                                                                           1
[malls, highways]                                                                                                          1
[hospitals, religious sites]                                                                                               1
[schools, hospitals, banks]                                                                                                1
[metro, market, hospital, school]                                                                                          1
[shopping malls, highways]                                                                                                 1
[school, shopping hubs]                                                                                                    1
[schools, malls, connectivity hubs]                                                                                        1
[highway, mall, companies]                                                                                                 1
[hospitals, religious site]                                                                                                1
[key hospitals, shree satay narayan mandir]                                                                                1
[school, vegetable market, temple, railway station, bus port]                                                              1
[khodiyar temple, bank of baroda atm, hospitals]                                                                           1
[key temples, healthcare centers]                                                                                          1
[hospital, school, market]                                                                                                 1
[vachhani hospital, kroma multispeciality dental clinic]                                                                   1
[health clinics, infocity office complex, pandit deendayal petroleum university]                                           1
[city, highway, shopping centre]                                                                                           1
[amenities]                                                                                                                1
[temples, clinics, fitness center]                                                                                         1
[mini market, sikshapatri road, vaishnodevi circle, gift city]                                                             1
[healthcare facilities, Pandit Deendayal Petroleum University]                                                             1
[malls, highway]                                                                                                           1
[hospital, market, metro station]                                                                                          1
[hospital, garden]                                                                                                         1
[metro, school, hospital, market]                                                                                          1
[mahudi tirth jain temple, mahudi jain temple]                                                                             1
[schools, malls, nh 48 connectivity]                                                                                       1
[IIT Gandhinagar, Gift City Circle]                                                                                        1
[super mall, reputed schools, shraddha womens hospital]                                                                    1
[highway, bus stand, vegetable market, hotels]                                                                             1
[metro, airport]                                                                                                           1
[gayatri mandir, hospitals]                                                                                                1

In [333]:
df.drop(columns=["BHK"], inplace=True)

In [339]:
df['Area_type'].value_counts()

Area_type
Super Built-up Area    746
Carpet Area            558
Built-up Area          144
Name: count, dtype: int64

In [342]:
df.drop(columns=["is_ready_to_move"], inplace=True)

In [340]:
df['Status'].value_counts()

Status
Ready To Move         1602
Under Construction     260
Name: count, dtype: int64

In [344]:
df["is_ready_to_move"] = (
    df["Status"] == "Ready To Move"
).astype(int)

In [345]:
df.drop(columns=["Status"], inplace=True)

In [ ]:
# convert into float datatype for modeling

df['bedrooms']=df['bedrooms'].astype(float)
df['bathrooms']=df['bathrooms'].astype(float)
df['balconies']=df['balconies'].astype(float)

In [365]:
df['current_floor'].value_counts()
# df['total_floors'].value_counts()

current_floor
Unknown               907
2nd                    87
5th floor              73
3rd                    64
1st                    55
2nd floor              55
4th                    52
6th floor              50
4th floor              41
ground floor           33
1st floor              32
7th floor              31
8th floor              31
5th                    27
3rd floor              26
5                      22
9th floor              16
12th floor             14
7                      14
6th                    13
4th level              10
10th                   10
7th                    10
10th floor              9
9th                     9
8th                     9
11th floor              8
13th floor              8
11th                    8
3                       7
1st level               7
12th                    6
4                       6
6th level               6
2                       6
13th                    6
8th level               5
5th level               5
13                      5
9th level               4
7th level               4
6                       4
ground level            4
9                       3
G+2 (3 flor)            3
first floor             3
Ground floor            3
3rd level               3
14th floor              3
5                       2
quiet                   2
27th floor              2
17th                    2
convenient              2
lower ground floor      2
single                  2
2                       2
8                       2
10                      2
20th                    2
third                   1
15th                    1
second floor            1
second                  1
14                      1
3                       1
rised floor             1
single floor            1
13/13                   1
23rd                    1
10th level              1
1                       1
lower ground level      1
18th level              1
25th                    1
14th level              1
10th to 13th            1
21st                    1
G-Floor                 1
22nd                    1
2nd level               1
21st floor              1
seventh floor           1
ground                  1
19th                    1
prime corner side       1
4                       1
19th floor              1
12th-Floor              1
24th                    1
Ground-Floor            1
23                      1
Top floor               1
basement                1
quiet floor             1
2-Floor                 1
third floor             1
revar front             1
26th                    1
North east              1
first                   1
Name: count, dtype: int64

In [364]:
# if current_floor = top floor variants then set current_floor = total_floors


top_floor_values = [
    "top floor",
    "top level",
    "top-Floor",
    "top-floor"
]

# mask
mask = df["current_floor"].isin(top_floor_values)

# assign total_floors value
df.loc[mask, "current_floor"] = df.loc[mask, "total_floors"]

# optional check
print(df.loc[mask, ["current_floor", "total_floors"]].head())

    current_floor total_floors
14              7            7
46              4            4
56              5            5
84              7            7
116             4            4

In [ ]:
# CURRENT FLOOR CLEANING / STANDARDIZATION

floor_mapping = {

    "Unknown": "Unknown",

    "2nd": 2,
    "5th floor": 5,
    "3rd": 3,
    "2nd floor": 2,
    "1st": 1,
    "4th": 4,
    "6th floor": 6,
    "4th floor": 4,
    "ground floor": 0,
    "1st floor": 1,
    "8th floor": 8,
    "7th floor": 7,
    "5th": 5,
    "3rd floor": 3,
    "9th floor": 9,
    "12th floor": 12,
    "6th": 6,
    "7th": 7,
    "4th level": 4,
    "10th": 10,
    "8th": 8,
    "10th floor": 10,
    "9th": 9,
    "11th": 11,
    "13th floor": 13,
    "11th floor": 11,
    "1st level": 1,
    "13th": 13,
    "6th level": 6,
    "2": 2,
    "12th": 12,
    "8th level": 8,
    "5th level": 5,
    "7th level": 7,
    "ground level": 0,
    "9th level": 9,
    "G+2 (3 flor)": "Unknown",
    "first floor": 1,
    "Ground floor": 0,
    "3rd level": 3,
    "14th floor": 14,
    "lower ground floor": -1,
    "27th floor": 27,
    "20th": 20,
    "single": 1,
    "5": 5,
    "convenient": "Unknown",
    "17th": 17,
    "quiet": "Unknown",
    "third": 3,
    "14th level": 14,
    "rised floor": "Unknown",
    "second floor": 2,
    "second": 2,
    "15th": 15,
    "single floor": 1,
    "10th level": 10,
    "lower ground level": -1,
    "18th level": 18,
    "13/13": 13,
    "25th": 25,
    "3": 3,
    "19th": 19,
    "22nd": 22,
    "21st": 21,
    "G-Floor": 0,
    "10th to 13th": 10,
    "2nd level": 2,
    "21st floor": 21,
    "seventh floor": 7,
    "ground": 0,
    "23rd": 23,
    "prime corner side": "Unknown",
    "4": 4,
    "19th floor": 19,
    "12th-Floor": 12,
    "24th": 24,
    "Ground-Floor": 0,
    "23": 23,
    "Top floor": "Unknown",
    "basement": -1,
    "quiet floor": "Unknown",
    "2-Floor": 2,
    "third floor": 3,
    "revar front": "Unknown",
    "26th": 26,
    "North east": "Unknown",
    "first": 1
}

# apply mapping

df["current_floor"] = df["current_floor"].map(floor_mapping)

In [371]:
df['current_floor'].value_counts()

current_floor
2          152
5          107
4          104
1          101
3           96
6           69
7           46
8           45
0           43
9           29
12          21
10          21
11          16
13          15
Unknown     13
-1           4
14           4
27           2
20           2
23           2
17           2
19           2
21           2
25           1
15           1
18           1
22           1
24           1
26           1
Name: count, dtype: int64

In [ ]:
# replace Unknown with NaN
df["current_floor"] = df["current_floor"].replace("Unknown", np.nan)

# convert to float
df["current_floor"] = df["current_floor"].astype(float)

print(df["current_floor"].dtype)
print(df["current_floor"].head())

float64
0    NaN
1    NaN
2    NaN
3    9.0
4    8.0
Name: current_floor, dtype: float64

C:\Users\MEGH BAVARVA\AppData\Local\Temp\ipykernel_4760\1435631192.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["current_floor"] = df["current_floor"].replace("Unknown", np.nan)

In [374]:
df['Area_type'].value_counts()

Area_type
Super Built-up Area    746
Carpet Area            558
Built-up Area          144
Name: count, dtype: int64

In [ ]:
# One hot encoding for Area_type

area_dummies = pd.get_dummies(
    df["Area_type"],
    prefix="Area",
    dtype=int
)

# add new columns
df = pd.concat([df, area_dummies], axis=1)

# remove original column
df.drop(columns=["Area_type"], inplace=True)

In [ ]:
df.rename(columns={'Area_Built-up Area': 'is_built_up_area'}, inplace=True)
df.rename(columns={'Area_Carpet Area': 'is_carpet_area'}, inplace=True)
df.rename(columns={'Area_Super Built-up Area': 'is_super_built_up_area'}, inplace=True)

df['is_built_up_area']=df['is_built_up_area'].astype(bool)
df['is_carpet_area']=df['is_carpet_area'].astype(bool)
df['is_super_built_up_area']=df['is_super_built_up_area'].astype(bool)

In [385]:
df['total_floors'].value_counts()

total_floors
Unknown    1037
13          144
5           129
7            96
8            68
14           67
3            42
6            38
9            36
4            34
12           32
11           30
10           24
1            20
2            14
33           12
25           11
20           10
35            5
18            4
24            4
31            3
22            3
19            3
34            3
21            3
17            2
32            2
15            2
16            1
50            1
Name: count, dtype: int64

In [386]:
# replace Unknown with NaN
df["total_floors"] = df["total_floors"].replace("Unknown", np.nan)

# convert to float
df["total_floors"] = df["total_floors"].astype(float)

C:\Users\MEGH BAVARVA\AppData\Local\Temp\ipykernel_4760\1966431174.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["total_floors"] = df["total_floors"].replace("Unknown", np.nan)

In [398]:
df.loc[
    df["total_floors_house"].notna(),
    ["total_floors_house", "total_floors"]
].sample(5)

     total_floors_house  total_floors
98                    5           5.0
1628                  3           3.0
750                   5           5.0
1705                  5           5.0
736                   3           3.0

FILL missing total_floors using total_floors_house

In [ ]:
# fill only where: total_floors is NaN  and total_floors_house is not NaN

mask = (
    df["total_floors"].isna() &
    df["total_floors_house"].notna()
)

df.loc[mask, "total_floors"] = df.loc[mask, "total_floors_house"]


# remove total_floors_house column
df.drop(columns=["total_floors_house"], inplace=True)

# check
print(df["total_floors"].isna().sum())

1030

C:\Users\MEGH BAVARVA\AppData\Local\Temp\ipykernel_4760\3309743389.py:14: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[5 10 5 1 3 5 7]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[mask, "total_floors"] = df.loc[mask, "total_floors_house"]

In [404]:
df.drop(columns=['facing'], inplace=True)

df.rename(columns={'facing_cleaned': 'facing'}, inplace=True)

In [406]:
df['furnishing_status'].value_counts()

furnishing_status
unfurnished       544
semi-furnished    146
furnished         122
Name: count, dtype: int64

In [407]:
df['property_type'].value_counts()

property_type
apartment                    693
flat                         344
bungalow                      68
villa                         52
house                         35
builder floor                 25
independent house             22
plot                          20
penthouse                     19
land                           7
studio apartment               4
land/plot                      3
flats                          3
duplex                         3
apartment/flat                 3
land plot                      2
residences                     2
residential plot               2
farmhouse                      2
builder floor apartment        2
tenament                       2
residential flat               1
other                          1
bunglow                        1
plots                          1
villa bungalow                 1
residential                    1
row house                      1
luxury segment                 1
2bhk                           1
independent builder floor      1
row houses                     1
rk                             1
building                       1
residential space              1
Name: count, dtype: int64

In [ ]:
# CLEAN PROPERTY TYPE COLUMN

import numpy as np

# convert to lowercase and remove extra spaces
df['property_type_cleaned'] = (
    df['property_type']
    .astype(str)
    .str.lower()
    .str.strip()
)


#  MAPPING
property_mapping = {

    # Apartment / Flat
    'apartment': 'apartment',
    'flat': 'apartment',
    'flats': 'apartment',
    'apartment/flat': 'apartment',
    'studio apartment': 'apartment',
    'residential flat': 'apartment',
    'rk': 'apartment',
    '2bhk': 'apartment',

    # Builder Floor
    'builder floor': 'builder floor',
    'builder floor apartment': 'builder floor',
    'independent builder floor': 'builder floor',

    # House
    'house': 'house',
    'independent house': 'house',
    'row house': 'house',
    'row houses': 'house',
    'tenament': 'house',
    'building': 'house',
    'residences': 'house',
    'residential': 'house',
    'residential space': 'house',


    # Villa / Bungalow
    'villa': 'villa',
    'bungalow': 'villa',
    'bunglow': 'villa',
    'villa bungalow': 'villa',
    'duplex': 'villa',

    # Plot / Land
    'plot': 'plot',
    'plots': 'plot',
    'land': 'plot',
    'land plot': 'plot',
    'land/plot': 'plot',
    'residential plot': 'plot',

    # Penthouse
    'penthouse': 'penthouse',

    # Farmhouse
    'farmhouse': 'farmhouse',

    # Other
    'luxury segment': 'luxuryhouse',
    'other': 'other'
}


# APPLY MAPPING
df['property_type_cleaned'] = (
    df['property_type_cleaned']
    .map(property_mapping)
)

# fill unmapped values as 'other'
df['property_type_cleaned'] = (
    df['property_type_cleaned']
    .fillna('other')
)


# DROP ORIGINAL COLUMN
df.drop(columns=['property_type'], inplace=True)

#  Rename
df.rename(
    columns={'property_type_cleaned': 'property_type'},
    inplace=True
)

print(df['property_type'].value_counts())

property_type
apartment        1050
other             554
villa             125
house              66
plot               35
builder floor      28
penthouse          19
farmhouse           2
luxuryhouse         1
Name: count, dtype: int64

In [448]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1880 entries, 0 to 1883
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    1880 non-null   object
 1   Location                1880 non-null   object
 2   Price (INR in Lakhs)    1880 non-null   float64
 3   Price_per_sqft          1874 non-null   float64
 4   Area_sqft               1880 non-null   float64
 5   Description             1880 non-null   object
 6   Property_URL            1880 non-null   object
 7   bedrooms                1737 non-null   float64
 8   bathrooms               1737 non-null   float64
 9   balconies               1737 non-null   float64
 10  current_floor           891 non-null    float64
 11  total_floors            850 non-null    object
 12  furnishing_status       812 non-null    object
 13  amenities               1695 non-null   object
 14  additional_rooms        1695 non-null   object
 15  nearby                  1695 non-null   object
 16  additional_insights     1695 non-null   object
 17  Mapped_Area             1880 non-null   object
 18  facing                  549 non-null    object
 19  property_age_bucket     1880 non-null   object
 20  is_ready_to_move        1880 non-null   int64
 21  is_built_up_area        1880 non-null   bool
 22  is_carpet_area          1880 non-null   bool
 23  is_super_built_up_area  1880 non-null   bool
 24  property_type           1880 non-null   object
dtypes: bool(3), float64(7), int64(1), object(14)
memory usage: 407.9+ KB

In [ ]:
df['current_floor_clean'].value_counts()
df.drop(columns=['current_floor_clean'], inplace=True)

In [ ]:
df['is_new_property'].value_counts()
df.drop(columns=['is_new_property'], inplace=True)

In [ ]:
df['current_floor_missing'].value_counts()
df['total_floors_missing'].value_counts()
df.drop(columns=["current_floor_missing", "total_floors_missing"], inplace=True)

In [ ]:
df['age_possession'].value_counts()
df.drop(columns=["age_possession"], inplace=True)

In [ ]:
# df['property_age_bucket'].value_counts()
df['is_new_property'].value_counts()

is_new_property
1    1070
0     810
Name: count, dtype: int64

In [424]:
df['nearby'].value_counts()

nearby
[]                                                                                                                      1247
[school, hospital, metro, mall, highway]                                                                                  35
[school]                                                                                                                  19
[metro]                                                                                                                   12
[school, hospital, metro]                                                                                                 11
[school, hospital]                                                                                                        10
[hospital]                                                                                                                 9
[highway]                                                                                                                  9
[hospitals, ambe mata mandir]                                                                                              8
[school, hospital, mall, highway]                                                                                          7
[temple, hospital]                                                                                                         7
[gift city]                                                                                                                6
[metro station, gift city]                                                                                                 6
[hospitals]                                                                                                                5
[gift city, metro station]                                                                                                 5
[temples, hospitals]                                                                                                       4
[temple]                                                                                                                   4
[school, hospital, market]                                                                                                 4
[school, markets]                                                                                                          4
[podar international]                                                                                                      4
[sheth n.N saravajanik hospital, randheja railway station]                                                                 4
[schools, hospitals]                                                                                                       3
[sg highway]                                                                                                               3
[hospital, temple]                                                                                                         3
[hospitals, shree satay narayan mandir]                                                                                    3
[12 meter road]                                                                                                            3
[relience circle]                                                                                                          2
[s p ring road]                                                                                                            2
[hospitals, infocity]                                                                                                      2
[schools, hospital, shopping]                                                                                              2
[mall, school]                                                                                                             2
[gandhinagar, kalol]                                                                                                       2
[pdpu metro, national highway 48]                                                                                          2
[temples, healthcare facilities]                                                                                           2
[religious landmarks, several]                                                                                             2
[school, market]                                                                                                           2
[shri hanumanji temple, multiple hospitals]                                                                                2
[hospitals, schools, markets]                                                                                              2
[hospital, school]                                                                                                         2
[hospitals, temple]                                                                                                        2
[religious sites]                                                                                                          2
[metro, malls, schools]                                                                                                    2
[school, hospital, mall]                                                                                                   2
[highway, mall]                                                                                                            2
[health focus physiotherapy clinic, infocity, pandit deendayal petroleum university]                                       2
[metro station, hospital]                                                                                                  2
[metro, school]                                                                                                            2
[hospital, railway station]                                                                                                2
[metro, road, highway]                                                                                                     1
[key connectivity points, schools]                                                                                         1
[hospitals, schools, markets, khodiyar temple, bank of baroda atm]                                                         1
[key religious sites, medical facilities]                                                                                  1
[metro, malls, schools, highways]                                                                                          1
[metro, market, pdpu, swaminarayan kanyashala, cuty pulse cinema, temples, svms hospital]                                  1
[hospitals, clubhouse]                                                                                                     1
[metro, religious sites]                                                                                                   1
[top schools, hospitals, sarkhej gandhinagar highway]                                                                      1
[health focus physiotherapy clinic, infocity]                                                                              1
[school, airport, shopping]                                                                                                1
[school, hospital, university]                                                                                             1
[schools, market, main road]                                                                                               1
[school, hotel, mall]                                                                                                      1
[schools, markets, hospitals]                                                                                              1
[sanjari park, pethapur]                                                                                                   1
[markets, metro, schools, railways]                                                                                        1
[hospitals, supreme smile dental clinic, gayatri hospital]                                                                 1
[prominent temples, multispeciality clinic]                                                                                1
[hospital, mall, railway station]                                                                                          1
[religious sites, multispecialty clinic]                                                                                   1
[multiple temples, dental clinic]                                                                                          1
[swaminarayan temple, gayatri hospital]                                                                                    1
[schools, hospital, mall, highway]                                                                                         1
[temples, medical facilities]                                                                                              1
[khodiyar temple, medical facilities, atms]                                                                                1
[hospitals, shr hanumanji temple]                                                                                          1
[bus depots, school]                                                                                                       1
[key healthcare facilities, infocity office complex]                                                                       1
[metro, highway]                                                                                                           1
[hospitals, infocity office complex]                                                                                       1
[pdpu road, gift city, metro station]                                                                                      1
[koba circle metro, schools, nh 48, esic hospital]                                                                         1
[nh147, sahjanand school, shoppers plaza]                                                                                  1
[multiple religious sites, shree mahakali mataji temple, swaminarayan temple]                                              1
[school, shopping malls, hospitals, garden]                                                                                1
[metro, hospitals, office complexes]                                                                                       1
[tcs, software company offices]                                                                                            1
[schools, hospital, shopping at swagat holiday mall]                                                                       1
[temples, clinics]                                                                                                         1
[multiple hospitals, health focus physiotherapy clinic]                                                                    1
[sg highway, adalaj petrol pump]                                                                                           1
[several temples]                                                                                                          1
[metro, schools]                                                                                                           1
[ramdevpir temple, Pethapur, gandhinagar]                                                                                  1
[tech parks, infocity, gift city, s.G. Highway, swagat holiday mall, dmart]                                                1
[sg highway, daiict, aashka hospital]                                                                                      1
[sbi bank, temple, market, school, rickshaw stand]                                                                         1
[railway station, medical college hospital, city bus stand]                                                                1
[school, hospital, highway, mall]                                                                                          1
[school, hospital, bus stop, highway]                                                                                      1
[relience smart bazar]                                                                                                     1
[science city circle]                                                                                                      1
[hospital, school, malls]                                                                                                  1
[poddar international school]                                                                                              1
[vavol pundrasan road]                                                                                                     1
[city pulse cinema, urjanagar 1 area]                                                                                      1
[S.G highway]                                                                                                              1
[pdpu road]                                                                                                                1
[sargasan cross road]                                                                                                      1
[d' mart]                                                                                                                  1
[mall, school, hospital]                                                                                                   1
[infocity area, national institute of design road]                                                                         1
[kh road]                                                                                                                  1
[club house]                                                                                                               1
[markets, hospital, school, malls]                                                                                         1
[schools, markets]                                                                                                         1
[metro station, school, hospital, highway]                                                                                 1
[school, mall, temple, garden]                                                                                             1
[school, hospital, shopping mall]                                                                                          1
[school, shopping malls]                                                                                                   1
[school, hospital, metro, mall, highway, airport, park]                                                                    1
[metro, rever]                                                                                                             1
[school, hospital, bazaar]                                                                                                 1
[schools, healthcare, shri hanumanji temple]                                                                               1
[temple, dental clinic]                                                                                                    1
[key medical facilities, gandhinagar]                                                                                      1
[railway station, metro station, mall, market]                                                                             1
[swaminarayan temple, hospitals]                                                                                           1
[malls, highways]                                                                                                          1
[hospitals, religious sites]                                                                                               1
[schools, hospitals, banks]                                                                                                1
[metro, market, hospital, school]                                                                                          1
[shopping malls, highways]                                                                                                 1
[school, shopping hubs]                                                                                                    1
[schools, malls, connectivity hubs]                                                                                        1
[highway, mall, companies]                                                                                                 1
[hospitals, religious site]                                                                                                1
[key hospitals, shree satay narayan mandir]                                                                                1
[school, vegetable market, temple, railway station, bus port]                                                              1
[khodiyar temple, bank of baroda atm, hospitals]                                                                           1
[key temples, healthcare centers]                                                                                          1
[hospital, school, market]                                                                                                 1
[vachhani hospital, kroma multispeciality dental clinic]                                                                   1
[health clinics, infocity office complex, pandit deendayal petroleum university]                                           1
[city, highway, shopping centre]                                                                                           1
[amenities]                                                                                                                1
[temples, clinics, fitness center]                                                                                         1
[mini market, sikshapatri road, vaishnodevi circle, gift city]                                                             1
[healthcare facilities, Pandit Deendayal Petroleum University]                                                             1
[malls, highway]                                                                                                           1
[hospital, market, metro station]                                                                                          1
[hospital, garden]                                                                                                         1
[metro, school, hospital, market]                                                                                          1
[mahudi tirth jain temple, mahudi jain temple]                                                                             1
[schools, malls, nh 48 connectivity]                                                                                       1
[IIT Gandhinagar, Gift City Circle]                                                                                        1
[super mall, reputed schools, shraddha womens hospital]                                                                    1
[highway, bus stand, vegetable market, hotels]                                                                             1
[metro, airport]                                                                                                           1
[gayatri mandir, hospitals]                                                                                                1

In [426]:
df['Mapped_Area'].value_counts()

Mapped_Area
Sargasan               487
Kudasan                271
Gift City              155
Raysan                 130
Randesan               127
Vavol                  123
Koba                   118
Kalol                  106
Pethapur                44
Dahegam                 38
Randheja                37
Palodia                 35
Mansa                   20
Uvarsad                 18
Gandhinagar Taluka      18
Khoraj                  15
Chiloda                 12
SP Ring Road            11
Sector 26               10
Alampur                  9
Sector 29                9
Sector 22                8
Adalaj                   7
Kolavada                 6
Sector 4                 6
Sector 3                 5
Sector 8                 5
Ambapur                  5
Other                    4
Karai                    4
Sector 25                4
SG Highway               4
Valad                    3
Nabhoi                   3
Sector 21                2
Sector 7                 2
Dabhoda                  2
Sector 2                 2
Sector 5                 2
Sector 28                2
Sector 6                 2
Sector 11                1
Sughad                   1
Sector 16                1
Outside Gandhinagar      1
Sector 30                1
Sector 19                1
Sector 1                 1
Sector 24                1
Sector 27                1
Name: count, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1880 entries, 0 to 1883
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    1880 non-null   object
 1   Location                1880 non-null   object
 2   Price (INR in Lakhs)    1880 non-null   float64
 3   Price_per_sqft          1874 non-null   float64
 4   Area_sqft               1880 non-null   float64
 5   Description             1880 non-null   object
 6   Property_URL            1880 non-null   object
 7   bedrooms                1737 non-null   float64
 8   bathrooms               1737 non-null   float64
 9   balconies               1737 non-null   float64
 10  current_floor           891 non-null    float64
 11  total_floors            850 non-null    object
 12  furnishing_status       812 non-null    object
 13  amenities               1695 non-null   object
 14  additional_rooms        1695 non-null   object
 15  nearby                  1695 non-null   object
 16  additional_insights     1695 non-null   object
 17  Mapped_Area             1880 non-null   object
 18  facing                  549 non-null    object
 19  property_age_bucket     1880 non-null   object
 20  is_ready_to_move        1880 non-null   int64
 21  is_built_up_area        1880 non-null   bool
 22  is_carpet_area          1880 non-null   bool
 23  is_super_built_up_area  1880 non-null   bool
 24  property_type           1880 non-null   object
dtypes: bool(3), float64(7), int64(1), object(14)
memory usage: 407.9+ KB

In [549]:
df['amenities'].value_counts()

amenities
[]                                                                                                                                    1484
[lift, garden, parking, clubhouse, swimming pool, gym, security, power backup]                                                          10
[lift, gym, security, power backup]                                                                                                      7
[lift]                                                                                                                                   7
[lift, garden, parking, clubhouse, power backup]                                                                                         6
[parking]                                                                                                                                6
[lift, parking]                                                                                                                          5
[lift, garden, parking, security, power backup]                                                                                          5
[swimming pool, fitness centre / gym]                                                                                                    4
[landscaped gardens, childrens play areas, clubhouse, security]                                                                          4
[24 hour water, 24 hour electricity, solar system]                                                                                       3
[fitness center, clubhouse]                                                                                                              3
[visitor parking]                                                                                                                        3
[fitness center]                                                                                                                         3
[lift, power backup, rainwater harvesting]                                                                                               2
[lift, gym, swimming pool]                                                                                                               2
[party plot/garden, common parking area, 24 hr. Water, 24 hr. electricity, pipeline gas connection]                                      2
[gym, indoor games, community hall, home theatre, water body, conference room, working office]                                           2
[fitness center, clubhouse, swimming pool]                                                                                               2
[gym, clubhouse, swimming pool, lift]                                                                                                    2
[gym, clubhouse, pool, power backup]                                                                                                     2
[lift, parking, clubhouse, swimming pool, power backup]                                                                                  2
[lift, fitness center]                                                                                                                   2
[gym, clubhouse, power backup, lift]                                                                                                     2
[lift, swimming pool]                                                                                                                    2
[fitness centre / gym, club house, park, shopping centre, lift(s)]                                                                       2
[swimming pool, fitness centre / gym, club house]                                                                                        2
[visitor parking, on-Call maintenance]                                                                                                   2
[gym, clubhouse, lift]                                                                                                                   2
[swimming pool]                                                                                                                          2
[clubhouse, swimming pool, garden]                                                                                                       2
[swimming pool, lift]                                                                                                                    2
[lift, garden, parking, clubhouse, security, power backup]                                                                               1
[clubhouse, garden, children play area, parking, power backup, security, cctv, pic and drop facility]                                    1
[club house, chi]                                                                                                                        1
[fitness centre / gym, club house, cctv surveillance, lift(s)]                                                                           1
[lift, gym, parking]                                                                                                                     1
[clubhouse, gym, cafe, badminton court, box cricket]                                                                                     1
[garden, gym, indoor play hall, common hall]                                                                                             1
[modular kitchen, wardrobes, parking]                                                                                                    1
[lift, garden, parking, electric geysers, fans, ac, solar panel, power backup]                                                           1
[gym, park, kids play area, tt area, community hall]                                                                                     1
[lift, gym, clubhouse, swimming pool]                                                                                                    1
[lift, parking, clubhouse, garden]                                                                                                       1
[rainwater harvesting, power backup, lift]                                                                                               1
[lift, power backup, rainwater harvesting, clubhouse]                                                                                    1
[lift, clubhouse, fitness center]                                                                                                        1
[gym, yoga room, children play area, community hall]                                                                                     1
[gym, garden, lift]                                                                                                                      1
[community hall, yoga room, garden, children play area]                                                                                  1
[3 car parking, lift, garden]                                                                                                            1
[garden, security, clubhouse]                                                                                                            1
[garden, gym, yoga room, theatre, club house, kids zone]                                                                                 1
[24/7 water, gated society security, visitor parking, on-Call maintenance]                                                               1
[club, power back-Up]                                                                                                                    1
[lift, garden, parking, clubhouse, swimming pool, gym, security, power backup, mini golf course, squash court, cafe]                     1
[swimming pool, gym, yoga room, table tennis room, badminton, children play area, cricket, walking track]                                1
[lift, gym, security]                                                                                                                    1
[swimming pool, fitness centre / gym, park, lift(s)]                                                                                     1
[swimming pool, fitness]                                                                                                                 1
[central ac, parking]                                                                                                                    1
[swimming pool, gym, garden, tennis court, clubhouse, 24x7 security, fire safety]                                                        1
[lift, power backup, childrens play area]                                                                                                1
[lift, fire safety system, 24 hours water supply, security]                                                                              1
[swimming pool, fitness centre / gym, park, club house, cctv surveillance]                                                               1
[gym, clubhouse]                                                                                                                         1
[landscaped gardens, childrens play area, yoga zone, cctv surveillance, gated security, ample parking]                                   1
[sky lounge, clubhouse, landscaped leisure zones]                                                                                        1
[cricket pitch, badminton court, cycling & jogging track, power backup]                                                                  1
[fitness]                                                                                                                                1
[gym, clubhouse, power backup, lift, rainwater harvesting]                                                                               1
[clubhouse, gym, lift, swimming pool]                                                                                                    1
[lift, on-Call maintenance]                                                                                                              1
[gym, rainwater harvesting, power backup, lift]                                                                                          1
[lift, power backup, parking, gym, clubhouse]                                                                                            1
[swimming pool, club house, cctv surveillance, lift(s)]                                                                                  1
[garden]                                                                                                                                 1
[lift, gym, clubhouse, cctv]                                                                                                             1
[lift, power backup, fire safety systems, 247 water supply]                                                                              1
[swimming pool, gym, clubhouse, lift]                                                                                                    1
[gymnasium, children's play area, swimming pool, sports avenues, library, business center, temple]                                       1
[lift, garden, parking, clubhouse]                                                                                                       1
[gym]                                                                                                                                    1
[indoor games, kids play area, 24 hours water supply, security]                                                                          1
[lift, garden, parking]                                                                                                                  1
[lift, gym, rooftop]                                                                                                                     1
[fitness centre / gym, parking, clubhouse, swimming pool]                                                                                1
[lift, gated society]                                                                                                                    1
[clubhouse, lift]                                                                                                                        1
[lift, gym, clubhouse]                                                                                                                   1
[park, lift]                                                                                                                             1
[lift, park]                                                                                                                             1
[lift, garden, park, fitness centre / gym]                                                                                               1
[parking, gated society]                                                                                                                 1
[gym, clubhouse, pool, parking, lift]                                                                                                    1
[gym, pool]                                                                                                                              1
[swimming pool, fitness centre / gym, grocery shop]                                                                                      1
[lift, visitor parking, on-Call maintenance]                                                                                             1
[fitness centre / gym, club house, lift(s)]                                                                                              1
[fitness centre / gym, club house, parking]                                                                                              1
[lift, power backup, parking]                                                                                                            1
[clubhouse, gym, parking]                                                                                                                1
[power backup, visitor parking]                                                                                                          1
[lift, gym, clubhouse, swimming pool, parking]                                                                                           1
[clubhouse, swimming pool, lift, power backup]                                                                                           1
[clubhouse, gym]                                                                                                                         1
[air-conditioned, parking]                                                                                                               1
[lift, gym, clubhouse, swimming pool, power backup]                                                                                      1
[lift, parking, garden]                                                                                                                  1
[lift, clubhouse, gym, swimming pool]                                                                                                    1
[fitness centre / gym]                                                                                                                   1
[clubhouse, gym, lift]                                                                                                                   1
[lift, power backup, central ac]                                                                                                         1
[lift, power backup, visitor parking, on-Call maintenance]                                                                               1
[clubhouse, gym, swimming pool, lift, parking, power backup]                                                                             1
[power backup, clubhouse]                                                                                                                1
[lift, parking, gated society access, on-Call maintenance]                                                                               1
[lift, clubhouse, gym, 24/7 water]                                                                                                       1
[lift, garden, outdoor play area, banquet hall, badminton court, cricket pitch, indoor cinema, indoor play area, library, parking]       1
[lift, gated security, power backup]                                                                                                     1
[clubhouse, gym, lift, pool]                                                                                                             1
[lift, gym, swimming pool, power backup]                                                                                                 1
[gym, swimming pool, lift, power backup]                                                                                                 1
[gym, clubhouse, lift, power backup]                                                                                                     1
[lift, parking, solar system]                                                                                                            1
[power backup, parking]                                                                                                                  1
[lift, cctv surveillance]                                                                                                                1
[lift, gym, clubhouse, parking, swimming pool]                                                                                           1
[parking, gym, clubhouse, lift]                                                                                                          1
[garden, club house, gym]                                                                                                                1
[lift, parking, cctv camera, power backup]                                                                                               1
[full power backup, 24x7 water, on-Call maintenance]                                                                                     1
[swimming pool, gym, tennis, table tennis, carom, ches, library]                                                                         1
[lift, gym, parking, power backup]                                                                                                       1
[parking, power backup]                                                                                                                  1
[gym, swimming pool]                                                                                                                     1
[fitness center, power backup]                                                                                                           1
[car parking facility, 24 hours water]                                                                                                   1
[lift, security, 24x7 water supply]                                                                                                      1
[visitor parking, modular kitchen]                                                                                                       1
[gated security, modular kitchen, 24/7 water]                                                                                            1
Name: count, dtype: int64

In [ ]:
amenity_mapping = {

    # LIFT
    "lift": "lift",
    "lift(s)": "lift",

    # GARDEN / OPEN SPACES
    "garden": "garden",
    "landscaped gardens": "garden",
    "party plot/garden": "garden",

    "park": "park",

    "landscaped leisure zones": "leisure zone",

    # PARKING
    "parking": "parking",
    "visitor parking": "parking",
    "car parking facility": "parking",
    "common parking area": "parking",
    "ample parking": "parking",
    "3 car parking": "parking",

    # CLUBHOUSE / COMMUNITY
    "clubhouse": "clubhouse",
    "club house": "clubhouse",
    "club": "clubhouse",

    "community hall": "community hall",
    "common hall": "community hall",

    "banquet hall": "banquet hall",

    "conference room": "conference room",

    "working office": "office",

    "business center": "business center",

    "sky lounge": "sky lounge",

    # SWIMMING / WATER
    "swimming pool": "swimming pool",
    "pool": "swimming pool",

    "water body": "water body",

    # FITNESS / GYM
    "gym": "gym",

    "fitness center": "gym",
    "fitness centre / gym": "gym",
    "fitness centre": "gym",
    "fitness": "gym",
    "gymnasium": "gym",

    # SECURITY
    "security": "security",

    "cctv surveillance": "security",
    "cctv camera": "security",

    "gated society security": "security",
    "gated security": "security",
    "24x7 security": "security",

    "fire safety": "fire safety",
    "fire safety system": "fire safety",
    "fire safety systems": "fire safety",

    # POWER BACKUP
    "power backup": "power backup",
    "power back-Up": "power backup",
    "full power backup": "power backup",

    # WATER / ELECTRICITY
    "24 hour water": "water supply",
    "24 hr. water": "water supply",
    "24 hours water supply": "water supply",
    "24/7 water": "water supply",
    "247 water supply": "water supply",
    "24x7 water supply": "water supply",

    "24 hour electricity": "electricity supply",
    "24 hr. electricity": "electricity supply",

    # RAINWATER / SOLAR / GAS
    "rainwater harvesting": "rainwater harvesting",

    "solar system": "solar",
    "solar panel": "solar",

    "pipeline gas connection": "gas",

    # INDOOR GAMES / SPORTS
    "indoor games": "indoor games",

    "indoor play hall": "indoor play area",
    "indoor play area": "indoor play area",

    "indoor cinema": "home theater",

    "table tennis room": "table tennis",
    "table tennis": "table tennis",
    "tt area": "table tennis",

    "carom": "carom",
    "ches": "chess",

    "badminton court": "badminton",
    "badminton": "badminton",

    "box cricket": "cricket",
    "cricket pitch": "cricket",
    "cricket": "cricket",

    "tennis court": "tennis",
    "tennis": "tennis",

    "squash court": "squash",

    "mini golf course": "mini golf",

    "cycling & jogging track": "jogging track",
    "walking track": "walking track",

    # CHILDREN
    "childrens play areas": "playground",
    "childrens play area": "playground",
    "children play area": "playground",
    "children's play area": "playground",
    "kids play area": "playground",
    "kids zone": "playground",

    # YOGA / WELLNESS
    "yoga room": "yoga",
    "yoga zone": "yoga",

    # LIBRARY / SHOPPING / CAFE
    "library": "library",

    "grocery shop": "grocery",

    "shopping centre": "shopping center",

    "cafe": "cafe",

    # HOME THEATER / ROOFTOP
    "home theatre": "home theater",
    "theatre": "home theater",

    "rooftop": "rooftop",

    # MAINTENANCE
    "on-call maintenance": "maintenance",

    # INTERIOR FEATURES
    "modular kitchen": "modular kitchen",

    "wardrobes": "wardrobes",

    "electric geysers": "water heater",

    "fans": "fans",

    "ac": "air conditioning",
    "central ac": "air conditioning",
    "air-conditioned": "air conditioning",

    # GATED COMMUNITY
    "gated society": "gated community",
    "gated society access": "gated community",

    # MISC
    "sports avenues": "sports facilities",

    "temple": "temple",

    "chi": "other",
}

In [ ]:
# NORMALIZE AMENITIES
def normalize_amenities(x):

    # Handle null values
    if x is None:
        return []

    if isinstance(x, float) and pd.isna(x):
        return []

    # If already list
    if isinstance(x, (list, np.ndarray)):
        amenities = x

    else:
        try:
            amenities = ast.literal_eval(str(x))
        except:
            return []

    cleaned = []

    for item in amenities:

        item = str(item).strip().lower()

        # APPLY YOUR MAPPING
        item = amenity_mapping.get(item, item)

        cleaned.append(item)

    # Remove duplicates
    cleaned = list(set(cleaned))

    return cleaned


# CREATE NORMALIZED COLUMN
df["normalized_amenities"] = df["amenities"].apply(
    normalize_amenities
)

In [ ]:
# LUXURY SCORE WEIGHTS

luxury_weights = {

    # BASIC AMENITIES
    "lift": 1,
    "parking": 1,
    "security": 1,
    "water supply": 1,
    "electricity supply": 1,
    "maintenance": 1,
    "fans": 1,
    "wardrobes": 1,
    "water heater": 1,

    # STANDARD SOCIETY FEATURES
    "garden": 2,
    "park": 2,
    "gym": 2,
    "clubhouse": 2,
    "power backup": 2,
    "playground": 2,
    "gated community": 2,
    "rainwater harvesting": 2,
    "shopping center": 2,
    "grocery": 2,
    "modular kitchen": 2,
    "visitor parking": 2,
    "leisure zone": 2,
    "party garden": 2,

    # PREMIUM FEATURES
    "swimming pool": 3,
    "community hall": 3,
    "indoor games": 3,
    "indoor play area": 3,
    "yoga": 3,
    "badminton": 3,
    "cricket": 3,
    "tennis": 3,
    "table tennis": 3,
    "library": 3,
    "business center": 3,
    "conference room": 3,
    "office": 3,
    "banquet hall": 3,
    "sports facilities": 3,
    "walking track": 3,
    "jogging track": 3,
    "cycling track": 3,
    "solar": 3,
    "gas": 3,
    "rooftop": 3,
    "air conditioning": 3,

    # LUXURY FEATURES
    "home theater": 5,
    "mini golf": 5,
    "squash": 5,
    "sky lounge": 5,
    "water body": 5,

    # EXTRA FEATURES
    "cafe": 2,
    "carom": 1,
    "chess": 1,
    "temple": 1,
    "fire safety": 2,
    "sports avenues": 3,
    "other": 0,
}

# CALCULATE LUXURY SCORE

def calculate_luxury_score(amenities):

    score = 0

    for amenity in amenities:

        score += luxury_weights.get(amenity, 0)

    return score


# APPLY
df["luxury_score"] = df["normalized_amenities"].apply(
    calculate_luxury_score
)

# CHECK RESULTS
print(df[[
    "normalized_amenities",
    "luxury_score"
]].sample(5))

     normalized_amenities  luxury_score
1726                   []             0
1433                   []             0
1416            [parking]             1
843                    []             0
1719                   []             0

In [ ]:
df.drop(columns=["normalized_amenities","cleaned_amenities","amenities"], inplace=True)

In [580]:
df.drop(columns=["additional_rooms"], inplace=True)

In [ ]:
nearby_mapping = {

    # EDUCATION
    "school": "school",
    "schools": "school",
    "college": "college",
    "university": "university",
    "educational institutions": "education hub",
    "educational institutes": "education hub",
    "educational hubs": "education hub",
    "major schools": "school",
    "top schools": "school",
    "podar international": "school",
    "poddar international school": "school",

    # HEALTHCARE
    "hospital": "hospital",
    "hospitals": "hospital",
    "healthcare facilities": "hospital",
    "healthcare centers": "hospital",
    "medical facilities": "hospital",
    "medical hospital": "hospital",
    "clinic": "hospital",
    "clinics": "hospital",

    # TRANSPORT
    "metro": "metro",
    "metro station": "metro",

    "railway station": "railway station",
    "bus stand": "bus stand",
    "bus station": "bus stand",
    "bus depot": "bus stand",
    "bus depots": "bus stand",

    "airport": "airport",

    # ROAD CONNECTIVITY
    "highway": "highway",
    "sg highway": "highway",
    "s.g. highway": "highway",
    "nh 48": "highway",
    "national highway 48": "highway",

    "road": "road",
    "main road": "road",

    # SHOPPING / COMMERCIAL
    "mall": "mall",
    "malls": "mall",
    "shopping mall": "mall",
    "shopping malls": "mall",

    "market": "market",
    "markets": "market",
    "bazaar": "market",
    "shops": "market",
    "mini market": "market",

    "shopping": "shopping",
    "shopping centre": "shopping",

    "cinema": "entertainment",
    "theatre": "entertainment",

    # PREMIUM LOCATIONS
    "gift city": "gift city",
    "infocity": "infocity",
    "tech parks": "tech park",
    "tcs": "tech park",
    "software company offices": "tech park",

    "river front": "riverfront",
    "riverfront": "riverfront",

    # RELIGIOUS
    "temple": "temple",
    "temples": "temple",
    "religious sites": "temple",
    "religious landmarks": "temple",

    # PARKS / GREENERY
    "garden": "garden",
    "park": "park",

    # BANKING
    "banks": "bank",
    "bank of baroda atm": "bank",
    "sbi bank": "bank",
}

In [585]:
location_weights = {

    # BASIC
    "school": 1,
    "hospital": 1,
    "market": 1,
    "road": 1,
    "bank": 1,
    "temple": 1,

    # GOOD CONNECTIVITY
    "metro": 3,
    "railway station": 2,
    "bus stand": 1,
    "highway": 3,
    "airport": 5,

    # PREMIUM SOCIAL INFRA
    "mall": 2,
    "shopping": 2,
    "entertainment": 2,
    "park": 2,
    "garden": 2,

    # EDUCATION
    "college": 2,
    "university": 3,
    "education hub": 3,

    # PREMIUM BUSINESS HUBS
    "gift city": 5,
    "infocity": 4,
    "tech park": 4,

    # ULTRA PREMIUM
    "riverfront": 6,
}

In [ ]:
def normalize_nearby(x):

    if x is None:
        return []

    if isinstance(x, float) and pd.isna(x):
        return []

    if isinstance(x, (list, np.ndarray)):
        nearby = x
    else:
        try:
            nearby = ast.literal_eval(str(x))
        except:
            return []

    cleaned = []

    for item in nearby:

        item = str(item).strip().lower()

        item = nearby_mapping.get(item, item)

        cleaned.append(item)

    return list(set(cleaned))


df["normalized_nearby"] = df["nearby"].apply(
    normalize_nearby
)

In [587]:
def calculate_location_score(nearby_list):

    score = 0

    for item in nearby_list:

        score += location_weights.get(item, 0)

    return score


df["location_advantage_score"] = df[
    "normalized_nearby"
].apply(calculate_location_score)

In [588]:
df.drop(
    columns=["nearby", "normalized_nearby"],
    inplace=True
)

In [589]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1880 entries, 0 to 1883
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Name                      1880 non-null   object
 1   Location                  1880 non-null   object
 2   Price (INR in Lakhs)      1880 non-null   float64
 3   Price_per_sqft            1874 non-null   float64
 4   Area_sqft                 1880 non-null   float64
 5   Description               1880 non-null   object
 6   Property_URL              1880 non-null   object
 7   bedrooms                  1737 non-null   float64
 8   bathrooms                 1737 non-null   float64
 9   balconies                 1737 non-null   float64
 10  current_floor             891 non-null    float64
 11  total_floors              850 non-null    object
 12  furnishing_status         812 non-null    object
 13  additional_insights       1695 non-null   object
 14  Mapped_Area               1880 non-null   object
 15  facing                    549 non-null    object
 16  property_age_bucket       1880 non-null   object
 17  is_ready_to_move          1880 non-null   int64
 18  is_built_up_area          1880 non-null   bool
 19  is_carpet_area            1880 non-null   bool
 20  is_super_built_up_area    1880 non-null   bool
 21  property_type             1880 non-null   object
 22  luxury_score              1880 non-null   int64
 23  location_advantage_score  1880 non-null   int64
dtypes: bool(3), float64(7), int64(3), object(11)
memory usage: 393.2+ KB

In [ ]:
import numpy as np

mask = (
    df["Description"].isna()
    | (df["Description"].astype(str).str.strip() == "")
)

df.loc[mask, "luxury_score"] = np.nan
df.loc[mask, "location_advantage_score"] = np.nan
df.loc[mask, "property_type"] = np.nan

In [ ]:
# BONUS WEIGHTS FROM additional_insights

insight_bonus = {

    "luxury property": 5,
    "prime location": 4,
    "riverfront": 6,

    "park facing": 3,
    "garden facing": 3,

    "corner property": 2,
    "road facing": 2,

    "vastu compliant": 1,
    "vaastu compliant": 1,

    "newly built": 2,
    "new construction": 2,
    "fresh construction": 2,

    "gated society": 2,

    "under construction": -1,
    "still under construction": -1,
}


# ADD BONUS TO EXISTING luxury_score
def add_insight_bonus(row):

    current_score = row["luxury_score"]

    insights = row["additional_insights"]

    # Handle null
    if insights is None:
        return current_score

    if isinstance(insights, float) and pd.isna(insights):
        return current_score

    # Convert string list to python list
    if not isinstance(insights, list):

        try:
            insights = ast.literal_eval(str(insights))
        except:
            return current_score

    bonus = 0

    for item in insights:

        item = str(item).strip().lower()

        bonus += insight_bonus.get(item, 0)

    return current_score + bonus


# UPDATE luxury_score
df["luxury_score"] = df.apply(
    add_insight_bonus,
    axis=1
)

In [ ]:
df.drop(columns=["additional_insights"], inplace=True)

In [618]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1880 entries, 0 to 1883
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Name                      1880 non-null   object
 1   Location                  1880 non-null   object
 2   Price (INR in Lakhs)      1880 non-null   float64
 3   Price_per_sqft            1874 non-null   float64
 4   Area_sqft                 1880 non-null   float64
 5   Description               1880 non-null   object
 6   Property_URL              1880 non-null   object
 7   bedrooms                  1737 non-null   float64
 8   bathrooms                 1737 non-null   float64
 9   balconies                 1737 non-null   float64
 10  current_floor             891 non-null    float64
 11  total_floors              850 non-null    object
 12  furnishing_status         812 non-null    object
 13  Mapped_Area               1880 non-null   object
 14  facing                    549 non-null    object
 15  property_age_bucket       1880 non-null   object
 16  is_ready_to_move          1880 non-null   int64
 17  is_built_up_area          1880 non-null   bool
 18  is_carpet_area            1880 non-null   bool
 19  is_super_built_up_area    1880 non-null   bool
 20  property_type             1722 non-null   object
 21  luxury_score              1722 non-null   float64
 22  location_advantage_score  1722 non-null   float64
dtypes: bool(3), float64(9), int64(1), object(10)
memory usage: 378.5+ KB

In [619]:
#  save this df to final CSV
df.to_csv("final.csv", index=False)

This is end of data preprocessing and feature engineering steps. Now we can move on to EDA and modeling.